// GENERATED by scripts/gen-test-suites.sh -- do not edit by hand.
// Regenerate with: scripts/gen-test-suites.sh
// Check for drift with: scripts/gen-test-suites.sh --check
//
// This file exists only to give cargo one test BINARY for the files listed
// below; it declares no tests of its own. Every included file keeps its
// original name, path, and test names (nextest's test list, with this
// suite's prefix stripped, is unchanged from before consolidation).
mod common;
#[path = "support/assertion.rs"]
mod assertion;
#[path = "support/oauth.rs"]
mod oauth;

#[path = "unkfield_ac01_write_table_rejected.rs"]
mod unkfield_ac01_write_table_rejected;
#[path = "unkfield_ac02_misplaced_field_valid_for.rs"]
mod unkfield_ac02_misplaced_field_valid_for;
#[path = "unkfield_ac03_near_miss_did_you_mean.rs"]
mod unkfield_ac03_near_miss_did_you_mean;
#[path = "unkfield_ac06_doc_examples_never_rejected.rs"]
mod unkfield_ac06_doc_examples_never_rejected;
#[path = "warmpool_ac06_ac07_tool_run.rs"]
mod warmpool_ac06_ac07_tool_run;
#[path = "wasmkind_ac04_independent_of_sandbox_mechanism.rs"]
mod wasmkind_ac04_independent_of_sandbox_mechanism;
#[path = "xaa_ac02_python_env_and_grants_method_xaa.rs"]
mod xaa_ac02_python_env_and_grants_method_xaa;
