// GENERATED by scripts/gen-test-suites.sh -- do not edit by hand.
// Regenerate with: scripts/gen-test-suites.sh
// Check for drift with: scripts/gen-test-suites.sh --check
//
// This file exists only to give cargo one test BINARY for the files listed
// below; it declares no tests of its own. Every included file keeps its
// original name, path, and test names (nextest's test list, with this
// suite's prefix stripped, is unchanged from before consolidation).
mod common;
mod ci_sandbox_support;
#[path = "support/assertion.rs"]
mod assertion;
#[path = "support/busyaudit.rs"]
mod busyaudit;
#[path = "support/chart_fixture.rs"]
mod chart_fixture;
#[path = "support/docs_qa.rs"]
mod docs_qa;
#[path = "support/fake_as.rs"]
mod fake_as;
#[path = "support/federation.rs"]
mod federation;
#[path = "support/host.rs"]
#[allow(dead_code)]
mod host;
#[path = "support/lanecov.rs"]
mod lanecov;
#[path = "support/oauth.rs"]
mod oauth;
#[path = "support/oauthclient.rs"]
mod oauthclient;

#[path = "ac01_extended_gates_prd_path_resolves_and_matches_card.rs"]
mod ac01_extended_gates_prd_path_resolves_and_matches_card;
#[path = "ac01_unauthenticated_lists_signup.rs"]
mod ac01_unauthenticated_lists_signup;
#[path = "ac02_signup_creates_hashed_tenant.rs"]
mod ac02_signup_creates_hashed_tenant;
#[path = "ac03_tenant_lists_control_plane_only.rs"]
mod ac03_tenant_lists_control_plane_only;
#[path = "ac04_publish_list_and_call.rs"]
mod ac04_publish_list_and_call;
#[path = "ac05_cross_tenant_isolation.rs"]
mod ac05_cross_tenant_isolation;
#[path = "ac06_remove_tool.rs"]
mod ac06_remove_tool;
#[path = "ac07_usage_metering.rs"]
mod ac07_usage_metering;
#[path = "ac08_admin_disable_and_forbidden.rs"]
mod ac08_admin_disable_and_forbidden;
#[path = "ac09_signup_rate_limit.rs"]
mod ac09_signup_rate_limit;
#[path = "ac10_publish_validation_errors.rs"]
mod ac10_publish_validation_errors;
#[path = "ac11_load_smoke.rs"]
mod ac11_load_smoke;
#[path = "ac12_preflight.rs"]
mod ac12_preflight;
#[path = "ac13_mcp_name_mismatch_metering.rs"]
mod ac13_mcp_name_mismatch_metering;
#[path = "ac14_storage_unwritable.rs"]
mod ac14_storage_unwritable;
#[path = "ac15_call_timeout.rs"]
mod ac15_call_timeout;
#[path = "ac16_request_body_too_large.rs"]
mod ac16_request_body_too_large;
#[path = "ac18_tools_list_ttl.rs"]
mod ac18_tools_list_ttl;
#[path = "ac19_registry_publish.rs"]
mod ac19_registry_publish;
#[path = "agentdir_ac01_ac02_ac03_ac04_identity_and_lookup.rs"]
mod agentdir_ac01_ac02_ac03_ac04_identity_and_lookup;
#[path = "agentdir_ac05_ac06_search.rs"]
mod agentdir_ac05_ac06_search;
#[path = "agentdir_ac07_ac09_ac10_lifecycle.rs"]
mod agentdir_ac07_ac09_ac10_lifecycle;
#[path = "agentdir_ac08_lookup_latency.rs"]
mod agentdir_ac08_lookup_latency;
#[path = "alert_ac01_signup_paused_webhook_delivered.rs"]
mod alert_ac01_signup_paused_webhook_delivered;
#[path = "alert_ac02_cooldown_collapses_repeat_alert.rs"]
mod alert_ac02_cooldown_collapses_repeat_alert;
#[path = "alert_ac03_quota_trip_raises_once_per_tenant_knob.rs"]
mod alert_ac03_quota_trip_raises_once_per_tenant_knob;
#[path = "alert_ac04_errors_rate_over_five_min.rs"]
mod alert_ac04_errors_rate_over_five_min;
#[path = "alert_ac05_webhook_retries_then_failed.rs"]
mod alert_ac05_webhook_retries_then_failed;
#[path = "alert_ac06_tenant_inbox_delivery.rs"]
mod alert_ac06_tenant_inbox_delivery;
#[path = "alert_ac07_admin_alerts_list_and_ack.rs"]
mod alert_ac07_admin_alerts_list_and_ack;
#[path = "alert_ac08_store_only_when_no_sink_configured.rs"]
mod alert_ac08_store_only_when_no_sink_configured;
#[path = "alert_ac09_min_severity_filters_delivery.rs"]
mod alert_ac09_min_severity_filters_delivery;
#[path = "alert_ac10_healthz_reports_open_and_last_raised_at.rs"]
mod alert_ac10_healthz_reports_open_and_last_raised_at;
#[path = "alert_ac11_raise_body_size_limit.rs"]
mod alert_ac11_raise_body_size_limit;
#[path = "attrib_ac1_loopback_signup_unstamped.rs"]
mod attrib_ac1_loopback_signup_unstamped;
#[path = "attrib_ac2_clientinfo_captured.rs"]
mod attrib_ac2_clientinfo_captured;
#[path = "attrib_ac3_backfill_migration.rs"]
mod attrib_ac3_backfill_migration;
#[path = "attrib_ac4_external_signup_counts_real.rs"]
mod attrib_ac4_external_signup_counts_real;
#[path = "attrib_ac5_funnel_report.rs"]
mod attrib_ac5_funnel_report;
#[path = "attrib_ac6_whoami_source_class.rs"]
mod attrib_ac6_whoami_source_class;
#[path = "attribdefault_ac1_bare_signup_client_info_is_null.rs"]
mod attribdefault_ac1_bare_signup_client_info_is_null;
#[path = "attribdefault_ac2_real_clientinfo_still_captured.rs"]
mod attribdefault_ac2_real_clientinfo_still_captured;
#[path = "autherr_ac1_tenant_key_missing.rs"]
mod autherr_ac1_tenant_key_missing;
#[path = "autherr_ac2_tenant_key_invalid.rs"]
mod autherr_ac2_tenant_key_invalid;
#[path = "autherr_ac3_disabled_tenant_key_invalid.rs"]
mod autherr_ac3_disabled_tenant_key_invalid;
#[path = "autherr_ac4_bearer_invalid_unchanged.rs"]
mod autherr_ac4_bearer_invalid_unchanged;
#[path = "autherr_ac5_instructions_mention_codes.rs"]
mod autherr_ac5_instructions_mention_codes;
#[path = "banlist_ac01_addr_ban_blocks_signup.rs"]
mod banlist_ac01_addr_ban_blocks_signup;
#[path = "banlist_ac02_key_ban_blocks_authenticated_calls.rs"]
mod banlist_ac02_key_ban_blocks_authenticated_calls;
#[path = "banlist_ac03_public_flag_controls_reason_visibility.rs"]
mod banlist_ac03_public_flag_controls_reason_visibility;
#[path = "banlist_ac04_auto_ban_on_network_denials.rs"]
mod banlist_ac04_auto_ban_on_network_denials;
#[path = "banlist_ac05_auto_ban_on_claim_rate_events.rs"]
mod banlist_ac05_auto_ban_on_claim_rate_events;
#[path = "banlist_ac06_expiry_lifts_ban_without_restart.rs"]
mod banlist_ac06_expiry_lifts_ban_without_restart;
#[path = "banlist_ac07_ban_remove_audited_with_operator_identity.rs"]
mod banlist_ac07_ban_remove_audited_with_operator_identity;
#[path = "banlist_ac08_list_active_only_excludes_expired.rs"]
mod banlist_ac08_list_active_only_excludes_expired;
#[path = "banlist_ac09_permanent_requires_literal_true.rs"]
mod banlist_ac09_permanent_requires_literal_true;
#[path = "banlist_ac10_cache_lookup_latency_at_scale.rs"]
mod banlist_ac10_cache_lookup_latency_at_scale;
#[path = "banlist_ac11_healthz_bans_block.rs"]
mod banlist_ac11_healthz_bans_block;
#[path = "banlist_ac12_live_ban_unban_trailer.rs"]
mod banlist_ac12_live_ban_unban_trailer;
#[path = "billing_ac01_plans_toml_and_billing_plans.rs"]
mod billing_ac01_plans_toml_and_billing_plans;
#[path = "billing_ac02_publish_quota_exceeded.rs"]
mod billing_ac02_publish_quota_exceeded;
#[path = "billing_ac03_call_time_quota_exceeded.rs"]
mod billing_ac03_call_time_quota_exceeded;
#[path = "billing_ac04_checkout_unavailable_no_keys.rs"]
mod billing_ac04_checkout_unavailable_no_keys;
#[path = "billing_ac05_checkout_returns_session.rs"]
mod billing_ac05_checkout_returns_session;
#[path = "billing_ac06_webhook_checkout_completed_idempotent.rs"]
mod billing_ac06_webhook_checkout_completed_idempotent;
#[path = "billing_ac07_webhook_bad_signature_or_stale.rs"]
mod billing_ac07_webhook_bad_signature_or_stale;
#[path = "billing_ac08_webhook_subscription_deleted_downgrades.rs"]
mod billing_ac08_webhook_subscription_deleted_downgrades;
#[path = "billing_ac09_admin_billing_ledger_filters.rs"]
mod billing_ac09_admin_billing_ledger_filters;
#[path = "billing_ac10_webhook_mode_mismatch.rs"]
mod billing_ac10_webhook_mode_mismatch;
#[path = "billing_ac11_healthz_paying_tenants.rs"]
mod billing_ac11_healthz_paying_tenants;
#[path = "billing_ac13_checkout_reuse.rs"]
mod billing_ac13_checkout_reuse;
#[path = "busyaudit_ac01_startup_pragma_audit_default_config.rs"]
mod busyaudit_ac01_startup_pragma_audit_default_config;
#[path = "busyaudit_ac02_env_override_busy_timeout.rs"]
mod busyaudit_ac02_env_override_busy_timeout;
#[path = "busyaudit_ac03_bypass_connection_named_file_and_line.rs"]
mod busyaudit_ac03_bypass_connection_named_file_and_line;
#[path = "busyaudit_ac04_wait_over_100ms_counted_no_error.rs"]
mod busyaudit_ac04_wait_over_100ms_counted_no_error;
#[path = "busyaudit_ac05_busy_total_increments_exactly_one.rs"]
mod busyaudit_ac05_busy_total_increments_exactly_one;
#[path = "busyaudit_ac06_64_tenants_50_cycles_no_contention.rs"]
mod busyaudit_ac06_64_tenants_50_cycles_no_contention;
#[path = "busyaudit_ac07_admin_db_stats.rs"]
mod busyaudit_ac07_admin_db_stats;
#[path = "busyaudit_ac08_healthz_db_fields.rs"]
mod busyaudit_ac08_healthz_db_fields;
#[path = "busyaudit_ac09_contention_alert.rs"]
mod busyaudit_ac09_contention_alert;
#[path = "busyaudit_ac10_wal_checkpoint_cron.rs"]
mod busyaudit_ac10_wal_checkpoint_cron;
#[path = "callerusage_ac01_caller_breakdown.rs"]
mod callerusage_ac01_caller_breakdown;
#[path = "callerusage_ac02_end_user_breakdown.rs"]
mod callerusage_ac02_end_user_breakdown;
#[path = "callerusage_ac03_caller_limit_enforced.rs"]
mod callerusage_ac03_caller_limit_enforced;
#[path = "callerusage_ac04_caller_requires_shared_tool.rs"]
mod callerusage_ac04_caller_requires_shared_tool;
#[path = "callerusage_ac05_end_user_pagination.rs"]
mod callerusage_ac05_end_user_pagination;
#[path = "callerusage_ac06_no_by_shape_unchanged.rs"]
mod callerusage_ac06_no_by_shape_unchanged;
#[path = "callerusage_ac07_rollup_speed_at_scale.rs"]
mod callerusage_ac07_rollup_speed_at_scale;
#[path = "callerusage_ac08_end_user_key_includes_caller.rs"]
mod callerusage_ac08_end_user_key_includes_caller;
#[path = "callerusage_ac09_admin_usage_top_audited.rs"]
mod callerusage_ac09_admin_usage_top_audited;
#[path = "channel_ac01_group_open_and_broadcast_read.rs"]
mod channel_ac01_group_open_and_broadcast_read;
#[path = "channel_ac02_non_member_channel_not_found.rs"]
mod channel_ac02_non_member_channel_not_found;
#[path = "channel_ac03_ack_resumes_from_stored_cursor.rs"]
mod channel_ac03_ack_resumes_from_stored_cursor;
#[path = "channel_ac04_concurrent_posts_no_dups_no_gaps.rs"]
mod channel_ac04_concurrent_posts_no_dups_no_gaps;
#[path = "channel_ac05_removed_member_loses_access_posts_remain.rs"]
mod channel_ac05_removed_member_loses_access_posts_remain;
#[path = "channel_ac06_message_trigger_fires_per_member_not_poster.rs"]
mod channel_ac06_message_trigger_fires_per_member_not_poster;
#[path = "channel_ac07_post_quota_120_per_hour.rs"]
mod channel_ac07_post_quota_120_per_hour;
#[path = "channel_ac08_retention_tick_purges_old_posts.rs"]
mod channel_ac08_retention_tick_purges_old_posts;
#[path = "channel_ac09_close_blocks_posts_not_reads.rs"]
mod channel_ac09_close_blocks_posts_not_reads;
#[path = "channel_ac10_freeze_blocks_posts_unfreeze_restores.rs"]
mod channel_ac10_freeze_blocks_posts_unfreeze_restores;
#[path = "chart_ac01_vendor_crates_documented_and_wired.rs"]
mod chart_ac01_vendor_crates_documented_and_wired;
#[path = "chart_ac02_category_sum_profiles_bar.rs"]
mod chart_ac02_category_sum_profiles_bar;
#[path = "chart_ac03_caption_recomputes_facts_from_rows.rs"]
mod chart_ac03_caption_recomputes_facts_from_rows;
#[path = "chart_ac04_temporal_day_column_picks_line_or_bar.rs"]
mod chart_ac04_temporal_day_column_picks_line_or_bar;
#[path = "chart_ac05_empty_result_is_table_with_no_takeaway.rs"]
mod chart_ac05_empty_result_is_table_with_no_takeaway;
#[path = "chart_ac06_count_star_is_bignumber.rs"]
mod chart_ac06_count_star_is_bignumber;
#[path = "chart_ac07_disallowed_mark_override_is_rejected.rs"]
mod chart_ac07_disallowed_mark_override_is_rejected;
#[path = "chart_ac08_share_link_opens_unauthenticated.rs"]
mod chart_ac08_share_link_opens_unauthenticated;
#[path = "chart_ac09_expired_or_altered_signature_refused.rs"]
mod chart_ac09_expired_or_altered_signature_refused;
#[path = "chart_ac10_101st_share_evicts_oldest.rs"]
mod chart_ac10_101st_share_evicts_oldest;
#[path = "chart_ac13_llms_txt_section_under_50_lines.rs"]
mod chart_ac13_llms_txt_section_under_50_lines;
#[path = "chart_ac14_ten_concurrent_calls_p95_under_250ms.rs"]
mod chart_ac14_ten_concurrent_calls_p95_under_250ms;
#[path = "checkcompat_ac02_ac03.rs"]
mod checkcompat_ac02_ac03;
#[path = "checkcompat_race_ac01_previous_up_within_1s.rs"]
mod checkcompat_race_ac01_previous_up_within_1s;
#[path = "checkcompat_race_ac03_inherited_listener_token_matches.rs"]
mod checkcompat_race_ac03_inherited_listener_token_matches;
#[path = "checkcompat_race_ac04_no_token_header_when_unset.rs"]
mod checkcompat_race_ac04_no_token_header_when_unset;
#[path = "checkcompat_race_ac05_stress_no_port_collisions.rs"]
mod checkcompat_race_ac05_stress_no_port_collisions;
#[path = "checkcompat_race_ac06_explicit_bind_still_enforces_token.rs"]
mod checkcompat_race_ac06_explicit_bind_still_enforces_token;
#[path = "checkcompat_race_ac07_suite_green_and_clippy_clean.rs"]
mod checkcompat_race_ac07_suite_green_and_clippy_clean;
#[path = "checkcompat_race_ac08_deferral_is_justified.rs"]
mod checkcompat_race_ac08_deferral_is_justified;
#[path = "ci_sandbox_ac01_workflow_executes_sandbox_suites.rs"]
mod ci_sandbox_ac01_workflow_executes_sandbox_suites;
#[path = "ci_sandbox_ac03_incapable_in_ci_skips_and_fails_job.rs"]
mod ci_sandbox_ac03_incapable_in_ci_skips_and_fails_job;
#[path = "ci_sandbox_ac04_incapable_outside_ci_fails_loudly.rs"]
mod ci_sandbox_ac04_incapable_outside_ci_fails_loudly;
#[path = "ci_sandbox_ac06_sandbox_suites_run_as_a_parallel_job.rs"]
mod ci_sandbox_ac06_sandbox_suites_run_as_a_parallel_job;
#[path = "classify_ac9_is_within_proptest.rs"]
mod classify_ac9_is_within_proptest;
#[path = "compat_ac01_ac02_ac03_cache_fields.rs"]
mod compat_ac01_ac02_ac03_cache_fields;
#[path = "compat_ac04_ac05_admin_and_tenant_cache_fields.rs"]
mod compat_ac04_ac05_admin_and_tenant_cache_fields;
#[path = "compat_ac08_ac09_ac10_advertised_version.rs"]
mod compat_ac08_ac09_ac10_advertised_version;
#[path = "compat_ac11_ac12_claude_sdk_replay.rs"]
mod compat_ac11_ac12_claude_sdk_replay;
#[path = "compose_ac3_self_call_refused.rs"]
mod compose_ac3_self_call_refused;
#[path = "compose_ac4_depth_exceeded.rs"]
mod compose_ac4_depth_exceeded;
#[path = "compose_ac5_three_step_chain_prev_mapping.rs"]
mod compose_ac5_three_step_chain_prev_mapping;
#[path = "compose_ac6_mapping_missing.rs"]
mod compose_ac6_mapping_missing;
#[path = "compose_ac7_on_error_continue.rs"]
mod compose_ac7_on_error_continue;
#[path = "compose_ac8_tool_test_dry_run.rs"]
mod compose_ac8_tool_test_dry_run;
#[path = "consent_ac01_ac02_ac03_ac04_contact_lifecycle.rs"]
mod consent_ac01_ac02_ac03_ac04_contact_lifecycle;
#[path = "consent_ac05_ac06_ac07_ac08_ac09_ac10_mute_urgent_block_delete_inbox.rs"]
mod consent_ac05_ac06_ac07_ac08_ac09_ac10_mute_urgent_block_delete_inbox;
#[path = "docsearch_ac01_status_reports_watermark_lag_and_chunks.rs"]
mod docsearch_ac01_status_reports_watermark_lag_and_chunks;
#[path = "docsearch_ac02_lexical_search_returns_passage_and_offset.rs"]
mod docsearch_ac02_lexical_search_returns_passage_and_offset;
#[path = "docsearch_ac03_version_update_drops_old_chunks.rs"]
mod docsearch_ac03_version_update_drops_old_chunks;
#[path = "docsearch_ac04_delete_removes_chunks.rs"]
mod docsearch_ac04_delete_removes_chunks;
#[path = "docsearch_ac05_embeddings_mode_ranks_by_cosine.rs"]
mod docsearch_ac05_embeddings_mode_ranks_by_cosine;
#[path = "docsearch_ac06_provider_503_falls_back_to_lexical.rs"]
mod docsearch_ac06_provider_503_falls_back_to_lexical;
#[path = "docsearch_ac07_chunk_quota_stops_indexer.rs"]
mod docsearch_ac07_chunk_quota_stops_indexer;
#[path = "docsearch_ac08_cross_tenant_isolation.rs"]
mod docsearch_ac08_cross_tenant_isolation;
#[path = "docsearch_ac09_fixture_corpus_hit_rate.rs"]
mod docsearch_ac09_fixture_corpus_hit_rate;
#[path = "docsearch_ac10_reindex_forces_all_documents.rs"]
mod docsearch_ac10_reindex_forces_all_documents;
#[path = "docsearch_ac11_lexical_search_p95_latency.rs"]
mod docsearch_ac11_lexical_search_p95_latency;
#[path = "docsqa_ac06_synthorg_task_matches_gold_question_3.rs"]
mod docsqa_ac06_synthorg_task_matches_gold_question_3;
#[path = "docsqa_ac10_deferral_is_justified.rs"]
mod docsqa_ac10_deferral_is_justified;
#[path = "docsqa_ac10_truth_tier_panel_satisfaction_recorded.rs"]
mod docsqa_ac10_truth_tier_panel_satisfaction_recorded;
#[path = "docstore_ac01_first_put_returns_version1_seq1.rs"]
mod docstore_ac01_first_put_returns_version1_seq1;
#[path = "docstore_ac02_put_bumps_version_noop_on_identical_content.rs"]
mod docstore_ac02_put_bumps_version_noop_on_identical_content;
#[path = "docstore_ac03_size_cap_rejects_over_2mib_accepts_exactly.rs"]
mod docstore_ac03_size_cap_rejects_over_2mib_accepts_exactly;
#[path = "docstore_ac04_extraction_json_and_csv.rs"]
mod docstore_ac04_extraction_json_and_csv;
#[path = "docstore_ac05_list_since_includes_deleted.rs"]
mod docstore_ac05_list_since_includes_deleted;
#[path = "docstore_ac06_quota_docs_and_docs_bytes.rs"]
mod docstore_ac06_quota_docs_and_docs_bytes;
#[path = "docstore_ac07_put_bytes_metering_event.rs"]
mod docstore_ac07_put_bytes_metering_event;
#[path = "docstore_ac08_unsupported_mime_by_content_sniff.rs"]
mod docstore_ac08_unsupported_mime_by_content_sniff;
#[path = "docstore_ac10_purge_older_than_versions.rs"]
mod docstore_ac10_purge_older_than_versions;
#[path = "docstore_ac11_export_includes_documents.rs"]
mod docstore_ac11_export_includes_documents;
#[path = "enduser_ac02_assertion_http_headers_and_calls_row.rs"]
mod enduser_ac02_assertion_http_headers_and_calls_row;
#[path = "enduser_ac03_invalid_assertion_rejected.rs"]
mod enduser_ac03_invalid_assertion_rejected;
#[path = "enduser_ac05_state_set_get_end_user_self_isolation.rs"]
mod enduser_ac05_state_set_get_end_user_self_isolation;
#[path = "enduser_ac06_state_query_end_user_self_scales_via_index.rs"]
mod enduser_ac06_state_query_end_user_self_scales_via_index;
#[path = "enduser_ac07_end_user_required_and_explicit_impersonation.rs"]
mod enduser_ac07_end_user_required_and_explicit_impersonation;
#[path = "enduser_ac08_explicit_subject_forbidden_with_own_identity.rs"]
mod enduser_ac08_explicit_subject_forbidden_with_own_identity;
#[path = "enduser_ac09_quota_end_users.rs"]
mod enduser_ac09_quota_end_users;
#[path = "enduser_ac10_whoami.rs"]
mod enduser_ac10_whoami;
#[path = "enduser_ac11_assertion_secret_rotate_invalidates_and_never_leaks.rs"]
mod enduser_ac11_assertion_secret_rotate_invalidates_and_never_leaks;
#[path = "enduserctl_ac01_list_flush_aggregates_calls.rs"]
mod enduserctl_ac01_list_flush_aggregates_calls;
#[path = "enduserctl_ac02_get_row_plus_counts.rs"]
mod enduserctl_ac02_get_row_plus_counts;
#[path = "enduserctl_ac03_audit_calls_newest_first_paged.rs"]
mod enduserctl_ac03_audit_calls_newest_first_paged;
#[path = "enduserctl_ac04_revoke_refuses_next_call_and_disconnects_vault.rs"]
mod enduserctl_ac04_revoke_refuses_next_call_and_disconnects_vault;
#[path = "enduserctl_ac05_purge_deletes_scoped_rows_and_deidentifies_calls.rs"]
mod enduserctl_ac05_purge_deletes_scoped_rows_and_deidentifies_calls;
#[path = "enduserctl_ac06_purge_without_revoke_rejected.rs"]
mod enduserctl_ac06_purge_without_revoke_rejected;
#[path = "enduserctl_ac07_unrevoke_restores_calls_audit_shows_both.rs"]
mod enduserctl_ac07_unrevoke_restores_calls_audit_shows_both;
#[path = "enduserctl_ac08_export_bundle_scoped_to_one_subject.rs"]
mod enduserctl_ac08_export_bundle_scoped_to_one_subject;
#[path = "enduserctl_ac09_admin_stats_per_tenant_and_audited.rs"]
mod enduserctl_ac09_admin_stats_per_tenant_and_audited;
#[path = "enduserctl_ac10_list_100k_pages_under_50ms_stable_cursor.rs"]
mod enduserctl_ac10_list_100k_pages_under_50ms_stable_cursor;
#[path = "envelope_ac1_http_declared_output_promoted.rs"]
mod envelope_ac1_http_declared_output_promoted;
#[path = "envelope_ac4_tool_test_reports_missing_declared_output.rs"]
mod envelope_ac4_tool_test_reports_missing_declared_output;
#[path = "federation_ac11_tenant_prm_lists_hosted_as.rs"]
mod federation_ac11_tenant_prm_lists_hosted_as;
#[path = "fedlogin_ac01_provider_set_discovery_no_secret.rs"]
mod fedlogin_ac01_provider_set_discovery_no_secret;
#[path = "fedlogin_ac02_authorize_redirects_consent_mints_code.rs"]
mod fedlogin_ac02_authorize_redirects_consent_mints_code;
#[path = "fedlogin_ac04_callback_error_paths.rs"]
mod fedlogin_ac04_callback_error_paths;
#[path = "fedlogin_ac05_email_verified_gate.rs"]
mod fedlogin_ac05_email_verified_gate;
#[path = "fedlogin_ac06_revoke_and_provider_remove.rs"]
mod fedlogin_ac06_revoke_and_provider_remove;
#[path = "fedlogin_ac07_key_form_present_or_absent.rs"]
mod fedlogin_ac07_key_form_present_or_absent;
#[path = "fedlogin_ac08_doctor_discovery_down.rs"]
mod fedlogin_ac08_doctor_discovery_down;
#[path = "fedlogin_ac09_docs_and_llms_txt.rs"]
mod fedlogin_ac09_docs_and_llms_txt;
#[path = "fedlogin_ac10_hosted_as_and_key_flows_unchanged.rs"]
mod fedlogin_ac10_hosted_as_and_key_flows_unchanged;
#[path = "firstcall_ac6_outcome_metering.rs"]
mod firstcall_ac6_outcome_metering;
#[path = "firstpub_ac09_dry_run_spec_size_short_circuits.rs"]
mod firstpub_ac09_dry_run_spec_size_short_circuits;
#[path = "firstpub_ac10_live_proof_against_real_mcphost.rs"]
mod firstpub_ac10_live_proof_against_real_mcphost;
#[path = "fleetips_reclassify_backfill.rs"]
mod fleetips_reclassify_backfill;
#[path = "gatedebt_4f1112d_ac4_no_test_reads_gate_receipts.rs"]
mod gatedebt_4f1112d_ac4_no_test_reads_gate_receipts;
#[path = "gatedebt_4f1112d_ac5_no_flake_audit_selftest_names.rs"]
mod gatedebt_4f1112d_ac5_no_flake_audit_selftest_names;
#[path = "handoff_ac01_signup_returns_token_and_no_key.rs"]
mod handoff_ac01_signup_returns_token_and_no_key;
#[path = "handoff_ac02_redeem_single_use_and_expiry.rs"]
mod handoff_ac02_redeem_single_use_and_expiry;
#[path = "handoff_ac03_key_rotate_invalidates_old_key.rs"]
mod handoff_ac03_key_rotate_invalidates_old_key;
#[path = "handoff_ac04_full_two_context_flow.rs"]
mod handoff_ac04_full_two_context_flow;
#[path = "handoff_ac05_raw_signup_still_works_unchanged.rs"]
mod handoff_ac05_raw_signup_still_works_unchanged;
#[path = "handoff_ac06_errors_never_echo_token_or_key.rs"]
mod handoff_ac06_errors_never_echo_token_or_key;
#[path = "handoff_ac07_docs_recommend_handoff_flow.rs"]
mod handoff_ac07_docs_recommend_handoff_flow;
#[path = "handoff_ac08_whoami_reports_key_age_and_rotation.rs"]
mod handoff_ac08_whoami_reports_key_age_and_rotation;
#[path = "hooks_ac10_healthz_event_counters.rs"]
mod hooks_ac10_healthz_event_counters;
#[path = "hooks_ac11_dedupe_header_idempotent.rs"]
mod hooks_ac11_dedupe_header_idempotent;
#[path = "hooks_ac1_hmac_sha256_valid_signature_runs.rs"]
mod hooks_ac1_hmac_sha256_valid_signature_runs;
#[path = "hooks_ac2_wrong_signature_401_no_run.rs"]
mod hooks_ac2_wrong_signature_401_no_run;
#[path = "hooks_ac3_stripe_style_stale_timestamp_401.rs"]
mod hooks_ac3_stripe_style_stale_timestamp_401;
#[path = "hooks_ac4_none_scheme_requires_allow_unverified.rs"]
mod hooks_ac4_none_scheme_requires_allow_unverified;
#[path = "hooks_ac5_rate_limit_429.rs"]
mod hooks_ac5_rate_limit_429;
#[path = "hooks_ac6_body_too_large_413.rs"]
mod hooks_ac6_body_too_large_413;
#[path = "hooks_ac7_trigger_test_creates_marked_run.rs"]
mod hooks_ac7_trigger_test_creates_marked_run;
#[path = "hooks_ac8_trigger_replay_new_run_trigger_ref.rs"]
mod hooks_ac8_trigger_replay_new_run_trigger_ref;
#[path = "hooks_ac9_paused_trigger_404.rs"]
mod hooks_ac9_paused_trigger_404;
#[path = "hostedas_ac01_well_known_metadata.rs"]
mod hostedas_ac01_well_known_metadata;
#[path = "hostedas_ac02_cimd_client_identification.rs"]
mod hostedas_ac02_cimd_client_identification;
#[path = "hostedas_ac03_dcr_register_and_rate_limit.rs"]
mod hostedas_ac03_dcr_register_and_rate_limit;
#[path = "hostedas_ac04_consent_code_token_hosted_bearer.rs"]
mod hostedas_ac04_consent_code_token_hosted_bearer;
#[path = "hostedas_ac05_code_replay_revokes_issued_tokens.rs"]
mod hostedas_ac05_code_replay_revokes_issued_tokens;
#[path = "hostedas_ac06_authorize_hardening.rs"]
mod hostedas_ac06_authorize_hardening;
#[path = "hostedas_ac07_cross_client_code_and_refresh_reuse.rs"]
mod hostedas_ac07_cross_client_code_and_refresh_reuse;
#[path = "hostedas_ac08_grants_list_revoke_and_oauth_revoke.rs"]
mod hostedas_ac08_grants_list_revoke_and_oauth_revoke;
#[path = "hostedas_ac09_no_secret_leakage.rs"]
mod hostedas_ac09_no_secret_leakage;
#[path = "hostedas_ac10_key_and_issuer_jwt_flows_unchanged.rs"]
mod hostedas_ac10_key_and_issuer_jwt_flows_unchanged;
#[path = "hostedas_ac11_docs_and_llms_txt.rs"]
mod hostedas_ac11_docs_and_llms_txt;
#[path = "hostedas_offline_access_scope.rs"]
mod hostedas_offline_access_scope;
#[path = "http_ac01_secret_redaction.rs"]
mod http_ac01_secret_redaction;
#[path = "http_ac02_publish_ssrf_literal.rs"]
mod http_ac02_publish_ssrf_literal;
#[path = "http_ac03_publish_secret_missing.rs"]
mod http_ac03_publish_secret_missing;
#[path = "http_ac04_args_invalid.rs"]
mod http_ac04_args_invalid;
#[path = "http_ac05_upstream_429_retry_after.rs"]
mod http_ac05_upstream_429_retry_after;
#[path = "http_ac06_upstream_timeout.rs"]
mod http_ac06_upstream_timeout;
#[path = "http_ac07_response_too_large.rs"]
mod http_ac07_response_too_large;
#[path = "http_ac08_template_error.rs"]
mod http_ac08_template_error;
#[path = "http_ac09_dns_rebinding.rs"]
mod http_ac09_dns_rebinding;
#[path = "http_ac10_concurrency_overhead.rs"]
mod http_ac10_concurrency_overhead;
#[path = "http_ac11_redirect_not_followed.rs"]
mod http_ac11_redirect_not_followed;
#[path = "http_ac12_tool_test.rs"]
mod http_ac12_tool_test;
#[path = "http_ac13_rate_limit.rs"]
mod http_ac13_rate_limit;
#[path = "http_ac14_bridge_envelope_payload.rs"]
mod http_ac14_bridge_envelope_payload;
#[path = "http_ac15_upstream_bridge_declarative.rs"]
mod http_ac15_upstream_bridge_declarative;
#[path = "http_ac16_upstream_bridge_errors.rs"]
mod http_ac16_upstream_bridge_errors;
#[path = "http_ac17_upstream_egress_policy.rs"]
mod http_ac17_upstream_egress_policy;
#[path = "http_ac18_bridge_test_dry_run.rs"]
mod http_ac18_bridge_test_dry_run;
#[path = "hybrid_ac01_identifier_chunk_wins_via_lexical_rank.rs"]
mod hybrid_ac01_identifier_chunk_wins_via_lexical_rank;
#[path = "hybrid_ac02_rrf_fuse_ties_and_normalization.rs"]
mod hybrid_ac02_rrf_fuse_ties_and_normalization;
#[path = "hybrid_ac03_lexical_mode_never_calls_provider.rs"]
mod hybrid_ac03_lexical_mode_never_calls_provider;
#[path = "hybrid_ac04_hybrid_without_provider_is_validation_error.rs"]
mod hybrid_ac04_hybrid_without_provider_is_validation_error;
#[path = "hybrid_ac05_default_mode_provider_failure_falls_back.rs"]
mod hybrid_ac05_default_mode_provider_failure_falls_back;
#[path = "hybrid_ac06_hybrid_mode_cross_tenant_isolation.rs"]
mod hybrid_ac06_hybrid_mode_cross_tenant_isolation;
#[path = "hybrid_ac07_p95_latency_within_30ms_of_embeddings_only.rs"]
mod hybrid_ac07_p95_latency_within_30ms_of_embeddings_only;
#[path = "hybrid_ac08_hybrid_hit_rate_at_least_each_mode.rs"]
mod hybrid_ac08_hybrid_hit_rate_at_least_each_mode;
#[path = "hybrid_ac10_filter_prefix_filters_before_fusion.rs"]
mod hybrid_ac10_filter_prefix_filters_before_fusion;
#[path = "infer_ac05_ac06_ac07_http_schema.rs"]
mod infer_ac05_ac06_ac07_http_schema;
#[path = "infer_ac14_latency_budget.rs"]
mod infer_ac14_latency_budget;
#[path = "infer_ac17_no_execution.rs"]
mod infer_ac17_no_execution;
#[path = "kindhonor_ac1_http_kind_honored.rs"]
mod kindhonor_ac1_http_kind_honored;
#[path = "kindhonor_ac3_spec_test_reports_kind.rs"]
mod kindhonor_ac3_spec_test_reports_kind;
#[path = "kindhonor_ac4_initialize_instructions_mention_kind.rs"]
mod kindhonor_ac4_initialize_instructions_mention_kind;
#[path = "kindhonor_ac5_replay_cost_optimizer_shape.rs"]
mod kindhonor_ac5_replay_cost_optimizer_shape;
#[path = "kindhonor_ac6_tools_list_meta_kind.rs"]
mod kindhonor_ac6_tools_list_meta_kind;
#[path = "kindroute_ac01_webhook_alias_returns_http_recipe.rs"]
mod kindroute_ac01_webhook_alias_returns_http_recipe;
#[path = "kindroute_ac02_case_insensitive_alias.rs"]
mod kindroute_ac02_case_insensitive_alias;
#[path = "kindroute_ac03_tool_publish_event_alias_resolves_to_http.rs"]
mod kindroute_ac03_tool_publish_event_alias_resolves_to_http;
#[path = "kindroute_ac06_contract_and_llms_txt_document_aliases.rs"]
mod kindroute_ac06_contract_and_llms_txt_document_aliases;
#[path = "kindroute_ac07_quickstart_no_kind_lists_kinds_aliases_recipes.rs"]
mod kindroute_ac07_quickstart_no_kind_lists_kinds_aliases_recipes;
#[path = "kindroute_ac08_full_suite_green_at_landing.rs"]
mod kindroute_ac08_full_suite_green_at_landing;
#[path = "lanecov_ac01_every_tracked_path_routes.rs"]
mod lanecov_ac01_every_tracked_path_routes;
#[path = "lanecov_ac02_coverage_test_is_actually_run.rs"]
mod lanecov_ac02_coverage_test_is_actually_run;
#[path = "lanecov_ac03_unrouted_path_is_named.rs"]
mod lanecov_ac03_unrouted_path_is_named;
#[path = "lanecov_ac04_existing_lanes_unchanged.rs"]
mod lanecov_ac04_existing_lanes_unchanged;
#[path = "lanecov_ac06_malformed_lane_fails_naming_it.rs"]
mod lanecov_ac06_malformed_lane_fails_naming_it;
#[path = "lanecov_ac07_docs_document_adding_a_lane.rs"]
mod lanecov_ac07_docs_document_adding_a_lane;
#[path = "limits_ac05_signup_burst_atomic.rs"]
mod limits_ac05_signup_burst_atomic;
#[path = "lineage_ac02_drop_with_no_consumers_is_unrefused.rs"]
mod lineage_ac02_drop_with_no_consumers_is_unrefused;
#[path = "lineage_ac03_blast_radius_ranks_chain_above_tool.rs"]
mod lineage_ac03_blast_radius_ranks_chain_above_tool;
#[path = "lineage_ac04_drop_gate_blocks_then_confirms_and_cascades.rs"]
mod lineage_ac04_drop_gate_blocks_then_confirms_and_cascades;
#[path = "lineage_ac05_effect_table_is_exhaustive.rs"]
mod lineage_ac05_effect_table_is_exhaustive;
#[path = "lineage_ac06_trace_shows_chart_and_handle_downstream.rs"]
mod lineage_ac06_trace_shows_chart_and_handle_downstream;
#[path = "lineage_ac07_trace_pages_150_downstream_consumers.rs"]
mod lineage_ac07_trace_pages_150_downstream_consumers;
#[path = "lineage_ac08_blast_radius_is_tenant_scoped.rs"]
mod lineage_ac08_blast_radius_is_tenant_scoped;
#[path = "lineage_ac09_model_set_role_change_notes_chart.rs"]
mod lineage_ac09_model_set_role_change_notes_chart;
#[path = "lineage_ac10_blast_radius_1000_nodes_3000_edges_under_50ms.rs"]
mod lineage_ac10_blast_radius_1000_nodes_3000_edges_under_50ms;
#[path = "lineage_ac11_chart_store_registers_edge_and_gates_drop.rs"]
mod lineage_ac11_chart_store_registers_edge_and_gates_drop;
#[path = "mcphost_admin_schema_contract_ac01_tenants_schema_version.rs"]
mod mcphost_admin_schema_contract_ac01_tenants_schema_version;
#[path = "mcphost_admin_schema_contract_ac02_listings_validate_v1_schema.rs"]
mod mcphost_admin_schema_contract_ac02_listings_validate_v1_schema;
#[path = "mcphost_admin_schema_contract_ac03_unknown_field_fails_naming_it.rs"]
mod mcphost_admin_schema_contract_ac03_unknown_field_fails_naming_it;
#[path = "mcphost_admin_schema_contract_ac04_unsupported_version_refused.rs"]
mod mcphost_admin_schema_contract_ac04_unsupported_version_refused;
#[path = "mcphost_admin_schema_contract_ac05_doctor_live_schema_version.rs"]
mod mcphost_admin_schema_contract_ac05_doctor_live_schema_version;
#[path = "mcphost_admin_schema_contract_ac06_admin_rs_fields_match_schema.rs"]
mod mcphost_admin_schema_contract_ac06_admin_rs_fields_match_schema;
#[path = "mcphost_admin_schema_contract_ac07_whoami_admin_schema_version.rs"]
mod mcphost_admin_schema_contract_ac07_whoami_admin_schema_version;
#[path = "mcphost_claude_code_plugin_and_snippets_ac01_plugin_assets_script.rs"]
mod mcphost_claude_code_plugin_and_snippets_ac01_plugin_assets_script;
#[path = "mcphost_claude_code_plugin_and_snippets_ac02_plugin_json_and_mcp_json_version.rs"]
mod mcphost_claude_code_plugin_and_snippets_ac02_plugin_json_and_mcp_json_version;
#[path = "mcphost_claude_code_plugin_and_snippets_ac03_readme_connect_section.rs"]
mod mcphost_claude_code_plugin_and_snippets_ac03_readme_connect_section;
#[path = "mcphost_claude_code_plugin_and_snippets_ac04_index_html_snippets.rs"]
mod mcphost_claude_code_plugin_and_snippets_ac04_index_html_snippets;
#[path = "mcphost_claude_code_plugin_and_snippets_ac05_skill_md_walkthrough.rs"]
mod mcphost_claude_code_plugin_and_snippets_ac05_skill_md_walkthrough;
#[path = "mcphost_claude_code_plugin_and_snippets_ac06_llms_txt_first_run_walkthrough.rs"]
mod mcphost_claude_code_plugin_and_snippets_ac06_llms_txt_first_run_walkthrough;
#[path = "mcphost_claude_code_plugin_and_snippets_ac07_no_leaked_bearer_key.rs"]
mod mcphost_claude_code_plugin_and_snippets_ac07_no_leaked_bearer_key;
#[path = "mcphost_claude_code_plugin_and_snippets_ac08_claude_plugin_validate.rs"]
mod mcphost_claude_code_plugin_and_snippets_ac08_claude_plugin_validate;
#[path = "mcphost_claude_code_plugin_and_snippets_ac09_readme_connect_links_status_and_aup.rs"]
mod mcphost_claude_code_plugin_and_snippets_ac09_readme_connect_links_status_and_aup;
#[path = "mcphost_data_retention_ac01_calls_prune_by_window.rs"]
mod mcphost_data_retention_ac01_calls_prune_by_window;
#[path = "mcphost_data_retention_ac02_metering_rows_survive_window.rs"]
mod mcphost_data_retention_ac02_metering_rows_survive_window;
#[path = "mcphost_data_retention_ac03_untracked_table_unchanged.rs"]
mod mcphost_data_retention_ac03_untracked_table_unchanged;
#[path = "mcphost_data_retention_ac04_batched_prune_no_lock_errors.rs"]
mod mcphost_data_retention_ac04_batched_prune_no_lock_errors;
#[path = "mcphost_data_retention_ac05_admin_usage_reports_size_and_last_prune.rs"]
mod mcphost_data_retention_ac05_admin_usage_reports_size_and_last_prune;
#[path = "mcphost_data_retention_ac06_disk_floor_refuses_writes.rs"]
mod mcphost_data_retention_ac06_disk_floor_refuses_writes;
#[path = "mcphost_data_retention_ac07_automatic_prune_keeps_last_prune_fresh.rs"]
mod mcphost_data_retention_ac07_automatic_prune_keeps_last_prune_fresh;
#[path = "mcphost_data_retention_ac08_host_usage_lists_retention_windows.rs"]
mod mcphost_data_retention_ac08_host_usage_lists_retention_windows;
#[path = "mcphost_data_retention_ac09_prune_error_sets_last_prune_ok_false.rs"]
mod mcphost_data_retention_ac09_prune_error_sets_last_prune_ok_false;
#[path = "mcphost_data_retention_ac10_admin_prune_now_runs_one_cycle.rs"]
mod mcphost_data_retention_ac10_admin_prune_now_runs_one_cycle;
#[path = "mcphost_database_in_a_minute_ac01_llms_txt_section.rs"]
mod mcphost_database_in_a_minute_ac01_llms_txt_section;
#[path = "mcphost_database_in_a_minute_ac08_live_test_skipped_without_env.rs"]
mod mcphost_database_in_a_minute_ac08_live_test_skipped_without_env;
#[path = "mcphost_host_tool_deprecation_ac01_contract_dump_deterministic.rs"]
mod mcphost_host_tool_deprecation_ac01_contract_dump_deterministic;
#[path = "mcphost_host_tool_deprecation_ac02_removed_field_without_deprecation_fails.rs"]
mod mcphost_host_tool_deprecation_ac02_removed_field_without_deprecation_fails;
#[path = "mcphost_host_tool_deprecation_ac03_deprecation_entry_marks_tools_list.rs"]
mod mcphost_host_tool_deprecation_ac03_deprecation_entry_marks_tools_list;
#[path = "mcphost_host_tool_deprecation_ac04_deprecated_field_call_envelope.rs"]
mod mcphost_host_tool_deprecation_ac04_deprecated_field_call_envelope;
#[path = "mcphost_host_tool_deprecation_ac05_removal_gated_on_sunset.rs"]
mod mcphost_host_tool_deprecation_ac05_removal_gated_on_sunset;
#[path = "mcphost_host_tool_deprecation_ac06_changelog_lists_additions.rs"]
mod mcphost_host_tool_deprecation_ac06_changelog_lists_additions;
#[path = "mcphost_host_tool_deprecation_ac07_whoami_contract_version.rs"]
mod mcphost_host_tool_deprecation_ac07_whoami_contract_version;
#[path = "mcphost_host_tool_deprecation_ac08_llms_txt_links_contract.rs"]
mod mcphost_host_tool_deprecation_ac08_llms_txt_links_contract;
#[path = "mcphost_human_claim_magic_link_ac01_claim_url_in_signup.rs"]
mod mcphost_human_claim_magic_link_ac01_claim_url_in_signup;
#[path = "mcphost_human_claim_magic_link_ac02_post_claim_sends_magic_link.rs"]
mod mcphost_human_claim_magic_link_ac02_post_claim_sends_magic_link;
#[path = "mcphost_human_claim_magic_link_ac03_verify_sets_owner_and_shows_summary.rs"]
mod mcphost_human_claim_magic_link_ac03_verify_sets_owner_and_shows_summary;
#[path = "mcphost_human_claim_magic_link_ac04_expired_claim_token_410.rs"]
mod mcphost_human_claim_magic_link_ac04_expired_claim_token_410;
#[path = "mcphost_human_claim_magic_link_ac05_malformed_email_400.rs"]
mod mcphost_human_claim_magic_link_ac05_malformed_email_400;
#[path = "mcphost_human_claim_magic_link_ac06_email_not_configured.rs"]
mod mcphost_human_claim_magic_link_ac06_email_not_configured;
#[path = "mcphost_human_claim_magic_link_ac07_racing_verify_single_winner.rs"]
mod mcphost_human_claim_magic_link_ac07_racing_verify_single_winner;
#[path = "mcphost_human_claim_magic_link_ac08_claim_rate_limit_per_ip.rs"]
mod mcphost_human_claim_magic_link_ac08_claim_rate_limit_per_ip;
#[path = "mcphost_human_claim_magic_link_ac09_healthz_and_admin_tenants_claimed.rs"]
mod mcphost_human_claim_magic_link_ac09_healthz_and_admin_tenants_claimed;
#[path = "mcphost_human_claim_magic_link_ac10_retry_recovers_from_one_failure.rs"]
mod mcphost_human_claim_magic_link_ac10_retry_recovers_from_one_failure;
#[path = "mcphost_human_claim_magic_link_ac11_whoami_owner_verified.rs"]
mod mcphost_human_claim_magic_link_ac11_whoami_owner_verified;
#[path = "mcphost_human_claim_magic_link_ac12_llms_txt_relay_sentence.rs"]
mod mcphost_human_claim_magic_link_ac12_llms_txt_relay_sentence;
#[path = "mcphost_human_claim_magic_link_ac13_bearer_key_never_in_claim_pages.rs"]
mod mcphost_human_claim_magic_link_ac13_bearer_key_never_in_claim_pages;
#[path = "mcphost_oauth_unverified_client_consent_warning_ac01_dcr_unverified_caution_renders.rs"]
mod mcphost_oauth_unverified_client_consent_warning_ac01_dcr_unverified_caution_renders;
#[path = "mcphost_oauth_unverified_client_consent_warning_ac02_cimd_no_unverified_caution.rs"]
mod mcphost_oauth_unverified_client_consent_warning_ac02_cimd_no_unverified_caution;
#[path = "mcphost_oauth_unverified_client_consent_warning_ac03_destination_host_shown.rs"]
mod mcphost_oauth_unverified_client_consent_warning_ac03_destination_host_shown;
#[path = "mcphost_oauth_unverified_client_consent_warning_ac04_dcr_name_escaped_self_asserted.rs"]
mod mcphost_oauth_unverified_client_consent_warning_ac04_dcr_name_escaped_self_asserted;
#[path = "mcphost_oauth_unverified_client_consent_warning_ac05_dcr_no_name_neutral_placeholder.rs"]
mod mcphost_oauth_unverified_client_consent_warning_ac05_dcr_no_name_neutral_placeholder;
#[path = "mcphost_oauth_unverified_client_consent_warning_ac06_operator_allowlist_suppresses_caution.rs"]
mod mcphost_oauth_unverified_client_consent_warning_ac06_operator_allowlist_suppresses_caution;
#[path = "mcphost_oauth_unverified_client_consent_warning_ac07_caution_links_to_explainer.rs"]
mod mcphost_oauth_unverified_client_consent_warning_ac07_caution_links_to_explainer;
#[path = "mcphost_oauth_unverified_client_consent_warning_ac08_consent_record_notes_unverified.rs"]
mod mcphost_oauth_unverified_client_consent_warning_ac08_consent_record_notes_unverified;
#[path = "mcphost_oauth_unverified_client_consent_warning_ac09_verified_flow_unchanged.rs"]
mod mcphost_oauth_unverified_client_consent_warning_ac09_verified_flow_unchanged;
#[path = "mcphost_sandbox_egress_allowlist_ac05_none_network_unshare_all.rs"]
mod mcphost_sandbox_egress_allowlist_ac05_none_network_unshare_all;
#[path = "mcphost_sandbox_egress_allowlist_ac09_readme_documents_proxy_and_deny_list.rs"]
mod mcphost_sandbox_egress_allowlist_ac09_readme_documents_proxy_and_deny_list;
#[path = "mcphost_share_a_tool_not_a_key_ac01_llms_txt_section.rs"]
mod mcphost_share_a_tool_not_a_key_ac01_llms_txt_section;
#[path = "mcphost_share_a_tool_not_a_key_ac02_caller_call_returns_upstream_response.rs"]
mod mcphost_share_a_tool_not_a_key_ac02_caller_call_returns_upstream_response;
#[path = "mcphost_share_a_tool_not_a_key_ac03_caller_never_sees_secret.rs"]
mod mcphost_share_a_tool_not_a_key_ac03_caller_never_sees_secret;
#[path = "mcphost_share_a_tool_not_a_key_ac04_group_remove_revokes_caller.rs"]
mod mcphost_share_a_tool_not_a_key_ac04_group_remove_revokes_caller;
#[path = "mcphost_share_a_tool_not_a_key_ac05_signup_events_source_tagged.rs"]
mod mcphost_share_a_tool_not_a_key_ac05_signup_events_source_tagged;
#[path = "mcphost_share_a_tool_not_a_key_ac07_synthorg_task_five_completions.rs"]
mod mcphost_share_a_tool_not_a_key_ac07_synthorg_task_five_completions;
#[path = "mcphost_share_a_tool_not_a_key_ac08_live_test_skipped_without_env.rs"]
mod mcphost_share_a_tool_not_a_key_ac08_live_test_skipped_without_env;
#[path = "mcphost_share_a_tool_not_a_key_ac09_public_variant_states_default_reason.rs"]
mod mcphost_share_a_tool_not_a_key_ac09_public_variant_states_default_reason;
#[path = "mcphost_shared_tool_spec_readback_ac07_docs_worked_example.rs"]
mod mcphost_shared_tool_spec_readback_ac07_docs_worked_example;
#[path = "mcphost_signup_kill_switch_and_source_ac01_source_echoed_and_stored.rs"]
mod mcphost_signup_kill_switch_and_source_ac01_source_echoed_and_stored;
#[path = "mcphost_signup_kill_switch_and_source_ac02_no_source_is_null.rs"]
mod mcphost_signup_kill_switch_and_source_ac02_no_source_is_null;
#[path = "mcphost_signup_kill_switch_and_source_ac03_invalid_source_rejected.rs"]
mod mcphost_signup_kill_switch_and_source_ac03_invalid_source_rejected;
#[path = "mcphost_signup_kill_switch_and_source_ac04_pause_file_stops_and_resumes_signups.rs"]
mod mcphost_signup_kill_switch_and_source_ac04_pause_file_stops_and_resumes_signups;
#[path = "mcphost_signup_kill_switch_and_source_ac05_pause_does_not_affect_authenticated_calls.rs"]
mod mcphost_signup_kill_switch_and_source_ac05_pause_does_not_affect_authenticated_calls;
#[path = "mcphost_signup_kill_switch_and_source_ac06_healthz_signups_by_source.rs"]
mod mcphost_signup_kill_switch_and_source_ac06_healthz_signups_by_source;
#[path = "mcphost_signup_kill_switch_and_source_ac07_healthz_reports_paused.rs"]
mod mcphost_signup_kill_switch_and_source_ac07_healthz_reports_paused;
#[path = "mcphost_signup_kill_switch_and_source_ac08_concurrent_burst_with_pause_toggle.rs"]
mod mcphost_signup_kill_switch_and_source_ac08_concurrent_burst_with_pause_toggle;
#[path = "mcphost_signup_kill_switch_and_source_ac09_llms_txt_documents_source.rs"]
mod mcphost_signup_kill_switch_and_source_ac09_llms_txt_documents_source;
#[path = "mcphost_signup_kill_switch_and_source_ac10_until_line_bounds_retry_after.rs"]
mod mcphost_signup_kill_switch_and_source_ac10_until_line_bounds_retry_after;
#[path = "mcphost_team_memory_ac01_llms_txt_section.rs"]
mod mcphost_team_memory_ac01_llms_txt_section;
#[path = "mcphost_team_memory_ac08_live_test_skipped_without_env.rs"]
mod mcphost_team_memory_ac08_live_test_skipped_without_env;
#[path = "mcphost_tenant_data_export_ac01_archive_contents.rs"]
mod mcphost_tenant_data_export_ac01_archive_contents;
#[path = "mcphost_tenant_data_export_ac02_signed_url_expiry.rs"]
mod mcphost_tenant_data_export_ac02_signed_url_expiry;
#[path = "mcphost_tenant_data_export_ac03_dedupe_in_progress.rs"]
mod mcphost_tenant_data_export_ac03_dedupe_in_progress;
#[path = "mcphost_tenant_data_export_ac04_live_export_trailer.rs"]
mod mcphost_tenant_data_export_ac04_live_export_trailer;
#[path = "mcphost_tenant_data_export_ac05_manifest_validates_publish_schema.rs"]
mod mcphost_tenant_data_export_ac05_manifest_validates_publish_schema;
#[path = "mcphost_tenant_data_export_ac06_tools_subset.rs"]
mod mcphost_tenant_data_export_ac06_tools_subset;
#[path = "mcphost_tenant_data_export_ac07_admin_usage_exports_today.rs"]
mod mcphost_tenant_data_export_ac07_admin_usage_exports_today;
#[path = "mcphost_tool_versions_ac01_publish_twice_lists_two_versions.rs"]
mod mcphost_tool_versions_ac01_publish_twice_lists_two_versions;
#[path = "mcphost_tool_versions_ac02_rollback_runs_old_source.rs"]
mod mcphost_tool_versions_ac02_rollback_runs_old_source;
#[path = "mcphost_tool_versions_ac03_free_plan_retains_five_versions.rs"]
mod mcphost_tool_versions_ac03_free_plan_retains_five_versions;
#[path = "mcphost_tool_versions_ac04_rollback_unknown_version_names_range.rs"]
mod mcphost_tool_versions_ac04_rollback_unknown_version_names_range;
#[path = "mcphost_tool_versions_ac05_pinned_caller_survives_republish.rs"]
mod mcphost_tool_versions_ac05_pinned_caller_survives_republish;
#[path = "mcphost_tool_versions_ac07_sharer_sees_version_changed_once.rs"]
mod mcphost_tool_versions_ac07_sharer_sees_version_changed_once;
#[path = "mcphost_tool_versions_ac08_remove_clears_all_versions.rs"]
mod mcphost_tool_versions_ac08_remove_clears_all_versions;
#[path = "mcphost_tool_versions_ac09_diff_returns_unified_diff.rs"]
mod mcphost_tool_versions_ac09_diff_returns_unified_diff;
#[path = "mcphost_uptime_probes_ac01_llms_txt_section.rs"]
mod mcphost_uptime_probes_ac01_llms_txt_section;
#[path = "mcphost_uptime_probes_ac08_live_test_skipped_without_env.rs"]
mod mcphost_uptime_probes_ac08_live_test_skipped_without_env;
#[path = "mcphost_webhook_inbox_ac01_set_returns_url_and_secret_get_omits_secret.rs"]
mod mcphost_webhook_inbox_ac01_set_returns_url_and_secret_get_omits_secret;
#[path = "mcphost_webhook_inbox_ac02_signed_post_stores_row_and_fires_run.rs"]
mod mcphost_webhook_inbox_ac02_signed_post_stores_row_and_fires_run;
#[path = "mcphost_webhook_inbox_ac03_unsigned_or_wrong_signature_401_no_row.rs"]
mod mcphost_webhook_inbox_ac03_unsigned_or_wrong_signature_401_no_row;
#[path = "mcphost_webhook_inbox_ac04_unknown_id_404_empty_body.rs"]
mod mcphost_webhook_inbox_ac04_unknown_id_404_empty_body;
#[path = "mcphost_webhook_inbox_ac05_oversized_body_413_no_row.rs"]
mod mcphost_webhook_inbox_ac05_oversized_body_413_no_row;
#[path = "mcphost_webhook_inbox_ac06_paused_stores_no_run_replay_fires_once.rs"]
mod mcphost_webhook_inbox_ac06_paused_stores_no_run_replay_fires_once;
#[path = "mcphost_webhook_inbox_ac07_repeated_delivery_id_dedupes_row.rs"]
mod mcphost_webhook_inbox_ac07_repeated_delivery_id_dedupes_row;
#[path = "mcphost_webhook_inbox_ac08_free_tenant_three_schedules_webhook_refused.rs"]
mod mcphost_webhook_inbox_ac08_free_tenant_three_schedules_webhook_refused;
#[path = "mcphost_webhook_inbox_ac09_concurrent_deliveries_all_land.rs"]
mod mcphost_webhook_inbox_ac09_concurrent_deliveries_all_land;
#[path = "mcphost_webhook_inbox_ac11_trigger_test_stores_and_fires_synthetic_delivery.rs"]
mod mcphost_webhook_inbox_ac11_trigger_test_stores_and_fires_synthetic_delivery;
#[path = "mcphost_webhook_inbox_ac12_stripe_verify_scheme_accepted.rs"]
mod mcphost_webhook_inbox_ac12_stripe_verify_scheme_accepted;
#[path = "meshops_ac01_stats_real_vs_synthetic_volume.rs"]
mod meshops_ac01_stats_real_vs_synthetic_volume;
#[path = "meshops_ac02_threads_no_bodies.rs"]
mod meshops_ac02_threads_no_bodies;
#[path = "meshops_ac03_thread_read_bodies_and_audit.rs"]
mod meshops_ac03_thread_read_bodies_and_audit;
#[path = "meshops_ac04_freeze_blocks_sends_not_reads_or_tools.rs"]
mod meshops_ac04_freeze_blocks_sends_not_reads_or_tools;
#[path = "meshops_ac05_unfreeze_restores_sending.rs"]
mod meshops_ac05_unfreeze_restores_sending;
#[path = "meshops_ac06_purge_dry_run_then_real.rs"]
mod meshops_ac06_purge_dry_run_then_real;
#[path = "meshops_ac07_tenant_delete_cascade_across_mesh_tables.rs"]
mod meshops_ac07_tenant_delete_cascade_across_mesh_tables;
#[path = "meshops_ac08_healthz_mesh_counters.rs"]
mod meshops_ac08_healthz_mesh_counters;
#[path = "meshops_ac09_stats_refusals_by_code_per_sender.rs"]
mod meshops_ac09_stats_refusals_by_code_per_sender;
#[path = "metering_ac01_stripe_customer_id_null_default.rs"]
mod metering_ac01_stripe_customer_id_null_default;
#[path = "metering_ac02_webhook_stores_stripe_customer_id.rs"]
mod metering_ac02_webhook_stores_stripe_customer_id;
#[path = "metering_ac03_checkout_metered_line_item.rs"]
mod metering_ac03_checkout_metered_line_item;
#[path = "metering_ac04_emits_pro_calls_only.rs"]
mod metering_ac04_emits_pro_calls_only;
#[path = "metering_ac05_crash_replay.rs"]
mod metering_ac05_crash_replay;
#[path = "metering_ac06_failure_leaves_state_unmoved.rs"]
mod metering_ac06_failure_leaves_state_unmoved;
#[path = "metering_ac07_batches_cap_at_100.rs"]
mod metering_ac07_batches_cap_at_100;
#[path = "metering_ac08_healthz_meter_lag.rs"]
mod metering_ac08_healthz_meter_lag;
#[path = "metering_ac09_deploy_units_verify.rs"]
mod metering_ac09_deploy_units_verify;
#[path = "metering_ac11_admin_meter_status.rs"]
mod metering_ac11_admin_meter_status;
#[path = "metering_ac12_billing_status_stripe_reported_usage.rs"]
mod metering_ac12_billing_status_stripe_reported_usage;
#[path = "metering_billing_status_emitted_this_month.rs"]
mod metering_billing_status_emitted_this_month;
#[path = "migration_compat_headers.rs"]
mod migration_compat_headers;
#[path = "minimal_ac1_anonymous_ok_only.rs"]
mod minimal_ac1_anonymous_ok_only;
#[path = "minimal_ac2_admin_full_document.rs"]
mod minimal_ac2_admin_full_document;
#[path = "minimal_ac3_wrong_bearer_matches_anonymous.rs"]
mod minimal_ac3_wrong_bearer_matches_anonymous;
#[path = "minimal_ac4_liveness_failure_returns_5xx.rs"]
mod minimal_ac4_liveness_failure_returns_5xx;
#[path = "minimal_ac5_tenant_bearer_gets_anonymous_body.rs"]
mod minimal_ac5_tenant_bearer_gets_anonymous_body;
#[path = "msg_ac01_send_reaches_inbox.rs"]
mod msg_ac01_send_reaches_inbox;
#[path = "msg_ac02_reply_appends_next_seq.rs"]
mod msg_ac02_reply_appends_next_seq;
#[path = "msg_ac03_non_participant_thread_not_found.rs"]
mod msg_ac03_non_participant_thread_not_found;
#[path = "msg_ac04_dedupe_key.rs"]
mod msg_ac04_dedupe_key;
#[path = "msg_ac05_block.rs"]
mod msg_ac05_block;
#[path = "msg_ac06_inbox_cursor_concurrent.rs"]
mod msg_ac06_inbox_cursor_concurrent;
#[path = "msg_ac07_forged_from.rs"]
mod msg_ac07_forged_from;
#[path = "msg_ac08_contact_policy_closed.rs"]
mod msg_ac08_contact_policy_closed;
#[path = "msg_ac09_msgs_per_hour_quota.rs"]
mod msg_ac09_msgs_per_hour_quota;
#[path = "msg_ac10_body_and_recipients_quota.rs"]
mod msg_ac10_body_and_recipients_quota;
#[path = "msg_ac11_tenant_delete_cascade.rs"]
mod msg_ac11_tenant_delete_cascade;
#[path = "msg_ac12_send_latency.rs"]
mod msg_ac12_send_latency;
#[path = "msg_ac13_unread_only.rs"]
mod msg_ac13_unread_only;
#[path = "msg_ac14_thread_continuation.rs"]
mod msg_ac14_thread_continuation;
#[path = "msg_regr01_dedupe_hit_preserves_refused.rs"]
mod msg_regr01_dedupe_hit_preserves_refused;
#[path = "oauthconf_ac01_gate_verdict_table_matches_gold.rs"]
mod oauthconf_ac01_gate_verdict_table_matches_gold;
#[path = "oauthconf_ac02_cimd_preferred_over_dcr_and_unsupported_without_either.rs"]
mod oauthconf_ac02_cimd_preferred_over_dcr_and_unsupported_without_either;
#[path = "oauthconf_ac03_authorize_request_scope_resource_pkce_state.rs"]
mod oauthconf_ac03_authorize_request_scope_resource_pkce_state;
#[path = "oauthconf_ac04_attack_probes_pass_only_on_as_refusal.rs"]
mod oauthconf_ac04_attack_probes_pass_only_on_as_refusal;
#[path = "oauthconf_ac05_probe_cli_json_matches_gate_and_exit_codes.rs"]
mod oauthconf_ac05_probe_cli_json_matches_gate_and_exit_codes;
#[path = "oauthconf_ac06_records_and_receipt_never_leak_secrets.rs"]
mod oauthconf_ac06_records_and_receipt_never_leak_secrets;
#[path = "oauthconf_ac07_scenarios_doc_matches_gold_and_docs_sharing_check.rs"]
mod oauthconf_ac07_scenarios_doc_matches_gold_and_docs_sharing_check;
#[path = "oauthpol_ac01_allowlist_by_client_id_and_cimd_host.rs"]
mod oauthpol_ac01_allowlist_by_client_id_and_cimd_host;
#[path = "oauthpol_ac02_approve_mode_pending_approve_deny.rs"]
mod oauthpol_ac02_approve_mode_pending_approve_deny;
#[path = "oauthpol_ac03_session_ttls_and_max_grant_age.rs"]
mod oauthpol_ac03_session_ttls_and_max_grant_age;
#[path = "oauthpol_ac04_reconsent_after_forces_consent_again.rs"]
mod oauthpol_ac04_reconsent_after_forces_consent_again;
#[path = "oauthpol_ac05_revoke_all_grants_and_pending.rs"]
mod oauthpol_ac05_revoke_all_grants_and_pending;
#[path = "oauthpol_ac06_audit_paging_and_export.rs"]
mod oauthpol_ac06_audit_paging_and_export;
#[path = "oauthpol_ac07_operator_block_list_and_admin_rejection.rs"]
mod oauthpol_ac07_operator_block_list_and_admin_rejection;
#[path = "oauthpol_ac08_cimd_host_daily_registration_cap.rs"]
mod oauthpol_ac08_cimd_host_daily_registration_cap;
#[path = "oauthpol_ac09_no_policy_defaults_match_hosted_as.rs"]
mod oauthpol_ac09_no_policy_defaults_match_hosted_as;
#[path = "oauthrs_ac01_protected_resource_metadata_empty.rs"]
mod oauthrs_ac01_protected_resource_metadata_empty;
#[path = "oauthrs_ac02_bearer_jwt_runs_as_tenant.rs"]
mod oauthrs_ac02_bearer_jwt_runs_as_tenant;
#[path = "oauthrs_ac03_invalid_tokens_rejected_with_reasons.rs"]
mod oauthrs_ac03_invalid_tokens_rejected_with_reasons;
#[path = "oauthrs_ac04_401_challenge_signup_still_open.rs"]
mod oauthrs_ac04_401_challenge_signup_still_open;
#[path = "oauthrs_ac05_unknown_kid_refetch_throttled.rs"]
mod oauthrs_ac05_unknown_kid_refetch_throttled;
#[path = "oauthrs_ac06_jwks_server_down_unknown_issuer.rs"]
mod oauthrs_ac06_jwks_server_down_unknown_issuer;
#[path = "oauthrs_ac07_issuer_registration_limits.rs"]
mod oauthrs_ac07_issuer_registration_limits;
#[path = "oauthrs_ac08_conflicting_credentials.rs"]
mod oauthrs_ac08_conflicting_credentials;
#[path = "oauthrs_ac09_admin_lists_issuers_and_audits.rs"]
mod oauthrs_ac09_admin_lists_issuers_and_audits;
#[path = "oauthrs_ac10_key_based_flow_unchanged.rs"]
mod oauthrs_ac10_key_based_flow_unchanged;
#[path = "oauthsig_ac01_auth_method_by_credential.rs"]
mod oauthsig_ac01_auth_method_by_credential;
#[path = "oauthsig_ac02_healthz_calls_and_tenants_by_method.rs"]
mod oauthsig_ac02_healthz_calls_and_tenants_by_method;
#[path = "oauthsig_ac03_admin_oauth_stats_tenant_rows_and_admin_only.rs"]
mod oauthsig_ac03_admin_oauth_stats_tenant_rows_and_admin_only;
#[path = "oauthsig_ac04_admin_oauth_stats_funnel.rs"]
mod oauthsig_ac04_admin_oauth_stats_funnel;
#[path = "oauthsig_ac05_healthz_cache_and_p95.rs"]
mod oauthsig_ac05_healthz_cache_and_p95;
#[path = "oauthsig_ac06_conformance_script_writes_receipt.rs"]
mod oauthsig_ac06_conformance_script_writes_receipt;
#[path = "plancat_ac01_missing_state_quotas_default_from_catalog.rs"]
mod plancat_ac01_missing_state_quotas_default_from_catalog;
#[path = "plancat_ac02_startup_logs_defaulted_fields.rs"]
mod plancat_ac02_startup_logs_defaulted_fields;
#[path = "plancat_ac03_unknown_plan_name_defaults_from_free.rs"]
mod plancat_ac03_unknown_plan_name_defaults_from_free;
#[path = "plancat_ac04_healthz_lists_plans_with_quotas.rs"]
mod plancat_ac04_healthz_lists_plans_with_quotas;
#[path = "plancat_ac05_full_plans_toml_unchanged_and_silent.rs"]
mod plancat_ac05_full_plans_toml_unchanged_and_silent;
#[path = "plancat_ac06_build_has_no_hardcoded_quota_defaults.rs"]
mod plancat_ac06_build_has_no_hardcoded_quota_defaults;
#[path = "plancat_ac07_llms_txt_names_defaulting_and_startup_line.rs"]
mod plancat_ac07_llms_txt_names_defaulting_and_startup_line;
#[path = "proptest_invariants.rs"]
mod proptest_invariants;
#[path = "provaudit_ac01_synthetic_signup_stamped.rs"]
mod provaudit_ac01_synthetic_signup_stamped;
#[path = "provaudit_ac02_external_signup_stamped.rs"]
mod provaudit_ac02_external_signup_stamped;
#[path = "provaudit_ac03_migration_backfill_counts.rs"]
mod provaudit_ac03_migration_backfill_counts;
#[path = "provaudit_ac04_healthz_split_shape.rs"]
mod provaudit_ac04_healthz_split_shape;
#[path = "provaudit_ac05_admin_audit_log.rs"]
mod provaudit_ac05_admin_audit_log;
#[path = "provaudit_ac06_null_origin_rejected.rs"]
mod provaudit_ac06_null_origin_rejected;
#[path = "provaudit_ac07_ip_class_triage.rs"]
mod provaudit_ac07_ip_class_triage;
#[path = "proxy_ac1_loopback_xff_resolves_signup_source.rs"]
mod proxy_ac1_loopback_xff_resolves_signup_source;
#[path = "proxy_ac2_non_loopback_peer_ignores_header.rs"]
mod proxy_ac2_non_loopback_peer_ignores_header;
#[path = "proxy_ac3_unparseable_header_falls_back.rs"]
mod proxy_ac3_unparseable_header_falls_back;
#[path = "proxy_ac4_rate_limit_keys_on_resolved_address.rs"]
mod proxy_ac4_rate_limit_keys_on_resolved_address;
#[path = "proxy_ac5_signup_event_stores_forwarded_address.rs"]
mod proxy_ac5_signup_event_stores_forwarded_address;
#[path = "proxy_ac6_healthz_distinct_source_ips.rs"]
mod proxy_ac6_healthz_distinct_source_ips;
#[path = "publishfirsttry_ac01_tool_publish_description.rs"]
mod publishfirsttry_ac01_tool_publish_description;
#[path = "publishfirsttry_ac02_structured_error_fields.rs"]
mod publishfirsttry_ac02_structured_error_fields;
#[path = "publishfirsttry_ac07_signup_next.rs"]
mod publishfirsttry_ac07_signup_next;
#[path = "revdebt_ac1_intent_card_pointers_resolve.rs"]
mod revdebt_ac1_intent_card_pointers_resolve;
#[path = "run_metrics_handoff_glob_regression.rs"]
mod run_metrics_handoff_glob_regression;
#[path = "runoverflow_ac03_progress_counter_monotonic_validation.rs"]
mod runoverflow_ac03_progress_counter_monotonic_validation;
#[path = "runoverflow_ac04_inline_part_zero_and_out_of_range_not_found.rs"]
mod runoverflow_ac04_inline_part_zero_and_out_of_range_not_found;
#[path = "runoverflow_ac05_http_async_2mib_overflows_to_parts.rs"]
mod runoverflow_ac05_http_async_2mib_overflows_to_parts;
#[path = "runs_ac05_sync_call_writes_run_row.rs"]
mod runs_ac05_sync_call_writes_run_row;
#[path = "runs_ac07_purge_clears_result.rs"]
mod runs_ac07_purge_clears_result;
#[path = "runs_ac08_tenant_delete_cascades_runs.rs"]
mod runs_ac08_tenant_delete_cascades_runs;
#[path = "runs_ac09_quickstart_and_llms_txt_name_job_limits.rs"]
mod runs_ac09_quickstart_and_llms_txt_name_job_limits;
#[path = "runs_ac10_wait_long_polls.rs"]
mod runs_ac10_wait_long_polls;
#[path = "runs_ac11_admin_runs_reap.rs"]
mod runs_ac11_admin_runs_reap;
#[path = "runsubject_ac01_async_assertion_end_user_on_run.rs"]
mod runsubject_ac01_async_assertion_end_user_on_run;
#[path = "runsubject_ac02_list_filters_by_end_user_subject.rs"]
mod runsubject_ac02_list_filters_by_end_user_subject;
#[path = "runsubject_ac03_oauth_run_carries_issuer_and_method.rs"]
mod runsubject_ac03_oauth_run_carries_issuer_and_method;
#[path = "runsubject_ac04_schedule_fired_run_end_user_null.rs"]
mod runsubject_ac04_schedule_fired_run_end_user_null;
#[path = "runsubject_ac05_list_output_unchanged_but_for_end_user.rs"]
mod runsubject_ac05_list_output_unchanged_but_for_end_user;
#[path = "runsubject_ac06_migration_0048_under_1s_at_100k_rows.rs"]
mod runsubject_ac06_migration_0048_under_1s_at_100k_rows;
#[path = "runsubject_ac07_llms_txt_names_end_user_and_filter.rs"]
mod runsubject_ac07_llms_txt_names_end_user_and_filter;
#[path = "sandboxready_ac7_conformance_suite.rs"]
mod sandboxready_ac7_conformance_suite;
#[path = "sched_ac10_trigger_fire_manual.rs"]
mod sched_ac10_trigger_fire_manual;
#[path = "sched_ac1_two_firings_visible_in_ledger.rs"]
mod sched_ac1_two_firings_visible_in_ledger;
#[path = "sched_ac2_invalid_cron_names_minute.rs"]
mod sched_ac2_invalid_cron_names_minute;
#[path = "sched_ac3_free_plan_quota_exceeded.rs"]
mod sched_ac3_free_plan_quota_exceeded;
#[path = "sched_ac4_free_plan_interval_too_short.rs"]
mod sched_ac4_free_plan_interval_too_short;
#[path = "sched_ac5_overlap_skips_and_records.rs"]
mod sched_ac5_overlap_skips_and_records;
#[path = "sched_ac6_pause_blocks_resume_allows.rs"]
mod sched_ac6_pause_blocks_resume_allows;
#[path = "sched_ac7_tool_remove_disables_triggers.rs"]
mod sched_ac7_tool_remove_disables_triggers;
#[path = "sched_ac8_healthz_scheduler_fields.rs"]
mod sched_ac8_healthz_scheduler_fields;
#[path = "sched_quickstart_and_usage_report_schedules.rs"]
mod sched_quickstart_and_usage_report_schedules;
#[path = "self_offboard_ac1_disables_tenant_and_returns_success.rs"]
mod self_offboard_ac1_disables_tenant_and_returns_success;
#[path = "self_offboard_ac2_idempotent_second_call.rs"]
mod self_offboard_ac2_idempotent_second_call;
#[path = "self_offboard_ac3_offboarded_key_same_shape_as_unissued.rs"]
mod self_offboard_ac3_offboarded_key_same_shape_as_unissued;
#[path = "self_offboard_ac4_pro_tenant_cancels_stripe_subscription.rs"]
mod self_offboard_ac4_pro_tenant_cancels_stripe_subscription;
#[path = "self_offboard_ac5_admin_tenants_distinguishes_reason.rs"]
mod self_offboard_ac5_admin_tenants_distinguishes_reason;
#[path = "sessbind_ac01_keyless_call_after_signup_runs_as_the_bound_tenant.rs"]
mod sessbind_ac01_keyless_call_after_signup_runs_as_the_bound_tenant;
#[path = "sessbind_ac02_five_tools_run_as_the_bound_tenant.rs"]
mod sessbind_ac02_five_tools_run_as_the_bound_tenant;
#[path = "sessbind_ac03_anonymous_session_unchanged.rs"]
mod sessbind_ac03_anonymous_session_unchanged;
#[path = "sessbind_ac04_explicit_key_wins_over_the_binding.rs"]
mod sessbind_ac04_explicit_key_wins_over_the_binding;
#[path = "sessbind_ac05_bearer_wins_and_the_binding_survives.rs"]
mod sessbind_ac05_bearer_wins_and_the_binding_survives;
#[path = "sessbind_ac06_second_signup_rebinds_and_reports_session_bound.rs"]
mod sessbind_ac06_second_signup_rebinds_and_reports_session_bound;
#[path = "sessbind_ac07_concurrent_sessions_no_cross_session_leak.rs"]
mod sessbind_ac07_concurrent_sessions_no_cross_session_leak;
#[path = "sessbind_ac08_binding_map_is_bounded_under_a_session_flood.rs"]
mod sessbind_ac08_binding_map_is_bounded_under_a_session_flood;
#[path = "sessbind_ac09_disabled_bound_tenant_drops_the_binding.rs"]
mod sessbind_ac09_disabled_bound_tenant_drops_the_binding;
#[path = "sessbind_ac10_request_log_records_the_upgraded_status.rs"]
mod sessbind_ac10_request_log_records_the_upgraded_status;
#[path = "sessbind_ac11_session_bound_calls_are_metered_and_counted.rs"]
mod sessbind_ac11_session_bound_calls_are_metered_and_counted;
#[path = "sessbind_ac12_tenant_key_description_states_signup_optionality.rs"]
mod sessbind_ac12_tenant_key_description_states_signup_optionality;
#[path = "sessbind_ac13_regression_gate.rs"]
mod sessbind_ac13_regression_gate;
#[path = "sessionkey_ac02_ac03_discovery_shape.rs"]
mod sessionkey_ac02_ac03_discovery_shape;
#[path = "sessionkey_ac04_signup_usage_field.rs"]
mod sessionkey_ac04_signup_usage_field;
#[path = "sessionkey_ac05_ac07_ac08_ac09_tenant_key_auth.rs"]
mod sessionkey_ac05_ac07_ac08_ac09_tenant_key_auth;
#[path = "sessionkey_ac06_publish_via_tenant_key.rs"]
mod sessionkey_ac06_publish_via_tenant_key;
#[path = "sessionkey_ac10_tenant_key_to_admin_forbidden.rs"]
mod sessionkey_ac10_tenant_key_to_admin_forbidden;
#[path = "sessionkey_ac11_ac12_ac13_ac14_ac15_tool_call.rs"]
mod sessionkey_ac11_ac12_ac13_ac14_ac15_tool_call;
#[path = "sessionkey_ac16_full_session_no_header.rs"]
mod sessionkey_ac16_full_session_no_header;
#[path = "sessionkey_ac18_tool_logs_no_key.rs"]
mod sessionkey_ac18_tool_logs_no_key;
#[path = "sessionkey_ac19_nested_tenant_key_redacted.rs"]
mod sessionkey_ac19_nested_tenant_key_redacted;
#[path = "sessionkey_ac20_error_message_no_key.rs"]
mod sessionkey_ac20_error_message_no_key;
#[path = "share_ac01_public_tool_cross_tenant_call.rs"]
mod share_ac01_public_tool_cross_tenant_call;
#[path = "share_ac02_private_tool_still_not_found.rs"]
mod share_ac02_private_tool_still_not_found;
#[path = "share_ac03_group_visibility_members_only.rs"]
mod share_ac03_group_visibility_members_only;
#[path = "share_ac04_secret_never_reaches_caller.rs"]
mod share_ac04_secret_never_reaches_caller;
#[path = "share_ac05_usage_and_quota_attribution.rs"]
mod share_ac05_usage_and_quota_attribution;
#[path = "share_ac06_share_quota_exceeded.rs"]
mod share_ac06_share_quota_exceeded;
#[path = "share_ac07_catalog_search_and_well_known.rs"]
mod share_ac07_catalog_search_and_well_known;
#[path = "share_ac08_unshare_revokes_access.rs"]
mod share_ac08_unshare_revokes_access;
#[path = "share_ac09_admin_tool_unshare.rs"]
mod share_ac09_admin_tool_unshare;
#[path = "sharedcall_ac01_host_tool_call_public_cross_tenant.rs"]
mod sharedcall_ac01_host_tool_call_public_cross_tenant;
#[path = "sharedcall_ac02_group_share_non_member_gets_hint.rs"]
mod sharedcall_ac02_group_share_non_member_gets_hint;
#[path = "sharedcall_ac03_not_found_reasons_indistinguishable.rs"]
mod sharedcall_ac03_not_found_reasons_indistinguishable;
#[path = "sharedcall_ac04_async_qualified_call_scoped_to_caller.rs"]
mod sharedcall_ac04_async_qualified_call_scoped_to_caller;
#[path = "sharedcall_ac05_gen_docs_sharing_check.rs"]
mod sharedcall_ac05_gen_docs_sharing_check;
#[path = "sharedcall_ac06_proof_script_qualified_host_tool_call.rs"]
mod sharedcall_ac06_proof_script_qualified_host_tool_call;
#[path = "sharedcall_ac07_own_unqualified_call_unchanged.rs"]
mod sharedcall_ac07_own_unqualified_call_unchanged;
#[path = "sharedcall_ac08_get_info_lists_shared_tools_with_via.rs"]
mod sharedcall_ac08_get_info_lists_shared_tools_with_via;
#[path = "sharedcall_ac09_quota_exhausted_qualified_call_refused.rs"]
mod sharedcall_ac09_quota_exhausted_qualified_call_refused;
#[path = "sharedrunscope_ac01_caller_sees_sync_shared_run.rs"]
mod sharedrunscope_ac01_caller_sees_sync_shared_run;
#[path = "sharedrunscope_ac02_owner_cannot_see_callers_run.rs"]
mod sharedrunscope_ac02_owner_cannot_see_callers_run;
#[path = "sharedrunscope_ac03_owner_meter_and_usage_unchanged.rs"]
mod sharedrunscope_ac03_owner_meter_and_usage_unchanged;
#[path = "sharedrunscope_ac04_own_call_run_row_unchanged.rs"]
mod sharedrunscope_ac04_own_call_run_row_unchanged;
#[path = "sharedrunscope_ac05_async_and_sync_share_scoping.rs"]
mod sharedrunscope_ac05_async_and_sync_share_scoping;
#[path = "sharedrunscope_ac06_raw_tools_call_shares_the_path.rs"]
mod sharedrunscope_ac06_raw_tools_call_shares_the_path;
#[path = "sharedrunscope_ac07_migration_backfills_legacy_rows.rs"]
mod sharedrunscope_ac07_migration_backfills_legacy_rows;
#[path = "sharedrunscope_ac08_proof_script_owner_ledger_check.rs"]
mod sharedrunscope_ac08_proof_script_owner_ledger_check;
#[path = "signupfleet_ac01_fleet_ips_bypass_signup_rate_limit.rs"]
mod signupfleet_ac01_fleet_ips_bypass_signup_rate_limit;
#[path = "specpath_ac01_map_form_normalizes_and_publishes.rs"]
mod specpath_ac01_map_form_normalizes_and_publishes;
#[path = "specpath_ac02_outputs_map_value_type_error.rs"]
mod specpath_ac02_outputs_map_value_type_error;
#[path = "specpath_ac03_headers_array_type_error.rs"]
mod specpath_ac03_headers_array_type_error;
#[path = "specpath_ac04_path_reads_declared_field.rs"]
mod specpath_ac04_path_reads_declared_field;
#[path = "specpath_ac05_missing_path_reports_tried_path.rs"]
mod specpath_ac05_missing_path_reports_tried_path;
#[path = "specpath_ac06_list_form_seen_at_hint.rs"]
mod specpath_ac06_list_form_seen_at_hint;
#[path = "specpath_ac07_replay_recorded_sessions_map_form.rs"]
mod specpath_ac07_replay_recorded_sessions_map_form;
#[path = "specpath_ac08_wildcard_path_rejected.rs"]
mod specpath_ac08_wildcard_path_rejected;
#[path = "state_ac01_kv_roundtrip.rs"]
mod state_ac01_kv_roundtrip;
#[path = "state_ac04_table_query.rs"]
mod state_ac04_table_query;
#[path = "state_ac05_schema_violation.rs"]
mod state_ac05_schema_violation;
#[path = "state_ac06_quota_exceeded.rs"]
mod state_ac06_quota_exceeded;
#[path = "state_ac08_tenant_isolation.rs"]
mod state_ac08_tenant_isolation;
#[path = "state_ac09_cascade_delete.rs"]
mod state_ac09_cascade_delete;
#[path = "statusfeed_ac02_exec_disabled_degrades.rs"]
mod statusfeed_ac02_exec_disabled_degrades;
#[path = "statusfeed_ac03_major_incident_outage.rs"]
mod statusfeed_ac03_major_incident_outage;
#[path = "statusfeed_ac04_incident_timeline_and_close.rs"]
mod statusfeed_ac04_incident_timeline_and_close;
#[path = "statusfeed_ac05_daily_rollup_uptime.rs"]
mod statusfeed_ac05_daily_rollup_uptime;
#[path = "statusfeed_ac06_external_sample_source_preserved.rs"]
mod statusfeed_ac06_external_sample_source_preserved;
#[path = "statusfeed_ac07_prune_keeps_rollup.rs"]
mod statusfeed_ac07_prune_keeps_rollup;
#[path = "statusfeed_ac08_status_html_renders.rs"]
mod statusfeed_ac08_status_html_renders;
#[path = "statusfeed_ac10_component_days_query.rs"]
mod statusfeed_ac10_component_days_query;
#[path = "statusfeed_ac11_deferral_is_justified.rs"]
mod statusfeed_ac11_deferral_is_justified;
#[path = "suite_ac1_ten_binaries_and_names_preserved.rs"]
mod suite_ac1_ten_binaries_and_names_preserved;
#[path = "suite_ac2_check_catches_unregistered_file.rs"]
mod suite_ac2_check_catches_unregistered_file;
#[path = "suite_ac3_mod_common_declared_once.rs"]
mod suite_ac3_mod_common_declared_once;
#[path = "suite_ac4_archived_prd_pointers_resolve.rs"]
mod suite_ac4_archived_prd_pointers_resolve;
#[path = "suite_ac5_disk_size_budget.rs"]
mod suite_ac5_disk_size_budget;
#[path = "suite_ac6_wall_time_budget.rs"]
mod suite_ac6_wall_time_budget;
#[path = "suite_ac7_junit_per_test_timing.rs"]
mod suite_ac7_junit_per_test_timing;
#[path = "suite_ac9_selftest_named_and_green.rs"]
mod suite_ac9_selftest_named_and_green;
#[path = "support_ac01_bearer_invalid_help_url.rs"]
mod support_ac01_bearer_invalid_help_url;
#[path = "support_ac02_internal_error_generic_and_logged.rs"]
mod support_ac02_internal_error_generic_and_logged;
#[path = "support_ac03_disk_floor_and_5xx_messages_generic.rs"]
mod support_ac03_disk_floor_and_5xx_messages_generic;
#[path = "support_ac04_plans_doc_and_json_consistent.rs"]
mod support_ac04_plans_doc_and_json_consistent;
#[path = "support_ac05_support_url_rendered_or_not_configured.rs"]
mod support_ac05_support_url_rendered_or_not_configured;
#[path = "support_ac06_served_pages_from_docs_and_readme.rs"]
mod support_ac06_served_pages_from_docs_and_readme;
#[path = "support_ac07_whoami_links_resolve.rs"]
mod support_ac07_whoami_links_resolve;
#[path = "support_ac08_release_artifact_includes_www.rs"]
mod support_ac08_release_artifact_includes_www;
#[path = "surface_ac02_dry_run_descriptions.rs"]
mod surface_ac02_dry_run_descriptions;
#[path = "surface_ac03_args_invalid_unified.rs"]
mod surface_ac03_args_invalid_unified;
#[path = "surface_ac04_required_field_descriptions.rs"]
mod surface_ac04_required_field_descriptions;
#[path = "surface_ac05_llms_txt_tool_parity.rs"]
mod surface_ac05_llms_txt_tool_parity;
#[path = "surface_ac07_tool_publish_description_length.rs"]
mod surface_ac07_tool_publish_description_length;
#[path = "surface_ac08_get_info_mentions_try_before_call.rs"]
mod surface_ac08_get_info_mentions_try_before_call;
#[path = "surface_tool_description_min_length.rs"]
mod surface_tool_description_min_length;
#[path = "synthetic_ac01_migration_null_default.rs"]
mod synthetic_ac01_migration_null_default;
#[path = "synthetic_ac02_signup_header_sets_label.rs"]
mod synthetic_ac02_signup_header_sets_label;
#[path = "synthetic_ac04_tenant_facing_byte_identical.rs"]
mod synthetic_ac04_tenant_facing_byte_identical;
#[path = "synthetic_ac05_admin_tenant_set_synthetic.rs"]
mod synthetic_ac05_admin_tenant_set_synthetic;
#[path = "synthetic_ac06_bulk_retro_tag.rs"]
mod synthetic_ac06_bulk_retro_tag;
#[path = "synthetic_ac07_healthz_counts.rs"]
mod synthetic_ac07_healthz_counts;
#[path = "synthetic_ac08_admin_tenants_field.rs"]
mod synthetic_ac08_admin_tenants_field;
#[path = "synthetic_ac09_metering_filter.rs"]
mod synthetic_ac09_metering_filter;
#[path = "synthetic_ac10_healthz_paying_real.rs"]
mod synthetic_ac10_healthz_paying_real;
#[path = "tablemodel_ac01_key_id_measure_category_date_roles.rs"]
mod tablemodel_ac01_key_id_measure_category_date_roles;
#[path = "tablemodel_ac02_foreign_key_detected_against_customers_id.rs"]
mod tablemodel_ac02_foreign_key_detected_against_customers_id;
#[path = "tablemodel_ac03_measures_and_dimensions_suggested.rs"]
mod tablemodel_ac03_measures_and_dimensions_suggested;
#[path = "tablemodel_ac04_null_share_with_category_role_preserved.rs"]
mod tablemodel_ac04_null_share_with_category_role_preserved;
#[path = "tablemodel_ac05_stale_after_append_recomputes_on_tick.rs"]
mod tablemodel_ac05_stale_after_append_recomputes_on_tick;
#[path = "tablemodel_ac06_large_table_samples_10000_under_500ms.rs"]
mod tablemodel_ac06_large_table_samples_10000_under_500ms;
#[path = "tablemodel_ac07_model_set_unit_annotation_survives_refresh.rs"]
mod tablemodel_ac07_model_set_unit_annotation_survives_refresh;
#[path = "tablemodel_ac08_model_set_role_override_keeps_inferred_role.rs"]
mod tablemodel_ac08_model_set_role_override_keeps_inferred_role;
#[path = "tablemodel_ac09_drop_removes_model_and_annotations.rs"]
mod tablemodel_ac09_drop_removes_model_and_annotations;
#[path = "tablemodel_ac10_empty_table_reports_unknown_types_no_error.rs"]
mod tablemodel_ac10_empty_table_reports_unknown_types_no_error;
#[path = "tables_ac07_tenant_delete_cascade.rs"]
mod tables_ac07_tenant_delete_cascade;
#[path = "tenant_delete_ac01_cascade_delete.rs"]
mod tenant_delete_ac01_cascade_delete;
#[path = "tenant_delete_ac02_forbidden.rs"]
mod tenant_delete_ac02_forbidden;
#[path = "tenant_delete_ac03_dry_run_prefix.rs"]
mod tenant_delete_ac03_dry_run_prefix;
#[path = "tenant_delete_ac04_prefix_delete.rs"]
mod tenant_delete_ac04_prefix_delete;
#[path = "tenant_delete_ac05_prefix_too_short.rs"]
mod tenant_delete_ac05_prefix_too_short;
#[path = "tenant_delete_ac06_migration_cascade.rs"]
mod tenant_delete_ac06_migration_cascade;
#[path = "tenant_delete_ac07_tenant_not_found.rs"]
mod tenant_delete_ac07_tenant_not_found;
#[path = "tenant_delete_ac09_healthz_probe_split.rs"]
mod tenant_delete_ac09_healthz_probe_split;
#[path = "tenant_delete_ac10_tenants_prefix_filter.rs"]
mod tenant_delete_ac10_tenants_prefix_filter;
#[path = "tenantprm_ac01_tenant_metadata_document.rs"]
mod tenantprm_ac01_tenant_metadata_document;
#[path = "tenantprm_ac02_bearer_jwt_tenant_and_audience_scoping.rs"]
mod tenantprm_ac02_bearer_jwt_tenant_and_audience_scoping;
#[path = "tenantprm_ac03_key_based_tenant_scoping_and_unknown_ns_404.rs"]
mod tenantprm_ac03_key_based_tenant_scoping_and_unknown_ns_404;
#[path = "tenantprm_ac04_401_challenge_names_tenant_or_root_metadata.rs"]
mod tenantprm_ac04_401_challenge_names_tenant_or_root_metadata;
#[path = "tenantprm_ac05_scope_gates_tool_calls.rs"]
mod tenantprm_ac05_scope_gates_tool_calls;
#[path = "tenantprm_ac06_whoami_carries_resource_and_metadata_url.rs"]
mod tenantprm_ac06_whoami_carries_resource_and_metadata_url;
#[path = "tenantprm_ac07_key_and_oauth_suites_unchanged.rs"]
mod tenantprm_ac07_key_and_oauth_suites_unchanged;
#[path = "tenantprm_ac09_llms_txt_documents_tenant_oauth.rs"]
mod tenantprm_ac09_llms_txt_documents_tenant_oauth;
#[path = "tkparam_ac01_tenant_key_missing_is_invalid_params.rs"]
mod tkparam_ac01_tenant_key_missing_is_invalid_params;
#[path = "tkparam_ac02_non_string_tenant_key_is_invalid_params.rs"]
mod tkparam_ac02_non_string_tenant_key_is_invalid_params;
#[path = "tkparam_ac03_five_tools_missing_tenant_key.rs"]
mod tkparam_ac03_five_tools_missing_tenant_key;
#[path = "tkparam_ac04_header_auth_unaffected.rs"]
mod tkparam_ac04_header_auth_unaffected;
#[path = "tkparam_ac05_tenant_key_invalid_unchanged.rs"]
mod tkparam_ac05_tenant_key_invalid_unchanged;
#[path = "tkparam_ac06_tenant_key_missing_payload_fields.rs"]
mod tkparam_ac06_tenant_key_missing_payload_fields;
#[path = "tkparam_ac07_example_is_placeholder_not_live.rs"]
mod tkparam_ac07_example_is_placeholder_not_live;
#[path = "tkparam_ac08_secretmissing_and_invalidparams_shape_unchanged.rs"]
mod tkparam_ac08_secretmissing_and_invalidparams_shape_unchanged;
#[path = "tkparam_ac09_schema_tenant_key_not_required_and_discoverable.rs"]
mod tkparam_ac09_schema_tenant_key_not_required_and_discoverable;
#[path = "tkparam_ac11_full_suite_green_at_landing.rs"]
mod tkparam_ac11_full_suite_green_at_landing;
#[path = "toolscope_ac01_scoped_consent_and_token.rs"]
mod toolscope_ac01_scoped_consent_and_token;
#[path = "toolscope_ac02_scoped_token_list_and_call.rs"]
mod toolscope_ac02_scoped_token_list_and_call;
#[path = "toolscope_ac03_step_up_reauthorize_union_scope.rs"]
mod toolscope_ac03_step_up_reauthorize_union_scope;
#[path = "toolscope_ac04_mcp_key_and_pre_prd_token_unaffected.rs"]
mod toolscope_ac04_mcp_key_and_pre_prd_token_unaffected;
#[path = "toolscope_ac05_publish_scope_validation.rs"]
mod toolscope_ac05_publish_scope_validation;
#[path = "toolscope_ac06_scope_change_takes_effect_next_call.rs"]
mod toolscope_ac06_scope_change_takes_effect_next_call;
#[path = "toolscope_ac07_metadata_scopes_supported.rs"]
mod toolscope_ac07_metadata_scopes_supported;
#[path = "toolscope_ac08_admin_stats_consents_by_scope.rs"]
mod toolscope_ac08_admin_stats_consents_by_scope;
#[path = "tooltest_ac12_log_marking.rs"]
mod tooltest_ac12_log_marking;
#[path = "tooltest_ac3_http_dry_run.rs"]
mod tooltest_ac3_http_dry_run;
#[path = "tooltest_ac4_echo_verbatim.rs"]
mod tooltest_ac4_echo_verbatim;
#[path = "tooltest_ac5_validation_error_taxonomy.rs"]
mod tooltest_ac5_validation_error_taxonomy;
#[path = "tooltest_ac6_quota_and_metering.rs"]
mod tooltest_ac6_quota_and_metering;
#[path = "tooltest_ac7_too_many_invocations.rs"]
mod tooltest_ac7_too_many_invocations;
#[path = "tooltest_ac9_ac10_listing_and_auth.rs"]
mod tooltest_ac9_ac10_listing_and_auth;
#[path = "vault_ac01_connect_link_redirects_to_auth_url.rs"]
mod vault_ac01_connect_link_redirects_to_auth_url;
#[path = "vault_ac02_callback_exchanges_code_and_stores_tokens.rs"]
mod vault_ac02_callback_exchanges_code_and_stores_tokens;
#[path = "vault_ac03_injects_bearer_overriding_tool_header.rs"]
mod vault_ac03_injects_bearer_overriding_tool_header;
#[path = "vault_ac04_call_log_never_contains_token.rs"]
mod vault_ac04_call_log_never_contains_token;
#[path = "vault_ac05_refresh_before_expiry_used_once.rs"]
mod vault_ac05_refresh_before_expiry_used_once;
#[path = "vault_ac06_unconnected_end_user_gets_connect_link.rs"]
mod vault_ac06_unconnected_end_user_gets_connect_link;
#[path = "vault_ac07_used_handoff_token_returns_410.rs"]
mod vault_ac07_used_handoff_token_returns_410;
#[path = "vault_ac08_disconnect_revokes_and_blocks_calls.rs"]
mod vault_ac08_disconnect_revokes_and_blocks_calls;
#[path = "vault_ac09_providers_hides_client_secret.rs"]
mod vault_ac09_providers_hides_client_secret;
#[path = "vault_ac10_refresh_401_revokes_no_retry_storm.rs"]
mod vault_ac10_refresh_401_revokes_no_retry_storm;
#[path = "vault_ac11_quota_vault_providers.rs"]
mod vault_ac11_quota_vault_providers;
#[path = "vaultst_ac01_status_lists_connected_and_unconnected_providers.rs"]
mod vaultst_ac01_status_lists_connected_and_unconnected_providers;
#[path = "vaultst_ac02_status_end_user_resolution_matches_connect_link.rs"]
mod vaultst_ac02_status_end_user_resolution_matches_connect_link;
#[path = "vaultst_ac03_status_shows_revoked_after_refresh_401.rs"]
mod vaultst_ac03_status_shows_revoked_after_refresh_401;
#[path = "vaultst_ac04_admin_vault_stats_per_tenant_per_provider.rs"]
mod vaultst_ac04_admin_vault_stats_per_tenant_per_provider;
#[path = "vaultst_ac05_admin_vault_stats_rejects_tenant_key.rs"]
mod vaultst_ac05_admin_vault_stats_rejects_tenant_key;
#[path = "vaultst_ac06_provider_remove_revokes_all_tokens.rs"]
mod vaultst_ac06_provider_remove_revokes_all_tokens;
#[path = "vaultst_ac07_provider_set_presets_fill_urls.rs"]
mod vaultst_ac07_provider_set_presets_fill_urls;
#[path = "vaultst_ac08_llms_txt_documents_vault_and_sharing_check_green.rs"]
mod vaultst_ac08_llms_txt_documents_vault_and_sharing_check_green;
#[path = "vaultst_ac09_deferral_is_justified.rs"]
mod vaultst_ac09_deferral_is_justified;
#[path = "vaultst_ac09_live_vault_status_trailer.rs"]
mod vaultst_ac09_live_vault_status_trailer;
#[path = "wake_ac1_message_trigger_fires_run.rs"]
mod wake_ac1_message_trigger_fires_run;
#[path = "wake_ac2_from_filter.rs"]
mod wake_ac2_from_filter;
#[path = "wake_ac3_dedupe.rs"]
mod wake_ac3_dedupe;
#[path = "wake_ac4_jobs_concurrent_rejects.rs"]
mod wake_ac4_jobs_concurrent_rejects;
#[path = "wake_ac5_pause_resume.rs"]
mod wake_ac5_pause_resume;
#[path = "wake_ac6_msg_wait.rs"]
mod wake_ac6_msg_wait;
#[path = "wake_ac7_trigger_test_synthetic_envelope.rs"]
mod wake_ac7_trigger_test_synthetic_envelope;
#[path = "wake_ac8_replay.rs"]
mod wake_ac8_replay;
#[path = "wasmkind_ac01_echo_component_calls_and_meters.rs"]
mod wasmkind_ac01_echo_component_calls_and_meters;
#[path = "wasmkind_ac02_publish_validation_errors.rs"]
mod wasmkind_ac02_publish_validation_errors;
#[path = "wasmkind_ac03_timeout_and_oom_recover.rs"]
mod wasmkind_ac03_timeout_and_oom_recover;
#[path = "wasmkind_ac05_tool_test_dry_run.rs"]
mod wasmkind_ac05_tool_test_dry_run;
#[path = "wasmkind_ac06_trap_is_structured_and_logged.rs"]
mod wasmkind_ac06_trap_is_structured_and_logged;
#[path = "wasmkind_ac07_docs_llms_and_quickstart_document_wasm.rs"]
mod wasmkind_ac07_docs_llms_and_quickstart_document_wasm;
#[path = "wasmkind_ac08_cache_reuses_compiled_artifact.rs"]
mod wasmkind_ac08_cache_reuses_compiled_artifact;
#[path = "wasmkind_ac09_healthz_reports_wasm_runtime.rs"]
mod wasmkind_ac09_healthz_reports_wasm_runtime;
#[path = "wasmkind_ac10_declared_output_promotion_matches_python.rs"]
mod wasmkind_ac10_declared_output_promotion_matches_python;
#[path = "xaa_ac01_valid_assertion_no_consent.rs"]
mod xaa_ac01_valid_assertion_no_consent;
#[path = "xaa_ac03_invalid_grant_reasons_are_distinct_and_audited.rs"]
mod xaa_ac03_invalid_grant_reasons_are_distinct_and_audited;
#[path = "xaa_ac04_invalid_client_scope_target.rs"]
mod xaa_ac04_invalid_client_scope_target;
#[path = "xaa_ac05_metadata_grant_types_and_trusted_issuer.rs"]
mod xaa_ac05_metadata_grant_types_and_trusted_issuer;
#[path = "xaa_ac06_offline_access_gates_refresh_token.rs"]
mod xaa_ac06_offline_access_gates_refresh_token;
#[path = "xaa_ac07_revoke_and_unrevoke_end_user.rs"]
mod xaa_ac07_revoke_and_unrevoke_end_user;
#[path = "xaa_ac08_trusted_issuer_quota.rs"]
mod xaa_ac08_trusted_issuer_quota;
#[path = "xaa_ac09_hosted_and_key_paths_unchanged.rs"]
mod xaa_ac09_hosted_and_key_paths_unchanged;
