// GENERATED by scripts/gen-test-suites.sh -- do not edit by hand.
// Regenerate with: scripts/gen-test-suites.sh
// Check for drift with: scripts/gen-test-suites.sh --check
//
// This file exists only to give cargo one test BINARY for the files listed
// below; it declares no tests of its own. Every included file keeps its
// original name, path, and test names (nextest's test list, with this
// suite's prefix stripped, is unchanged from before consolidation).
mod common;

#[path = "http_ac01_secret_redaction.rs"]
mod http_ac01_secret_redaction;
#[path = "http_ac02_publish_ssrf_literal.rs"]
mod http_ac02_publish_ssrf_literal;
#[path = "http_ac03_publish_secret_missing.rs"]
mod http_ac03_publish_secret_missing;
#[path = "http_ac04_args_invalid.rs"]
mod http_ac04_args_invalid;
#[path = "http_ac05_upstream_429_retry_after.rs"]
mod http_ac05_upstream_429_retry_after;
#[path = "http_ac06_upstream_timeout.rs"]
mod http_ac06_upstream_timeout;
#[path = "http_ac07_response_too_large.rs"]
mod http_ac07_response_too_large;
#[path = "http_ac08_template_error.rs"]
mod http_ac08_template_error;
#[path = "http_ac09_dns_rebinding.rs"]
mod http_ac09_dns_rebinding;
#[path = "http_ac10_concurrency_overhead.rs"]
mod http_ac10_concurrency_overhead;
#[path = "http_ac11_redirect_not_followed.rs"]
mod http_ac11_redirect_not_followed;
#[path = "http_ac12_tool_test.rs"]
mod http_ac12_tool_test;
#[path = "http_ac13_rate_limit.rs"]
mod http_ac13_rate_limit;
#[path = "http_ac14_bridge_envelope_payload.rs"]
mod http_ac14_bridge_envelope_payload;
#[path = "http_ac15_upstream_bridge_declarative.rs"]
mod http_ac15_upstream_bridge_declarative;
#[path = "http_ac16_upstream_bridge_errors.rs"]
mod http_ac16_upstream_bridge_errors;
#[path = "http_ac17_upstream_egress_policy.rs"]
mod http_ac17_upstream_egress_policy;
#[path = "http_ac18_bridge_test_dry_run.rs"]
mod http_ac18_bridge_test_dry_run;
#[path = "infer_ac05_ac06_ac07_http_schema.rs"]
mod infer_ac05_ac06_ac07_http_schema;
#[path = "infer_ac14_latency_budget.rs"]
mod infer_ac14_latency_budget;
#[path = "infer_ac17_no_execution.rs"]
mod infer_ac17_no_execution;
#[path = "kindhonor_ac1_http_kind_honored.rs"]
mod kindhonor_ac1_http_kind_honored;
#[path = "kindhonor_ac3_spec_test_reports_kind.rs"]
mod kindhonor_ac3_spec_test_reports_kind;
#[path = "kindhonor_ac4_initialize_instructions_mention_kind.rs"]
mod kindhonor_ac4_initialize_instructions_mention_kind;
#[path = "kindhonor_ac5_replay_cost_optimizer_shape.rs"]
mod kindhonor_ac5_replay_cost_optimizer_shape;
#[path = "kindhonor_ac6_tools_list_meta_kind.rs"]
mod kindhonor_ac6_tools_list_meta_kind;
#[path = "limits_ac05_signup_burst_atomic.rs"]
mod limits_ac05_signup_burst_atomic;
#[path = "metering_ac01_stripe_customer_id_null_default.rs"]
mod metering_ac01_stripe_customer_id_null_default;
#[path = "metering_ac02_webhook_stores_stripe_customer_id.rs"]
mod metering_ac02_webhook_stores_stripe_customer_id;
#[path = "metering_ac03_checkout_metered_line_item.rs"]
mod metering_ac03_checkout_metered_line_item;
#[path = "metering_ac04_emits_pro_calls_only.rs"]
mod metering_ac04_emits_pro_calls_only;
#[path = "metering_ac05_crash_replay.rs"]
mod metering_ac05_crash_replay;
#[path = "metering_ac06_failure_leaves_state_unmoved.rs"]
mod metering_ac06_failure_leaves_state_unmoved;
#[path = "metering_ac07_batches_cap_at_100.rs"]
mod metering_ac07_batches_cap_at_100;
#[path = "metering_ac08_healthz_meter_lag.rs"]
mod metering_ac08_healthz_meter_lag;
#[path = "metering_ac09_deploy_units_verify.rs"]
mod metering_ac09_deploy_units_verify;
#[path = "metering_ac11_admin_meter_status.rs"]
mod metering_ac11_admin_meter_status;
#[path = "metering_ac12_billing_status_stripe_reported_usage.rs"]
mod metering_ac12_billing_status_stripe_reported_usage;
#[path = "metering_billing_status_emitted_this_month.rs"]
mod metering_billing_status_emitted_this_month;
#[path = "migration_compat_headers.rs"]
mod migration_compat_headers;
#[path = "minimal_ac1_anonymous_ok_only.rs"]
mod minimal_ac1_anonymous_ok_only;
#[path = "minimal_ac2_admin_full_document.rs"]
mod minimal_ac2_admin_full_document;
#[path = "minimal_ac3_wrong_bearer_matches_anonymous.rs"]
mod minimal_ac3_wrong_bearer_matches_anonymous;
#[path = "minimal_ac4_liveness_failure_returns_5xx.rs"]
mod minimal_ac4_liveness_failure_returns_5xx;
#[path = "minimal_ac5_tenant_bearer_gets_anonymous_body.rs"]
mod minimal_ac5_tenant_bearer_gets_anonymous_body;
#[path = "proptest_invariants.rs"]
mod proptest_invariants;
#[path = "provaudit_ac01_synthetic_signup_stamped.rs"]
mod provaudit_ac01_synthetic_signup_stamped;
#[path = "provaudit_ac02_external_signup_stamped.rs"]
mod provaudit_ac02_external_signup_stamped;
#[path = "provaudit_ac03_migration_backfill_counts.rs"]
mod provaudit_ac03_migration_backfill_counts;
#[path = "provaudit_ac04_healthz_split_shape.rs"]
mod provaudit_ac04_healthz_split_shape;
#[path = "provaudit_ac05_admin_audit_log.rs"]
mod provaudit_ac05_admin_audit_log;
#[path = "provaudit_ac06_null_origin_rejected.rs"]
mod provaudit_ac06_null_origin_rejected;
#[path = "provaudit_ac07_ip_class_triage.rs"]
mod provaudit_ac07_ip_class_triage;
#[path = "proxy_ac1_loopback_xff_resolves_signup_source.rs"]
mod proxy_ac1_loopback_xff_resolves_signup_source;
#[path = "proxy_ac2_non_loopback_peer_ignores_header.rs"]
mod proxy_ac2_non_loopback_peer_ignores_header;
#[path = "proxy_ac3_unparseable_header_falls_back.rs"]
mod proxy_ac3_unparseable_header_falls_back;
#[path = "proxy_ac4_rate_limit_keys_on_resolved_address.rs"]
mod proxy_ac4_rate_limit_keys_on_resolved_address;
#[path = "proxy_ac5_signup_event_stores_forwarded_address.rs"]
mod proxy_ac5_signup_event_stores_forwarded_address;
#[path = "proxy_ac6_healthz_distinct_source_ips.rs"]
mod proxy_ac6_healthz_distinct_source_ips;
#[path = "publishfirsttry_ac01_tool_publish_description.rs"]
mod publishfirsttry_ac01_tool_publish_description;
#[path = "publishfirsttry_ac02_structured_error_fields.rs"]
mod publishfirsttry_ac02_structured_error_fields;
#[path = "publishfirsttry_ac07_signup_next.rs"]
mod publishfirsttry_ac07_signup_next;
#[path = "revdebt_ac1_intent_card_pointers_resolve.rs"]
mod revdebt_ac1_intent_card_pointers_resolve;
#[path = "runs_ac05_sync_call_writes_run_row.rs"]
mod runs_ac05_sync_call_writes_run_row;
#[path = "runs_ac07_purge_clears_result.rs"]
mod runs_ac07_purge_clears_result;
#[path = "runs_ac08_tenant_delete_cascades_runs.rs"]
mod runs_ac08_tenant_delete_cascades_runs;
#[path = "runs_ac09_quickstart_and_llms_txt_name_job_limits.rs"]
mod runs_ac09_quickstart_and_llms_txt_name_job_limits;
#[path = "runs_ac10_wait_long_polls.rs"]
mod runs_ac10_wait_long_polls;
#[path = "runs_ac11_admin_runs_reap.rs"]
mod runs_ac11_admin_runs_reap;
#[path = "sandboxready_ac7_conformance_suite.rs"]
mod sandboxready_ac7_conformance_suite;
#[path = "sched_ac10_trigger_fire_manual.rs"]
mod sched_ac10_trigger_fire_manual;
#[path = "sched_ac1_two_firings_visible_in_ledger.rs"]
mod sched_ac1_two_firings_visible_in_ledger;
#[path = "sched_ac2_invalid_cron_names_minute.rs"]
mod sched_ac2_invalid_cron_names_minute;
#[path = "sched_ac3_free_plan_quota_exceeded.rs"]
mod sched_ac3_free_plan_quota_exceeded;
#[path = "sched_ac4_free_plan_interval_too_short.rs"]
mod sched_ac4_free_plan_interval_too_short;
#[path = "sched_ac5_overlap_skips_and_records.rs"]
mod sched_ac5_overlap_skips_and_records;
#[path = "sched_ac6_pause_blocks_resume_allows.rs"]
mod sched_ac6_pause_blocks_resume_allows;
#[path = "sched_ac7_tool_remove_disables_triggers.rs"]
mod sched_ac7_tool_remove_disables_triggers;
#[path = "sched_ac8_healthz_scheduler_fields.rs"]
mod sched_ac8_healthz_scheduler_fields;
#[path = "sched_quickstart_and_usage_report_schedules.rs"]
mod sched_quickstart_and_usage_report_schedules;
