// GENERATED by scripts/gen-test-suites.sh -- do not edit by hand.
// Regenerate with: scripts/gen-test-suites.sh
// Check for drift with: scripts/gen-test-suites.sh --check
//
// This file exists only to give cargo one test BINARY for the files listed
// below; it declares no tests of its own. Every included file keeps its
// original name, path, and test names (nextest's test list, with this
// suite's prefix stripped, is unchanged from before consolidation).
mod common;

#[path = "wasmkind_ac01_echo_component_calls_and_meters.rs"]
mod wasmkind_ac01_echo_component_calls_and_meters;
#[path = "wasmkind_ac02_publish_validation_errors.rs"]
mod wasmkind_ac02_publish_validation_errors;
#[path = "wasmkind_ac03_timeout_and_oom_recover.rs"]
mod wasmkind_ac03_timeout_and_oom_recover;
#[path = "wasmkind_ac05_tool_test_dry_run.rs"]
mod wasmkind_ac05_tool_test_dry_run;
#[path = "wasmkind_ac06_trap_is_structured_and_logged.rs"]
mod wasmkind_ac06_trap_is_structured_and_logged;
#[path = "wasmkind_ac07_docs_llms_and_quickstart_document_wasm.rs"]
mod wasmkind_ac07_docs_llms_and_quickstart_document_wasm;
#[path = "wasmkind_ac08_cache_reuses_compiled_artifact.rs"]
mod wasmkind_ac08_cache_reuses_compiled_artifact;
#[path = "wasmkind_ac09_healthz_reports_wasm_runtime.rs"]
mod wasmkind_ac09_healthz_reports_wasm_runtime;
#[path = "wasmkind_ac10_declared_output_promotion_matches_python.rs"]
mod wasmkind_ac10_declared_output_promotion_matches_python;
