// GENERATED by scripts/gen-test-suites.sh -- do not edit by hand.
// Regenerate with: scripts/gen-test-suites.sh
// Check for drift with: scripts/gen-test-suites.sh --check
//
// This file exists only to give cargo one test BINARY for the files listed
// below; it declares no tests of its own. Every included file keeps its
// original name, path, and test names (nextest's test list, with this
// suite's prefix stripped, is unchanged from before consolidation).
mod common;
mod ci_sandbox_support;
#[path = "support/host.rs"]
#[allow(dead_code)]
mod host;
#[path = "support/lanecov.rs"]
mod lanecov;

#[path = "ac01_extended_gates_prd_path_resolves_and_matches_card.rs"]
mod ac01_extended_gates_prd_path_resolves_and_matches_card;
#[path = "ac01_unauthenticated_lists_signup.rs"]
mod ac01_unauthenticated_lists_signup;
#[path = "ac02_signup_creates_hashed_tenant.rs"]
mod ac02_signup_creates_hashed_tenant;
#[path = "ac03_tenant_lists_control_plane_only.rs"]
mod ac03_tenant_lists_control_plane_only;
#[path = "ac04_publish_list_and_call.rs"]
mod ac04_publish_list_and_call;
#[path = "ac05_cross_tenant_isolation.rs"]
mod ac05_cross_tenant_isolation;
#[path = "ac06_remove_tool.rs"]
mod ac06_remove_tool;
#[path = "ac07_usage_metering.rs"]
mod ac07_usage_metering;
#[path = "ac08_admin_disable_and_forbidden.rs"]
mod ac08_admin_disable_and_forbidden;
#[path = "ac09_signup_rate_limit.rs"]
mod ac09_signup_rate_limit;
#[path = "ac10_publish_validation_errors.rs"]
mod ac10_publish_validation_errors;
#[path = "ac11_load_smoke.rs"]
mod ac11_load_smoke;
#[path = "ac12_preflight.rs"]
mod ac12_preflight;
#[path = "ac13_mcp_name_mismatch_metering.rs"]
mod ac13_mcp_name_mismatch_metering;
#[path = "ac14_storage_unwritable.rs"]
mod ac14_storage_unwritable;
#[path = "ac15_call_timeout.rs"]
mod ac15_call_timeout;
#[path = "ac16_request_body_too_large.rs"]
mod ac16_request_body_too_large;
#[path = "ac18_tools_list_ttl.rs"]
mod ac18_tools_list_ttl;
#[path = "ac19_registry_publish.rs"]
mod ac19_registry_publish;
#[path = "agentdir_ac01_ac02_ac03_ac04_identity_and_lookup.rs"]
mod agentdir_ac01_ac02_ac03_ac04_identity_and_lookup;
#[path = "agentdir_ac05_ac06_search.rs"]
mod agentdir_ac05_ac06_search;
#[path = "agentdir_ac07_ac09_ac10_lifecycle.rs"]
mod agentdir_ac07_ac09_ac10_lifecycle;
#[path = "agentdir_ac08_lookup_latency.rs"]
mod agentdir_ac08_lookup_latency;
#[path = "attrib_ac1_loopback_signup_unstamped.rs"]
mod attrib_ac1_loopback_signup_unstamped;
#[path = "attrib_ac2_clientinfo_captured.rs"]
mod attrib_ac2_clientinfo_captured;
#[path = "attrib_ac3_backfill_migration.rs"]
mod attrib_ac3_backfill_migration;
#[path = "attrib_ac4_external_signup_counts_real.rs"]
mod attrib_ac4_external_signup_counts_real;
#[path = "attrib_ac5_funnel_report.rs"]
mod attrib_ac5_funnel_report;
#[path = "attrib_ac6_whoami_source_class.rs"]
mod attrib_ac6_whoami_source_class;
#[path = "attribdefault_ac1_bare_signup_client_info_is_null.rs"]
mod attribdefault_ac1_bare_signup_client_info_is_null;
#[path = "attribdefault_ac2_real_clientinfo_still_captured.rs"]
mod attribdefault_ac2_real_clientinfo_still_captured;
#[path = "autherr_ac1_tenant_key_missing.rs"]
mod autherr_ac1_tenant_key_missing;
#[path = "autherr_ac2_tenant_key_invalid.rs"]
mod autherr_ac2_tenant_key_invalid;
#[path = "autherr_ac3_disabled_tenant_key_invalid.rs"]
mod autherr_ac3_disabled_tenant_key_invalid;
#[path = "autherr_ac4_bearer_invalid_unchanged.rs"]
mod autherr_ac4_bearer_invalid_unchanged;
#[path = "autherr_ac5_instructions_mention_codes.rs"]
mod autherr_ac5_instructions_mention_codes;
#[path = "billing_ac01_plans_toml_and_billing_plans.rs"]
mod billing_ac01_plans_toml_and_billing_plans;
#[path = "billing_ac02_publish_quota_exceeded.rs"]
mod billing_ac02_publish_quota_exceeded;
#[path = "billing_ac03_call_time_quota_exceeded.rs"]
mod billing_ac03_call_time_quota_exceeded;
#[path = "billing_ac04_checkout_unavailable_no_keys.rs"]
mod billing_ac04_checkout_unavailable_no_keys;
#[path = "billing_ac05_checkout_returns_session.rs"]
mod billing_ac05_checkout_returns_session;
#[path = "billing_ac06_webhook_checkout_completed_idempotent.rs"]
mod billing_ac06_webhook_checkout_completed_idempotent;
#[path = "billing_ac07_webhook_bad_signature_or_stale.rs"]
mod billing_ac07_webhook_bad_signature_or_stale;
#[path = "billing_ac08_webhook_subscription_deleted_downgrades.rs"]
mod billing_ac08_webhook_subscription_deleted_downgrades;
#[path = "billing_ac09_admin_billing_ledger_filters.rs"]
mod billing_ac09_admin_billing_ledger_filters;
#[path = "billing_ac10_webhook_mode_mismatch.rs"]
mod billing_ac10_webhook_mode_mismatch;
#[path = "billing_ac11_healthz_paying_tenants.rs"]
mod billing_ac11_healthz_paying_tenants;
#[path = "billing_ac13_checkout_reuse.rs"]
mod billing_ac13_checkout_reuse;
#[path = "channel_ac01_group_open_and_broadcast_read.rs"]
mod channel_ac01_group_open_and_broadcast_read;
#[path = "channel_ac02_non_member_channel_not_found.rs"]
mod channel_ac02_non_member_channel_not_found;
#[path = "channel_ac03_ack_resumes_from_stored_cursor.rs"]
mod channel_ac03_ack_resumes_from_stored_cursor;
#[path = "channel_ac04_concurrent_posts_no_dups_no_gaps.rs"]
mod channel_ac04_concurrent_posts_no_dups_no_gaps;
#[path = "channel_ac05_removed_member_loses_access_posts_remain.rs"]
mod channel_ac05_removed_member_loses_access_posts_remain;
#[path = "channel_ac06_message_trigger_fires_per_member_not_poster.rs"]
mod channel_ac06_message_trigger_fires_per_member_not_poster;
#[path = "channel_ac07_post_quota_120_per_hour.rs"]
mod channel_ac07_post_quota_120_per_hour;
#[path = "channel_ac08_retention_tick_purges_old_posts.rs"]
mod channel_ac08_retention_tick_purges_old_posts;
#[path = "channel_ac09_close_blocks_posts_not_reads.rs"]
mod channel_ac09_close_blocks_posts_not_reads;
#[path = "channel_ac10_freeze_blocks_posts_unfreeze_restores.rs"]
mod channel_ac10_freeze_blocks_posts_unfreeze_restores;
#[path = "checkcompat_ac02_ac03.rs"]
mod checkcompat_ac02_ac03;
#[path = "checkcompat_race_ac01_previous_up_within_1s.rs"]
mod checkcompat_race_ac01_previous_up_within_1s;
#[path = "checkcompat_race_ac03_inherited_listener_token_matches.rs"]
mod checkcompat_race_ac03_inherited_listener_token_matches;
#[path = "checkcompat_race_ac04_no_token_header_when_unset.rs"]
mod checkcompat_race_ac04_no_token_header_when_unset;
#[path = "checkcompat_race_ac05_stress_no_port_collisions.rs"]
mod checkcompat_race_ac05_stress_no_port_collisions;
#[path = "checkcompat_race_ac06_explicit_bind_still_enforces_token.rs"]
mod checkcompat_race_ac06_explicit_bind_still_enforces_token;
#[path = "checkcompat_race_ac07_suite_green_and_clippy_clean.rs"]
mod checkcompat_race_ac07_suite_green_and_clippy_clean;
#[path = "checkcompat_race_ac08_deferral_is_justified.rs"]
mod checkcompat_race_ac08_deferral_is_justified;
#[path = "ci_sandbox_ac01_workflow_executes_sandbox_suites.rs"]
mod ci_sandbox_ac01_workflow_executes_sandbox_suites;
#[path = "ci_sandbox_ac03_incapable_in_ci_skips_and_fails_job.rs"]
mod ci_sandbox_ac03_incapable_in_ci_skips_and_fails_job;
#[path = "ci_sandbox_ac04_incapable_outside_ci_fails_loudly.rs"]
mod ci_sandbox_ac04_incapable_outside_ci_fails_loudly;
#[path = "ci_sandbox_ac06_sandbox_suites_run_as_a_parallel_job.rs"]
mod ci_sandbox_ac06_sandbox_suites_run_as_a_parallel_job;
#[path = "classify_ac9_is_within_proptest.rs"]
mod classify_ac9_is_within_proptest;
#[path = "compat_ac01_ac02_ac03_cache_fields.rs"]
mod compat_ac01_ac02_ac03_cache_fields;
#[path = "compat_ac04_ac05_admin_and_tenant_cache_fields.rs"]
mod compat_ac04_ac05_admin_and_tenant_cache_fields;
#[path = "compat_ac08_ac09_ac10_advertised_version.rs"]
mod compat_ac08_ac09_ac10_advertised_version;
#[path = "compat_ac11_ac12_claude_sdk_replay.rs"]
mod compat_ac11_ac12_claude_sdk_replay;
#[path = "compose_ac3_self_call_refused.rs"]
mod compose_ac3_self_call_refused;
#[path = "compose_ac4_depth_exceeded.rs"]
mod compose_ac4_depth_exceeded;
#[path = "compose_ac5_three_step_chain_prev_mapping.rs"]
mod compose_ac5_three_step_chain_prev_mapping;
#[path = "compose_ac6_mapping_missing.rs"]
mod compose_ac6_mapping_missing;
#[path = "compose_ac7_on_error_continue.rs"]
mod compose_ac7_on_error_continue;
#[path = "compose_ac8_tool_test_dry_run.rs"]
mod compose_ac8_tool_test_dry_run;
#[path = "consent_ac01_ac02_ac03_ac04_contact_lifecycle.rs"]
mod consent_ac01_ac02_ac03_ac04_contact_lifecycle;
#[path = "consent_ac05_ac06_ac07_ac08_ac09_ac10_mute_urgent_block_delete_inbox.rs"]
mod consent_ac05_ac06_ac07_ac08_ac09_ac10_mute_urgent_block_delete_inbox;
#[path = "envelope_ac1_http_declared_output_promoted.rs"]
mod envelope_ac1_http_declared_output_promoted;
#[path = "envelope_ac4_tool_test_reports_missing_declared_output.rs"]
mod envelope_ac4_tool_test_reports_missing_declared_output;
#[path = "firstcall_ac6_outcome_metering.rs"]
mod firstcall_ac6_outcome_metering;
#[path = "gatedebt_4f1112d_ac4_no_test_reads_gate_receipts.rs"]
mod gatedebt_4f1112d_ac4_no_test_reads_gate_receipts;
#[path = "gatedebt_4f1112d_ac5_no_flake_audit_selftest_names.rs"]
mod gatedebt_4f1112d_ac5_no_flake_audit_selftest_names;
#[path = "handoff_ac01_signup_returns_token_and_no_key.rs"]
mod handoff_ac01_signup_returns_token_and_no_key;
#[path = "handoff_ac02_redeem_single_use_and_expiry.rs"]
mod handoff_ac02_redeem_single_use_and_expiry;
#[path = "handoff_ac03_key_rotate_invalidates_old_key.rs"]
mod handoff_ac03_key_rotate_invalidates_old_key;
#[path = "handoff_ac04_full_two_context_flow.rs"]
mod handoff_ac04_full_two_context_flow;
#[path = "handoff_ac05_raw_signup_still_works_unchanged.rs"]
mod handoff_ac05_raw_signup_still_works_unchanged;
#[path = "handoff_ac06_errors_never_echo_token_or_key.rs"]
mod handoff_ac06_errors_never_echo_token_or_key;
#[path = "handoff_ac07_docs_recommend_handoff_flow.rs"]
mod handoff_ac07_docs_recommend_handoff_flow;
#[path = "handoff_ac08_whoami_reports_key_age_and_rotation.rs"]
mod handoff_ac08_whoami_reports_key_age_and_rotation;
#[path = "hooks_ac10_healthz_event_counters.rs"]
mod hooks_ac10_healthz_event_counters;
#[path = "hooks_ac11_dedupe_header_idempotent.rs"]
mod hooks_ac11_dedupe_header_idempotent;
#[path = "hooks_ac1_hmac_sha256_valid_signature_runs.rs"]
mod hooks_ac1_hmac_sha256_valid_signature_runs;
#[path = "hooks_ac2_wrong_signature_401_no_run.rs"]
mod hooks_ac2_wrong_signature_401_no_run;
#[path = "hooks_ac3_stripe_style_stale_timestamp_401.rs"]
mod hooks_ac3_stripe_style_stale_timestamp_401;
#[path = "hooks_ac4_none_scheme_requires_allow_unverified.rs"]
mod hooks_ac4_none_scheme_requires_allow_unverified;
#[path = "hooks_ac5_rate_limit_429.rs"]
mod hooks_ac5_rate_limit_429;
#[path = "hooks_ac6_body_too_large_413.rs"]
mod hooks_ac6_body_too_large_413;
#[path = "hooks_ac7_trigger_test_creates_marked_run.rs"]
mod hooks_ac7_trigger_test_creates_marked_run;
#[path = "hooks_ac8_trigger_replay_new_run_trigger_ref.rs"]
mod hooks_ac8_trigger_replay_new_run_trigger_ref;
#[path = "hooks_ac9_paused_trigger_404.rs"]
mod hooks_ac9_paused_trigger_404;
#[path = "http_ac01_secret_redaction.rs"]
mod http_ac01_secret_redaction;
#[path = "http_ac02_publish_ssrf_literal.rs"]
mod http_ac02_publish_ssrf_literal;
#[path = "http_ac03_publish_secret_missing.rs"]
mod http_ac03_publish_secret_missing;
#[path = "http_ac04_args_invalid.rs"]
mod http_ac04_args_invalid;
#[path = "http_ac05_upstream_429_retry_after.rs"]
mod http_ac05_upstream_429_retry_after;
#[path = "http_ac06_upstream_timeout.rs"]
mod http_ac06_upstream_timeout;
#[path = "http_ac07_response_too_large.rs"]
mod http_ac07_response_too_large;
#[path = "http_ac08_template_error.rs"]
mod http_ac08_template_error;
#[path = "http_ac09_dns_rebinding.rs"]
mod http_ac09_dns_rebinding;
#[path = "http_ac10_concurrency_overhead.rs"]
mod http_ac10_concurrency_overhead;
#[path = "http_ac11_redirect_not_followed.rs"]
mod http_ac11_redirect_not_followed;
#[path = "http_ac12_tool_test.rs"]
mod http_ac12_tool_test;
#[path = "http_ac13_rate_limit.rs"]
mod http_ac13_rate_limit;
#[path = "http_ac14_bridge_envelope_payload.rs"]
mod http_ac14_bridge_envelope_payload;
#[path = "http_ac15_upstream_bridge_declarative.rs"]
mod http_ac15_upstream_bridge_declarative;
#[path = "http_ac16_upstream_bridge_errors.rs"]
mod http_ac16_upstream_bridge_errors;
#[path = "http_ac17_upstream_egress_policy.rs"]
mod http_ac17_upstream_egress_policy;
#[path = "http_ac18_bridge_test_dry_run.rs"]
mod http_ac18_bridge_test_dry_run;
#[path = "infer_ac05_ac06_ac07_http_schema.rs"]
mod infer_ac05_ac06_ac07_http_schema;
#[path = "infer_ac14_latency_budget.rs"]
mod infer_ac14_latency_budget;
#[path = "infer_ac17_no_execution.rs"]
mod infer_ac17_no_execution;
#[path = "kindhonor_ac1_http_kind_honored.rs"]
mod kindhonor_ac1_http_kind_honored;
#[path = "kindhonor_ac3_spec_test_reports_kind.rs"]
mod kindhonor_ac3_spec_test_reports_kind;
#[path = "kindhonor_ac4_initialize_instructions_mention_kind.rs"]
mod kindhonor_ac4_initialize_instructions_mention_kind;
#[path = "kindhonor_ac5_replay_cost_optimizer_shape.rs"]
mod kindhonor_ac5_replay_cost_optimizer_shape;
#[path = "kindhonor_ac6_tools_list_meta_kind.rs"]
mod kindhonor_ac6_tools_list_meta_kind;
#[path = "lanecov_ac01_every_tracked_path_routes.rs"]
mod lanecov_ac01_every_tracked_path_routes;
#[path = "lanecov_ac02_coverage_test_is_actually_run.rs"]
mod lanecov_ac02_coverage_test_is_actually_run;
#[path = "lanecov_ac03_unrouted_path_is_named.rs"]
mod lanecov_ac03_unrouted_path_is_named;
#[path = "lanecov_ac04_existing_lanes_unchanged.rs"]
mod lanecov_ac04_existing_lanes_unchanged;
#[path = "lanecov_ac06_malformed_lane_fails_naming_it.rs"]
mod lanecov_ac06_malformed_lane_fails_naming_it;
#[path = "lanecov_ac07_docs_document_adding_a_lane.rs"]
mod lanecov_ac07_docs_document_adding_a_lane;
#[path = "limits_ac05_signup_burst_atomic.rs"]
mod limits_ac05_signup_burst_atomic;
#[path = "mcphost_data_retention_ac01_calls_prune_by_window.rs"]
mod mcphost_data_retention_ac01_calls_prune_by_window;
#[path = "mcphost_data_retention_ac02_metering_rows_survive_window.rs"]
mod mcphost_data_retention_ac02_metering_rows_survive_window;
#[path = "mcphost_data_retention_ac03_untracked_table_unchanged.rs"]
mod mcphost_data_retention_ac03_untracked_table_unchanged;
#[path = "mcphost_data_retention_ac04_batched_prune_no_lock_errors.rs"]
mod mcphost_data_retention_ac04_batched_prune_no_lock_errors;
#[path = "mcphost_data_retention_ac05_admin_usage_reports_size_and_last_prune.rs"]
mod mcphost_data_retention_ac05_admin_usage_reports_size_and_last_prune;
#[path = "mcphost_data_retention_ac06_disk_floor_refuses_writes.rs"]
mod mcphost_data_retention_ac06_disk_floor_refuses_writes;
#[path = "mcphost_data_retention_ac07_automatic_prune_keeps_last_prune_fresh.rs"]
mod mcphost_data_retention_ac07_automatic_prune_keeps_last_prune_fresh;
#[path = "mcphost_data_retention_ac08_host_usage_lists_retention_windows.rs"]
mod mcphost_data_retention_ac08_host_usage_lists_retention_windows;
#[path = "mcphost_data_retention_ac09_prune_error_sets_last_prune_ok_false.rs"]
mod mcphost_data_retention_ac09_prune_error_sets_last_prune_ok_false;
#[path = "mcphost_data_retention_ac10_admin_prune_now_runs_one_cycle.rs"]
mod mcphost_data_retention_ac10_admin_prune_now_runs_one_cycle;
#[path = "mcphost_database_in_a_minute_ac01_llms_txt_section.rs"]
mod mcphost_database_in_a_minute_ac01_llms_txt_section;
#[path = "mcphost_database_in_a_minute_ac08_live_test_skipped_without_env.rs"]
mod mcphost_database_in_a_minute_ac08_live_test_skipped_without_env;
#[path = "mcphost_host_tool_deprecation_ac01_contract_dump_deterministic.rs"]
mod mcphost_host_tool_deprecation_ac01_contract_dump_deterministic;
#[path = "mcphost_host_tool_deprecation_ac02_removed_field_without_deprecation_fails.rs"]
mod mcphost_host_tool_deprecation_ac02_removed_field_without_deprecation_fails;
#[path = "mcphost_host_tool_deprecation_ac03_deprecation_entry_marks_tools_list.rs"]
mod mcphost_host_tool_deprecation_ac03_deprecation_entry_marks_tools_list;
#[path = "mcphost_host_tool_deprecation_ac04_deprecated_field_call_envelope.rs"]
mod mcphost_host_tool_deprecation_ac04_deprecated_field_call_envelope;
#[path = "mcphost_host_tool_deprecation_ac05_removal_gated_on_sunset.rs"]
mod mcphost_host_tool_deprecation_ac05_removal_gated_on_sunset;
#[path = "mcphost_host_tool_deprecation_ac06_changelog_lists_additions.rs"]
mod mcphost_host_tool_deprecation_ac06_changelog_lists_additions;
#[path = "mcphost_host_tool_deprecation_ac07_whoami_contract_version.rs"]
mod mcphost_host_tool_deprecation_ac07_whoami_contract_version;
#[path = "mcphost_host_tool_deprecation_ac08_llms_txt_links_contract.rs"]
mod mcphost_host_tool_deprecation_ac08_llms_txt_links_contract;
#[path = "mcphost_sandbox_egress_allowlist_ac05_none_network_unshare_all.rs"]
mod mcphost_sandbox_egress_allowlist_ac05_none_network_unshare_all;
#[path = "mcphost_sandbox_egress_allowlist_ac09_readme_documents_proxy_and_deny_list.rs"]
mod mcphost_sandbox_egress_allowlist_ac09_readme_documents_proxy_and_deny_list;
#[path = "mcphost_share_a_tool_not_a_key_ac01_llms_txt_section.rs"]
mod mcphost_share_a_tool_not_a_key_ac01_llms_txt_section;
#[path = "mcphost_share_a_tool_not_a_key_ac02_caller_call_returns_upstream_response.rs"]
mod mcphost_share_a_tool_not_a_key_ac02_caller_call_returns_upstream_response;
#[path = "mcphost_share_a_tool_not_a_key_ac03_caller_never_sees_secret.rs"]
mod mcphost_share_a_tool_not_a_key_ac03_caller_never_sees_secret;
#[path = "mcphost_share_a_tool_not_a_key_ac04_group_remove_revokes_caller.rs"]
mod mcphost_share_a_tool_not_a_key_ac04_group_remove_revokes_caller;
#[path = "mcphost_share_a_tool_not_a_key_ac05_signup_events_source_tagged.rs"]
mod mcphost_share_a_tool_not_a_key_ac05_signup_events_source_tagged;
#[path = "mcphost_share_a_tool_not_a_key_ac07_synthorg_task_five_completions.rs"]
mod mcphost_share_a_tool_not_a_key_ac07_synthorg_task_five_completions;
#[path = "mcphost_share_a_tool_not_a_key_ac08_live_test_skipped_without_env.rs"]
mod mcphost_share_a_tool_not_a_key_ac08_live_test_skipped_without_env;
#[path = "mcphost_share_a_tool_not_a_key_ac09_public_variant_states_default_reason.rs"]
mod mcphost_share_a_tool_not_a_key_ac09_public_variant_states_default_reason;
#[path = "mcphost_signup_kill_switch_and_source_ac01_source_echoed_and_stored.rs"]
mod mcphost_signup_kill_switch_and_source_ac01_source_echoed_and_stored;
#[path = "mcphost_signup_kill_switch_and_source_ac02_no_source_is_null.rs"]
mod mcphost_signup_kill_switch_and_source_ac02_no_source_is_null;
#[path = "mcphost_signup_kill_switch_and_source_ac03_invalid_source_rejected.rs"]
mod mcphost_signup_kill_switch_and_source_ac03_invalid_source_rejected;
#[path = "mcphost_signup_kill_switch_and_source_ac04_pause_file_stops_and_resumes_signups.rs"]
mod mcphost_signup_kill_switch_and_source_ac04_pause_file_stops_and_resumes_signups;
#[path = "mcphost_signup_kill_switch_and_source_ac05_pause_does_not_affect_authenticated_calls.rs"]
mod mcphost_signup_kill_switch_and_source_ac05_pause_does_not_affect_authenticated_calls;
#[path = "mcphost_signup_kill_switch_and_source_ac06_healthz_signups_by_source.rs"]
mod mcphost_signup_kill_switch_and_source_ac06_healthz_signups_by_source;
#[path = "mcphost_signup_kill_switch_and_source_ac07_healthz_reports_paused.rs"]
mod mcphost_signup_kill_switch_and_source_ac07_healthz_reports_paused;
#[path = "mcphost_signup_kill_switch_and_source_ac08_concurrent_burst_with_pause_toggle.rs"]
mod mcphost_signup_kill_switch_and_source_ac08_concurrent_burst_with_pause_toggle;
#[path = "mcphost_signup_kill_switch_and_source_ac09_llms_txt_documents_source.rs"]
mod mcphost_signup_kill_switch_and_source_ac09_llms_txt_documents_source;
#[path = "mcphost_signup_kill_switch_and_source_ac10_until_line_bounds_retry_after.rs"]
mod mcphost_signup_kill_switch_and_source_ac10_until_line_bounds_retry_after;
#[path = "mcphost_team_memory_ac01_llms_txt_section.rs"]
mod mcphost_team_memory_ac01_llms_txt_section;
#[path = "mcphost_team_memory_ac08_live_test_skipped_without_env.rs"]
mod mcphost_team_memory_ac08_live_test_skipped_without_env;
#[path = "mcphost_tenant_data_export_ac01_archive_contents.rs"]
mod mcphost_tenant_data_export_ac01_archive_contents;
#[path = "mcphost_tenant_data_export_ac02_signed_url_expiry.rs"]
mod mcphost_tenant_data_export_ac02_signed_url_expiry;
#[path = "mcphost_tenant_data_export_ac03_dedupe_in_progress.rs"]
mod mcphost_tenant_data_export_ac03_dedupe_in_progress;
#[path = "mcphost_tenant_data_export_ac04_live_export_trailer.rs"]
mod mcphost_tenant_data_export_ac04_live_export_trailer;
#[path = "mcphost_tenant_data_export_ac05_manifest_validates_publish_schema.rs"]
mod mcphost_tenant_data_export_ac05_manifest_validates_publish_schema;
#[path = "mcphost_tenant_data_export_ac06_tools_subset.rs"]
mod mcphost_tenant_data_export_ac06_tools_subset;
#[path = "mcphost_tenant_data_export_ac07_admin_usage_exports_today.rs"]
mod mcphost_tenant_data_export_ac07_admin_usage_exports_today;
#[path = "mcphost_tool_versions_ac01_publish_twice_lists_two_versions.rs"]
mod mcphost_tool_versions_ac01_publish_twice_lists_two_versions;
#[path = "mcphost_tool_versions_ac02_rollback_runs_old_source.rs"]
mod mcphost_tool_versions_ac02_rollback_runs_old_source;
#[path = "mcphost_tool_versions_ac03_free_plan_retains_five_versions.rs"]
mod mcphost_tool_versions_ac03_free_plan_retains_five_versions;
#[path = "mcphost_tool_versions_ac04_rollback_unknown_version_names_range.rs"]
mod mcphost_tool_versions_ac04_rollback_unknown_version_names_range;
#[path = "mcphost_tool_versions_ac05_pinned_caller_survives_republish.rs"]
mod mcphost_tool_versions_ac05_pinned_caller_survives_republish;
#[path = "mcphost_tool_versions_ac07_sharer_sees_version_changed_once.rs"]
mod mcphost_tool_versions_ac07_sharer_sees_version_changed_once;
#[path = "mcphost_tool_versions_ac08_remove_clears_all_versions.rs"]
mod mcphost_tool_versions_ac08_remove_clears_all_versions;
#[path = "mcphost_tool_versions_ac09_diff_returns_unified_diff.rs"]
mod mcphost_tool_versions_ac09_diff_returns_unified_diff;
#[path = "mcphost_uptime_probes_ac01_llms_txt_section.rs"]
mod mcphost_uptime_probes_ac01_llms_txt_section;
#[path = "mcphost_uptime_probes_ac08_live_test_skipped_without_env.rs"]
mod mcphost_uptime_probes_ac08_live_test_skipped_without_env;
#[path = "mcphost_webhook_inbox_ac01_set_returns_url_and_secret_get_omits_secret.rs"]
mod mcphost_webhook_inbox_ac01_set_returns_url_and_secret_get_omits_secret;
#[path = "mcphost_webhook_inbox_ac02_signed_post_stores_row_and_fires_run.rs"]
mod mcphost_webhook_inbox_ac02_signed_post_stores_row_and_fires_run;
#[path = "mcphost_webhook_inbox_ac03_unsigned_or_wrong_signature_401_no_row.rs"]
mod mcphost_webhook_inbox_ac03_unsigned_or_wrong_signature_401_no_row;
#[path = "mcphost_webhook_inbox_ac04_unknown_id_404_empty_body.rs"]
mod mcphost_webhook_inbox_ac04_unknown_id_404_empty_body;
#[path = "mcphost_webhook_inbox_ac05_oversized_body_413_no_row.rs"]
mod mcphost_webhook_inbox_ac05_oversized_body_413_no_row;
#[path = "mcphost_webhook_inbox_ac06_paused_stores_no_run_replay_fires_once.rs"]
mod mcphost_webhook_inbox_ac06_paused_stores_no_run_replay_fires_once;
#[path = "mcphost_webhook_inbox_ac07_repeated_delivery_id_dedupes_row.rs"]
mod mcphost_webhook_inbox_ac07_repeated_delivery_id_dedupes_row;
#[path = "mcphost_webhook_inbox_ac08_free_tenant_three_schedules_webhook_refused.rs"]
mod mcphost_webhook_inbox_ac08_free_tenant_three_schedules_webhook_refused;
#[path = "mcphost_webhook_inbox_ac09_concurrent_deliveries_all_land.rs"]
mod mcphost_webhook_inbox_ac09_concurrent_deliveries_all_land;
#[path = "mcphost_webhook_inbox_ac11_trigger_test_stores_and_fires_synthetic_delivery.rs"]
mod mcphost_webhook_inbox_ac11_trigger_test_stores_and_fires_synthetic_delivery;
#[path = "mcphost_webhook_inbox_ac12_stripe_verify_scheme_accepted.rs"]
mod mcphost_webhook_inbox_ac12_stripe_verify_scheme_accepted;
#[path = "meshops_ac01_stats_real_vs_synthetic_volume.rs"]
mod meshops_ac01_stats_real_vs_synthetic_volume;
#[path = "meshops_ac02_threads_no_bodies.rs"]
mod meshops_ac02_threads_no_bodies;
#[path = "meshops_ac03_thread_read_bodies_and_audit.rs"]
mod meshops_ac03_thread_read_bodies_and_audit;
#[path = "meshops_ac04_freeze_blocks_sends_not_reads_or_tools.rs"]
mod meshops_ac04_freeze_blocks_sends_not_reads_or_tools;
#[path = "meshops_ac05_unfreeze_restores_sending.rs"]
mod meshops_ac05_unfreeze_restores_sending;
#[path = "meshops_ac06_purge_dry_run_then_real.rs"]
mod meshops_ac06_purge_dry_run_then_real;
#[path = "meshops_ac07_tenant_delete_cascade_across_mesh_tables.rs"]
mod meshops_ac07_tenant_delete_cascade_across_mesh_tables;
#[path = "meshops_ac08_healthz_mesh_counters.rs"]
mod meshops_ac08_healthz_mesh_counters;
#[path = "meshops_ac09_stats_refusals_by_code_per_sender.rs"]
mod meshops_ac09_stats_refusals_by_code_per_sender;
#[path = "metering_ac01_stripe_customer_id_null_default.rs"]
mod metering_ac01_stripe_customer_id_null_default;
#[path = "metering_ac02_webhook_stores_stripe_customer_id.rs"]
mod metering_ac02_webhook_stores_stripe_customer_id;
#[path = "metering_ac03_checkout_metered_line_item.rs"]
mod metering_ac03_checkout_metered_line_item;
#[path = "metering_ac04_emits_pro_calls_only.rs"]
mod metering_ac04_emits_pro_calls_only;
#[path = "metering_ac05_crash_replay.rs"]
mod metering_ac05_crash_replay;
#[path = "metering_ac06_failure_leaves_state_unmoved.rs"]
mod metering_ac06_failure_leaves_state_unmoved;
#[path = "metering_ac07_batches_cap_at_100.rs"]
mod metering_ac07_batches_cap_at_100;
#[path = "metering_ac08_healthz_meter_lag.rs"]
mod metering_ac08_healthz_meter_lag;
#[path = "metering_ac09_deploy_units_verify.rs"]
mod metering_ac09_deploy_units_verify;
#[path = "metering_ac11_admin_meter_status.rs"]
mod metering_ac11_admin_meter_status;
#[path = "metering_ac12_billing_status_stripe_reported_usage.rs"]
mod metering_ac12_billing_status_stripe_reported_usage;
#[path = "metering_billing_status_emitted_this_month.rs"]
mod metering_billing_status_emitted_this_month;
#[path = "migration_compat_headers.rs"]
mod migration_compat_headers;
#[path = "minimal_ac1_anonymous_ok_only.rs"]
mod minimal_ac1_anonymous_ok_only;
#[path = "minimal_ac2_admin_full_document.rs"]
mod minimal_ac2_admin_full_document;
#[path = "minimal_ac3_wrong_bearer_matches_anonymous.rs"]
mod minimal_ac3_wrong_bearer_matches_anonymous;
#[path = "minimal_ac4_liveness_failure_returns_5xx.rs"]
mod minimal_ac4_liveness_failure_returns_5xx;
#[path = "minimal_ac5_tenant_bearer_gets_anonymous_body.rs"]
mod minimal_ac5_tenant_bearer_gets_anonymous_body;
#[path = "msg_ac01_send_reaches_inbox.rs"]
mod msg_ac01_send_reaches_inbox;
#[path = "msg_ac02_reply_appends_next_seq.rs"]
mod msg_ac02_reply_appends_next_seq;
#[path = "msg_ac03_non_participant_thread_not_found.rs"]
mod msg_ac03_non_participant_thread_not_found;
#[path = "msg_ac04_dedupe_key.rs"]
mod msg_ac04_dedupe_key;
#[path = "msg_ac05_block.rs"]
mod msg_ac05_block;
#[path = "msg_ac06_inbox_cursor_concurrent.rs"]
mod msg_ac06_inbox_cursor_concurrent;
#[path = "msg_ac07_forged_from.rs"]
mod msg_ac07_forged_from;
#[path = "msg_ac08_contact_policy_closed.rs"]
mod msg_ac08_contact_policy_closed;
#[path = "msg_ac09_msgs_per_hour_quota.rs"]
mod msg_ac09_msgs_per_hour_quota;
#[path = "msg_ac10_body_and_recipients_quota.rs"]
mod msg_ac10_body_and_recipients_quota;
#[path = "msg_ac11_tenant_delete_cascade.rs"]
mod msg_ac11_tenant_delete_cascade;
#[path = "msg_ac12_send_latency.rs"]
mod msg_ac12_send_latency;
#[path = "msg_ac13_unread_only.rs"]
mod msg_ac13_unread_only;
#[path = "msg_ac14_thread_continuation.rs"]
mod msg_ac14_thread_continuation;
#[path = "msg_regr01_dedupe_hit_preserves_refused.rs"]
mod msg_regr01_dedupe_hit_preserves_refused;
#[path = "proptest_invariants.rs"]
mod proptest_invariants;
#[path = "provaudit_ac01_synthetic_signup_stamped.rs"]
mod provaudit_ac01_synthetic_signup_stamped;
#[path = "provaudit_ac02_external_signup_stamped.rs"]
mod provaudit_ac02_external_signup_stamped;
#[path = "provaudit_ac03_migration_backfill_counts.rs"]
mod provaudit_ac03_migration_backfill_counts;
#[path = "provaudit_ac04_healthz_split_shape.rs"]
mod provaudit_ac04_healthz_split_shape;
#[path = "provaudit_ac05_admin_audit_log.rs"]
mod provaudit_ac05_admin_audit_log;
#[path = "provaudit_ac06_null_origin_rejected.rs"]
mod provaudit_ac06_null_origin_rejected;
#[path = "provaudit_ac07_ip_class_triage.rs"]
mod provaudit_ac07_ip_class_triage;
#[path = "proxy_ac1_loopback_xff_resolves_signup_source.rs"]
mod proxy_ac1_loopback_xff_resolves_signup_source;
#[path = "proxy_ac2_non_loopback_peer_ignores_header.rs"]
mod proxy_ac2_non_loopback_peer_ignores_header;
#[path = "proxy_ac3_unparseable_header_falls_back.rs"]
mod proxy_ac3_unparseable_header_falls_back;
#[path = "proxy_ac4_rate_limit_keys_on_resolved_address.rs"]
mod proxy_ac4_rate_limit_keys_on_resolved_address;
#[path = "proxy_ac5_signup_event_stores_forwarded_address.rs"]
mod proxy_ac5_signup_event_stores_forwarded_address;
#[path = "proxy_ac6_healthz_distinct_source_ips.rs"]
mod proxy_ac6_healthz_distinct_source_ips;
#[path = "publishfirsttry_ac01_tool_publish_description.rs"]
mod publishfirsttry_ac01_tool_publish_description;
#[path = "publishfirsttry_ac02_structured_error_fields.rs"]
mod publishfirsttry_ac02_structured_error_fields;
#[path = "publishfirsttry_ac07_signup_next.rs"]
mod publishfirsttry_ac07_signup_next;
#[path = "revdebt_ac1_intent_card_pointers_resolve.rs"]
mod revdebt_ac1_intent_card_pointers_resolve;
#[path = "run_metrics_handoff_glob_regression.rs"]
mod run_metrics_handoff_glob_regression;
#[path = "runs_ac05_sync_call_writes_run_row.rs"]
mod runs_ac05_sync_call_writes_run_row;
#[path = "runs_ac07_purge_clears_result.rs"]
mod runs_ac07_purge_clears_result;
#[path = "runs_ac08_tenant_delete_cascades_runs.rs"]
mod runs_ac08_tenant_delete_cascades_runs;
#[path = "runs_ac09_quickstart_and_llms_txt_name_job_limits.rs"]
mod runs_ac09_quickstart_and_llms_txt_name_job_limits;
#[path = "runs_ac10_wait_long_polls.rs"]
mod runs_ac10_wait_long_polls;
#[path = "runs_ac11_admin_runs_reap.rs"]
mod runs_ac11_admin_runs_reap;
#[path = "sandboxready_ac7_conformance_suite.rs"]
mod sandboxready_ac7_conformance_suite;
#[path = "sched_ac10_trigger_fire_manual.rs"]
mod sched_ac10_trigger_fire_manual;
#[path = "sched_ac1_two_firings_visible_in_ledger.rs"]
mod sched_ac1_two_firings_visible_in_ledger;
#[path = "sched_ac2_invalid_cron_names_minute.rs"]
mod sched_ac2_invalid_cron_names_minute;
#[path = "sched_ac3_free_plan_quota_exceeded.rs"]
mod sched_ac3_free_plan_quota_exceeded;
#[path = "sched_ac4_free_plan_interval_too_short.rs"]
mod sched_ac4_free_plan_interval_too_short;
#[path = "sched_ac5_overlap_skips_and_records.rs"]
mod sched_ac5_overlap_skips_and_records;
#[path = "sched_ac6_pause_blocks_resume_allows.rs"]
mod sched_ac6_pause_blocks_resume_allows;
#[path = "sched_ac7_tool_remove_disables_triggers.rs"]
mod sched_ac7_tool_remove_disables_triggers;
#[path = "sched_ac8_healthz_scheduler_fields.rs"]
mod sched_ac8_healthz_scheduler_fields;
#[path = "sched_quickstart_and_usage_report_schedules.rs"]
mod sched_quickstart_and_usage_report_schedules;
#[path = "self_offboard_ac1_disables_tenant_and_returns_success.rs"]
mod self_offboard_ac1_disables_tenant_and_returns_success;
#[path = "self_offboard_ac2_idempotent_second_call.rs"]
mod self_offboard_ac2_idempotent_second_call;
#[path = "self_offboard_ac3_offboarded_key_same_shape_as_unissued.rs"]
mod self_offboard_ac3_offboarded_key_same_shape_as_unissued;
#[path = "self_offboard_ac4_pro_tenant_cancels_stripe_subscription.rs"]
mod self_offboard_ac4_pro_tenant_cancels_stripe_subscription;
#[path = "self_offboard_ac5_admin_tenants_distinguishes_reason.rs"]
mod self_offboard_ac5_admin_tenants_distinguishes_reason;
#[path = "sessionkey_ac02_ac03_discovery_shape.rs"]
mod sessionkey_ac02_ac03_discovery_shape;
#[path = "sessionkey_ac04_signup_usage_field.rs"]
mod sessionkey_ac04_signup_usage_field;
#[path = "sessionkey_ac05_ac07_ac08_ac09_tenant_key_auth.rs"]
mod sessionkey_ac05_ac07_ac08_ac09_tenant_key_auth;
#[path = "sessionkey_ac06_publish_via_tenant_key.rs"]
mod sessionkey_ac06_publish_via_tenant_key;
#[path = "sessionkey_ac10_tenant_key_to_admin_forbidden.rs"]
mod sessionkey_ac10_tenant_key_to_admin_forbidden;
#[path = "sessionkey_ac11_ac12_ac13_ac14_ac15_tool_call.rs"]
mod sessionkey_ac11_ac12_ac13_ac14_ac15_tool_call;
#[path = "sessionkey_ac16_full_session_no_header.rs"]
mod sessionkey_ac16_full_session_no_header;
#[path = "sessionkey_ac18_tool_logs_no_key.rs"]
mod sessionkey_ac18_tool_logs_no_key;
#[path = "sessionkey_ac19_nested_tenant_key_redacted.rs"]
mod sessionkey_ac19_nested_tenant_key_redacted;
#[path = "sessionkey_ac20_error_message_no_key.rs"]
mod sessionkey_ac20_error_message_no_key;
#[path = "share_ac01_public_tool_cross_tenant_call.rs"]
mod share_ac01_public_tool_cross_tenant_call;
#[path = "share_ac02_private_tool_still_not_found.rs"]
mod share_ac02_private_tool_still_not_found;
#[path = "share_ac03_group_visibility_members_only.rs"]
mod share_ac03_group_visibility_members_only;
#[path = "share_ac04_secret_never_reaches_caller.rs"]
mod share_ac04_secret_never_reaches_caller;
#[path = "share_ac05_usage_and_quota_attribution.rs"]
mod share_ac05_usage_and_quota_attribution;
#[path = "share_ac06_share_quota_exceeded.rs"]
mod share_ac06_share_quota_exceeded;
#[path = "share_ac07_catalog_search_and_well_known.rs"]
mod share_ac07_catalog_search_and_well_known;
#[path = "share_ac08_unshare_revokes_access.rs"]
mod share_ac08_unshare_revokes_access;
#[path = "share_ac09_admin_tool_unshare.rs"]
mod share_ac09_admin_tool_unshare;
#[path = "specpath_ac01_map_form_normalizes_and_publishes.rs"]
mod specpath_ac01_map_form_normalizes_and_publishes;
#[path = "specpath_ac02_outputs_map_value_type_error.rs"]
mod specpath_ac02_outputs_map_value_type_error;
#[path = "specpath_ac03_headers_array_type_error.rs"]
mod specpath_ac03_headers_array_type_error;
#[path = "specpath_ac04_path_reads_declared_field.rs"]
mod specpath_ac04_path_reads_declared_field;
#[path = "specpath_ac05_missing_path_reports_tried_path.rs"]
mod specpath_ac05_missing_path_reports_tried_path;
#[path = "specpath_ac06_list_form_seen_at_hint.rs"]
mod specpath_ac06_list_form_seen_at_hint;
#[path = "specpath_ac07_replay_recorded_sessions_map_form.rs"]
mod specpath_ac07_replay_recorded_sessions_map_form;
#[path = "specpath_ac08_wildcard_path_rejected.rs"]
mod specpath_ac08_wildcard_path_rejected;
#[path = "state_ac01_kv_roundtrip.rs"]
mod state_ac01_kv_roundtrip;
#[path = "state_ac04_table_query.rs"]
mod state_ac04_table_query;
#[path = "state_ac05_schema_violation.rs"]
mod state_ac05_schema_violation;
#[path = "state_ac06_quota_exceeded.rs"]
mod state_ac06_quota_exceeded;
#[path = "state_ac08_tenant_isolation.rs"]
mod state_ac08_tenant_isolation;
#[path = "state_ac09_cascade_delete.rs"]
mod state_ac09_cascade_delete;
#[path = "suite_ac1_ten_binaries_and_names_preserved.rs"]
mod suite_ac1_ten_binaries_and_names_preserved;
#[path = "suite_ac2_check_catches_unregistered_file.rs"]
mod suite_ac2_check_catches_unregistered_file;
#[path = "suite_ac3_mod_common_declared_once.rs"]
mod suite_ac3_mod_common_declared_once;
#[path = "suite_ac4_archived_prd_pointers_resolve.rs"]
mod suite_ac4_archived_prd_pointers_resolve;
#[path = "suite_ac5_disk_size_budget.rs"]
mod suite_ac5_disk_size_budget;
#[path = "suite_ac6_wall_time_budget.rs"]
mod suite_ac6_wall_time_budget;
#[path = "suite_ac7_junit_per_test_timing.rs"]
mod suite_ac7_junit_per_test_timing;
#[path = "suite_ac9_selftest_named_and_green.rs"]
mod suite_ac9_selftest_named_and_green;
#[path = "surface_ac02_dry_run_descriptions.rs"]
mod surface_ac02_dry_run_descriptions;
#[path = "surface_ac03_args_invalid_unified.rs"]
mod surface_ac03_args_invalid_unified;
#[path = "surface_ac04_required_field_descriptions.rs"]
mod surface_ac04_required_field_descriptions;
#[path = "surface_ac05_llms_txt_tool_parity.rs"]
mod surface_ac05_llms_txt_tool_parity;
#[path = "surface_ac07_tool_publish_description_length.rs"]
mod surface_ac07_tool_publish_description_length;
#[path = "surface_ac08_get_info_mentions_try_before_call.rs"]
mod surface_ac08_get_info_mentions_try_before_call;
#[path = "synthetic_ac01_migration_null_default.rs"]
mod synthetic_ac01_migration_null_default;
#[path = "synthetic_ac02_signup_header_sets_label.rs"]
mod synthetic_ac02_signup_header_sets_label;
#[path = "synthetic_ac04_tenant_facing_byte_identical.rs"]
mod synthetic_ac04_tenant_facing_byte_identical;
#[path = "synthetic_ac05_admin_tenant_set_synthetic.rs"]
mod synthetic_ac05_admin_tenant_set_synthetic;
#[path = "synthetic_ac06_bulk_retro_tag.rs"]
mod synthetic_ac06_bulk_retro_tag;
#[path = "synthetic_ac07_healthz_counts.rs"]
mod synthetic_ac07_healthz_counts;
#[path = "synthetic_ac08_admin_tenants_field.rs"]
mod synthetic_ac08_admin_tenants_field;
#[path = "synthetic_ac09_metering_filter.rs"]
mod synthetic_ac09_metering_filter;
#[path = "synthetic_ac10_healthz_paying_real.rs"]
mod synthetic_ac10_healthz_paying_real;
#[path = "tables_ac07_tenant_delete_cascade.rs"]
mod tables_ac07_tenant_delete_cascade;
#[path = "tenant_delete_ac01_cascade_delete.rs"]
mod tenant_delete_ac01_cascade_delete;
#[path = "tenant_delete_ac02_forbidden.rs"]
mod tenant_delete_ac02_forbidden;
#[path = "tenant_delete_ac03_dry_run_prefix.rs"]
mod tenant_delete_ac03_dry_run_prefix;
#[path = "tenant_delete_ac04_prefix_delete.rs"]
mod tenant_delete_ac04_prefix_delete;
#[path = "tenant_delete_ac05_prefix_too_short.rs"]
mod tenant_delete_ac05_prefix_too_short;
#[path = "tenant_delete_ac06_migration_cascade.rs"]
mod tenant_delete_ac06_migration_cascade;
#[path = "tenant_delete_ac07_tenant_not_found.rs"]
mod tenant_delete_ac07_tenant_not_found;
#[path = "tenant_delete_ac09_healthz_probe_split.rs"]
mod tenant_delete_ac09_healthz_probe_split;
#[path = "tenant_delete_ac10_tenants_prefix_filter.rs"]
mod tenant_delete_ac10_tenants_prefix_filter;
#[path = "tooltest_ac12_log_marking.rs"]
mod tooltest_ac12_log_marking;
#[path = "tooltest_ac3_http_dry_run.rs"]
mod tooltest_ac3_http_dry_run;
#[path = "tooltest_ac4_echo_verbatim.rs"]
mod tooltest_ac4_echo_verbatim;
#[path = "tooltest_ac5_validation_error_taxonomy.rs"]
mod tooltest_ac5_validation_error_taxonomy;
#[path = "tooltest_ac6_quota_and_metering.rs"]
mod tooltest_ac6_quota_and_metering;
#[path = "tooltest_ac7_too_many_invocations.rs"]
mod tooltest_ac7_too_many_invocations;
#[path = "tooltest_ac9_ac10_listing_and_auth.rs"]
mod tooltest_ac9_ac10_listing_and_auth;
#[path = "wake_ac1_message_trigger_fires_run.rs"]
mod wake_ac1_message_trigger_fires_run;
#[path = "wake_ac2_from_filter.rs"]
mod wake_ac2_from_filter;
#[path = "wake_ac3_dedupe.rs"]
mod wake_ac3_dedupe;
#[path = "wake_ac4_jobs_concurrent_rejects.rs"]
mod wake_ac4_jobs_concurrent_rejects;
#[path = "wake_ac5_pause_resume.rs"]
mod wake_ac5_pause_resume;
#[path = "wake_ac6_msg_wait.rs"]
mod wake_ac6_msg_wait;
#[path = "wake_ac7_trigger_test_synthetic_envelope.rs"]
mod wake_ac7_trigger_test_synthetic_envelope;
#[path = "wake_ac8_replay.rs"]
mod wake_ac8_replay;
#[path = "wasmkind_ac01_echo_component_calls_and_meters.rs"]
mod wasmkind_ac01_echo_component_calls_and_meters;
#[path = "wasmkind_ac02_publish_validation_errors.rs"]
mod wasmkind_ac02_publish_validation_errors;
#[path = "wasmkind_ac03_timeout_and_oom_recover.rs"]
mod wasmkind_ac03_timeout_and_oom_recover;
#[path = "wasmkind_ac05_tool_test_dry_run.rs"]
mod wasmkind_ac05_tool_test_dry_run;
#[path = "wasmkind_ac06_trap_is_structured_and_logged.rs"]
mod wasmkind_ac06_trap_is_structured_and_logged;
#[path = "wasmkind_ac07_docs_llms_and_quickstart_document_wasm.rs"]
mod wasmkind_ac07_docs_llms_and_quickstart_document_wasm;
#[path = "wasmkind_ac08_cache_reuses_compiled_artifact.rs"]
mod wasmkind_ac08_cache_reuses_compiled_artifact;
#[path = "wasmkind_ac09_healthz_reports_wasm_runtime.rs"]
mod wasmkind_ac09_healthz_reports_wasm_runtime;
#[path = "wasmkind_ac10_declared_output_promotion_matches_python.rs"]
mod wasmkind_ac10_declared_output_promotion_matches_python;
