// GENERATED by scripts/gen-test-suites.sh -- do not edit by hand.
// Regenerate with: scripts/gen-test-suites.sh
// Check for drift with: scripts/gen-test-suites.sh --check
//
// This file exists only to give cargo one test BINARY for the files listed
// below; it declares no tests of its own. Every included file keeps its
// original name, path, and test names (nextest's test list, with this
// suite's prefix stripped, is unchanged from before consolidation).
mod common;
#[path = "support/assertion.rs"]
mod assertion;
#[path = "support/oauth.rs"]
mod oauth;
#[path = "support/oauthclient.rs"]
mod oauthclient;

#[path = "synthetic_ac01_migration_null_default.rs"]
mod synthetic_ac01_migration_null_default;
#[path = "synthetic_ac02_signup_header_sets_label.rs"]
mod synthetic_ac02_signup_header_sets_label;
#[path = "synthetic_ac04_tenant_facing_byte_identical.rs"]
mod synthetic_ac04_tenant_facing_byte_identical;
#[path = "synthetic_ac05_admin_tenant_set_synthetic.rs"]
mod synthetic_ac05_admin_tenant_set_synthetic;
#[path = "synthetic_ac06_bulk_retro_tag.rs"]
mod synthetic_ac06_bulk_retro_tag;
#[path = "synthetic_ac07_healthz_counts.rs"]
mod synthetic_ac07_healthz_counts;
#[path = "synthetic_ac08_admin_tenants_field.rs"]
mod synthetic_ac08_admin_tenants_field;
#[path = "synthetic_ac09_metering_filter.rs"]
mod synthetic_ac09_metering_filter;
#[path = "synthetic_ac10_healthz_paying_real.rs"]
mod synthetic_ac10_healthz_paying_real;
#[path = "tablemodel_ac01_key_id_measure_category_date_roles.rs"]
mod tablemodel_ac01_key_id_measure_category_date_roles;
#[path = "tablemodel_ac02_foreign_key_detected_against_customers_id.rs"]
mod tablemodel_ac02_foreign_key_detected_against_customers_id;
#[path = "tablemodel_ac03_measures_and_dimensions_suggested.rs"]
mod tablemodel_ac03_measures_and_dimensions_suggested;
#[path = "tablemodel_ac04_null_share_with_category_role_preserved.rs"]
mod tablemodel_ac04_null_share_with_category_role_preserved;
#[path = "tablemodel_ac05_stale_after_append_recomputes_on_tick.rs"]
mod tablemodel_ac05_stale_after_append_recomputes_on_tick;
#[path = "tablemodel_ac06_large_table_samples_10000_under_500ms.rs"]
mod tablemodel_ac06_large_table_samples_10000_under_500ms;
#[path = "tablemodel_ac07_model_set_unit_annotation_survives_refresh.rs"]
mod tablemodel_ac07_model_set_unit_annotation_survives_refresh;
#[path = "tablemodel_ac08_model_set_role_override_keeps_inferred_role.rs"]
mod tablemodel_ac08_model_set_role_override_keeps_inferred_role;
#[path = "tablemodel_ac09_drop_removes_model_and_annotations.rs"]
mod tablemodel_ac09_drop_removes_model_and_annotations;
#[path = "tablemodel_ac10_empty_table_reports_unknown_types_no_error.rs"]
mod tablemodel_ac10_empty_table_reports_unknown_types_no_error;
#[path = "tables_ac07_tenant_delete_cascade.rs"]
mod tables_ac07_tenant_delete_cascade;
#[path = "tenant_delete_ac01_cascade_delete.rs"]
mod tenant_delete_ac01_cascade_delete;
#[path = "tenant_delete_ac02_forbidden.rs"]
mod tenant_delete_ac02_forbidden;
#[path = "tenant_delete_ac03_dry_run_prefix.rs"]
mod tenant_delete_ac03_dry_run_prefix;
#[path = "tenant_delete_ac04_prefix_delete.rs"]
mod tenant_delete_ac04_prefix_delete;
#[path = "tenant_delete_ac05_prefix_too_short.rs"]
mod tenant_delete_ac05_prefix_too_short;
#[path = "tenant_delete_ac06_migration_cascade.rs"]
mod tenant_delete_ac06_migration_cascade;
#[path = "tenant_delete_ac07_tenant_not_found.rs"]
mod tenant_delete_ac07_tenant_not_found;
#[path = "tenant_delete_ac09_healthz_probe_split.rs"]
mod tenant_delete_ac09_healthz_probe_split;
#[path = "tenant_delete_ac10_tenants_prefix_filter.rs"]
mod tenant_delete_ac10_tenants_prefix_filter;
#[path = "tenantprm_ac01_tenant_metadata_document.rs"]
mod tenantprm_ac01_tenant_metadata_document;
#[path = "tenantprm_ac02_bearer_jwt_tenant_and_audience_scoping.rs"]
mod tenantprm_ac02_bearer_jwt_tenant_and_audience_scoping;
#[path = "tenantprm_ac03_key_based_tenant_scoping_and_unknown_ns_404.rs"]
mod tenantprm_ac03_key_based_tenant_scoping_and_unknown_ns_404;
#[path = "tenantprm_ac04_401_challenge_names_tenant_or_root_metadata.rs"]
mod tenantprm_ac04_401_challenge_names_tenant_or_root_metadata;
#[path = "tenantprm_ac05_scope_gates_tool_calls.rs"]
mod tenantprm_ac05_scope_gates_tool_calls;
#[path = "tenantprm_ac06_whoami_carries_resource_and_metadata_url.rs"]
mod tenantprm_ac06_whoami_carries_resource_and_metadata_url;
#[path = "tenantprm_ac07_key_and_oauth_suites_unchanged.rs"]
mod tenantprm_ac07_key_and_oauth_suites_unchanged;
#[path = "tenantprm_ac09_llms_txt_documents_tenant_oauth.rs"]
mod tenantprm_ac09_llms_txt_documents_tenant_oauth;
#[path = "testtruth_ac01_chain_prev_will_fail.rs"]
mod testtruth_ac01_chain_prev_will_fail;
#[path = "testtruth_ac02_chain_prev_result_pass.rs"]
mod testtruth_ac02_chain_prev_result_pass;
#[path = "testtruth_ac03_chain_prev_no_output_schema_unverifiable.rs"]
mod testtruth_ac03_chain_prev_no_output_schema_unverifiable;
#[path = "testtruth_ac06_publish_gate_verdict.rs"]
mod testtruth_ac06_publish_gate_verdict;
#[path = "testtruth_ac07_quickstart_chain_verdict_blurb.rs"]
mod testtruth_ac07_quickstart_chain_verdict_blurb;
#[path = "tgraph_ac01_foreign_key_edge_and_graph_includes_both_tables.rs"]
mod tgraph_ac01_foreign_key_edge_and_graph_includes_both_tables;
#[path = "tgraph_ac02_join_paths_one_step_foreign_key.rs"]
mod tgraph_ac02_join_paths_one_step_foreign_key;
#[path = "tgraph_ac03_two_step_same_name_path.rs"]
mod tgraph_ac03_two_step_same_name_path;
#[path = "tgraph_ac04_no_shared_columns_returns_no_path_with_candidates.rs"]
mod tgraph_ac04_no_shared_columns_returns_no_path_with_candidates;
#[path = "tgraph_ac05_next_questions_five_entries_all_runnable.rs"]
mod tgraph_ac05_next_questions_five_entries_all_runnable;
#[path = "tgraph_ac06_stale_after_append_tick_clears.rs"]
mod tgraph_ac06_stale_after_append_tick_clears;
#[path = "tgraph_ac07_tenant_isolation_identically_named_tables.rs"]
mod tgraph_ac07_tenant_isolation_identically_named_tables;
#[path = "tgraph_ac08_description_annotation_node_attribute_and_question_text.rs"]
mod tgraph_ac08_description_annotation_node_attribute_and_question_text;
#[path = "tgraph_ac10_fifty_tables_twenty_columns_under_500ms.rs"]
mod tgraph_ac10_fifty_tables_twenty_columns_under_500ms;
#[path = "tkparam_ac01_tenant_key_missing_is_invalid_params.rs"]
mod tkparam_ac01_tenant_key_missing_is_invalid_params;
#[path = "tkparam_ac02_non_string_tenant_key_is_invalid_params.rs"]
mod tkparam_ac02_non_string_tenant_key_is_invalid_params;
#[path = "tkparam_ac03_five_tools_missing_tenant_key.rs"]
mod tkparam_ac03_five_tools_missing_tenant_key;
#[path = "tkparam_ac04_header_auth_unaffected.rs"]
mod tkparam_ac04_header_auth_unaffected;
#[path = "tkparam_ac05_tenant_key_invalid_unchanged.rs"]
mod tkparam_ac05_tenant_key_invalid_unchanged;
#[path = "tkparam_ac06_tenant_key_missing_payload_fields.rs"]
mod tkparam_ac06_tenant_key_missing_payload_fields;
#[path = "tkparam_ac07_example_is_placeholder_not_live.rs"]
mod tkparam_ac07_example_is_placeholder_not_live;
#[path = "tkparam_ac08_secretmissing_and_invalidparams_shape_unchanged.rs"]
mod tkparam_ac08_secretmissing_and_invalidparams_shape_unchanged;
#[path = "tkparam_ac09_schema_tenant_key_not_required_and_discoverable.rs"]
mod tkparam_ac09_schema_tenant_key_not_required_and_discoverable;
#[path = "tkparam_ac11_full_suite_green_at_landing.rs"]
mod tkparam_ac11_full_suite_green_at_landing;
#[path = "toolname_ac01_lint_reports_violations.rs"]
mod toolname_ac01_lint_reports_violations;
#[path = "toolname_ac02_alias_dispatch_hint_and_log.rs"]
mod toolname_ac02_alias_dispatch_hint_and_log;
#[path = "toolname_ac03_tools_list_alias_entries.rs"]
mod toolname_ac03_tools_list_alias_entries;
#[path = "toolname_ac04_docs_names_exist_and_tools_doc_fresh.rs"]
mod toolname_ac04_docs_names_exist_and_tools_doc_fresh;
#[path = "toolname_ac05_alias_metrics_counter.rs"]
mod toolname_ac05_alias_metrics_counter;
#[path = "toolname_ac06_did_you_mean_suggests_canonical.rs"]
mod toolname_ac06_did_you_mean_suggests_canonical;
#[path = "toolname_ac07_whoami_naming_rule_url_once_per_session.rs"]
mod toolname_ac07_whoami_naming_rule_url_once_per_session;
#[path = "toolname_ac08_tools_list_counts_updated.rs"]
mod toolname_ac08_tools_list_counts_updated;
#[path = "toolscope_ac01_scoped_consent_and_token.rs"]
mod toolscope_ac01_scoped_consent_and_token;
#[path = "toolscope_ac02_scoped_token_list_and_call.rs"]
mod toolscope_ac02_scoped_token_list_and_call;
#[path = "toolscope_ac03_step_up_reauthorize_union_scope.rs"]
mod toolscope_ac03_step_up_reauthorize_union_scope;
#[path = "toolscope_ac04_mcp_key_and_pre_prd_token_unaffected.rs"]
mod toolscope_ac04_mcp_key_and_pre_prd_token_unaffected;
#[path = "toolscope_ac05_publish_scope_validation.rs"]
mod toolscope_ac05_publish_scope_validation;
#[path = "toolscope_ac06_scope_change_takes_effect_next_call.rs"]
mod toolscope_ac06_scope_change_takes_effect_next_call;
#[path = "toolscope_ac07_metadata_scopes_supported.rs"]
mod toolscope_ac07_metadata_scopes_supported;
#[path = "toolscope_ac08_admin_stats_consents_by_scope.rs"]
mod toolscope_ac08_admin_stats_consents_by_scope;
#[path = "tooltest_ac12_log_marking.rs"]
mod tooltest_ac12_log_marking;
#[path = "tooltest_ac3_http_dry_run.rs"]
mod tooltest_ac3_http_dry_run;
#[path = "tooltest_ac4_echo_verbatim.rs"]
mod tooltest_ac4_echo_verbatim;
#[path = "tooltest_ac5_validation_error_taxonomy.rs"]
mod tooltest_ac5_validation_error_taxonomy;
#[path = "tooltest_ac6_quota_and_metering.rs"]
mod tooltest_ac6_quota_and_metering;
#[path = "tooltest_ac7_too_many_invocations.rs"]
mod tooltest_ac7_too_many_invocations;
#[path = "tooltest_ac9_ac10_listing_and_auth.rs"]
mod tooltest_ac9_ac10_listing_and_auth;
#[path = "trigidem_ac01_webhook_set_twice_idempotent.rs"]
mod trigidem_ac01_webhook_set_twice_idempotent;
#[path = "trigidem_ac02_webhook_update_tool_keeps_id_and_url.rs"]
mod trigidem_ac02_webhook_update_tool_keeps_id_and_url;
#[path = "trigidem_ac03_schedule_update_cron_changes_next_unix.rs"]
mod trigidem_ac03_schedule_update_cron_changes_next_unix;
#[path = "trigidem_ac04_kind_mismatch_refused.rs"]
mod trigidem_ac04_kind_mismatch_refused;
#[path = "trigidem_ac05_verbs_accept_name.rs"]
mod trigidem_ac05_verbs_accept_name;
#[path = "trigidem_ac06_migration_backfills_duplicate_names.rs"]
mod trigidem_ac06_migration_backfills_duplicate_names;
#[path = "trigidem_ac07_webhook_inbox_quickstart_shows_name_idempotent.rs"]
mod trigidem_ac07_webhook_inbox_quickstart_shows_name_idempotent;
#[path = "unkfield_ac04_trigger_set_unknown_argument.rs"]
mod unkfield_ac04_trigger_set_unknown_argument;
#[path = "unkfield_ac05_tools_list_additional_properties_false.rs"]
mod unkfield_ac05_tools_list_additional_properties_false;
#[path = "unkfield_ac07_spec_fields_doc_check_script.rs"]
mod unkfield_ac07_spec_fields_doc_check_script;
#[path = "upgrade_ac01_calls_per_day_next_checkout.rs"]
mod upgrade_ac01_calls_per_day_next_checkout;
#[path = "upgrade_ac02_billing_off_refusal_text.rs"]
mod upgrade_ac02_billing_off_refusal_text;
#[path = "upgrade_ac03_checkout_source_metadata.rs"]
mod upgrade_ac03_checkout_source_metadata;
#[path = "upgrade_ac04_webhook_stamps_paid_unix.rs"]
mod upgrade_ac04_webhook_stamps_paid_unix;
#[path = "upgrade_ac05_billing_status_receipt.rs"]
mod upgrade_ac05_billing_status_receipt;
#[path = "upgrade_ac06_admin_funnel_upgrades_by_trigger.rs"]
mod upgrade_ac06_admin_funnel_upgrades_by_trigger;
#[path = "upgrade_ac07_admin_upgrades_listing.rs"]
mod upgrade_ac07_admin_upgrades_listing;
#[path = "urltenant_ac01_path_secret_whoami_auth_method_url.rs"]
mod urltenant_ac01_path_secret_whoami_auth_method_url;
#[path = "urltenant_ac02_wrong_or_rotated_secret_404.rs"]
mod urltenant_ac02_wrong_or_rotated_secret_404;
#[path = "urltenant_ac03_key_rotate_rotates_key_and_url.rs"]
mod urltenant_ac03_key_rotate_rotates_key_and_url;
#[path = "urltenant_ac04_new_url_page_and_signup_limiter.rs"]
mod urltenant_ac04_new_url_page_and_signup_limiter;
#[path = "urltenant_ac05_browser_get_shows_explainer_page.rs"]
mod urltenant_ac05_browser_get_shows_explainer_page;
#[path = "urltenant_ac06_quickstart_url_bound_no_signup_step.rs"]
mod urltenant_ac06_quickstart_url_bound_no_signup_step;
#[path = "urltenant_ac07_header_conflict_is_auth_conflict.rs"]
mod urltenant_ac07_header_conflict_is_auth_conflict;
#[path = "vault_ac01_connect_link_redirects_to_auth_url.rs"]
mod vault_ac01_connect_link_redirects_to_auth_url;
#[path = "vault_ac02_callback_exchanges_code_and_stores_tokens.rs"]
mod vault_ac02_callback_exchanges_code_and_stores_tokens;
#[path = "vault_ac03_injects_bearer_overriding_tool_header.rs"]
mod vault_ac03_injects_bearer_overriding_tool_header;
#[path = "vault_ac04_call_log_never_contains_token.rs"]
mod vault_ac04_call_log_never_contains_token;
#[path = "vault_ac05_refresh_before_expiry_used_once.rs"]
mod vault_ac05_refresh_before_expiry_used_once;
#[path = "vault_ac06_unconnected_end_user_gets_connect_link.rs"]
mod vault_ac06_unconnected_end_user_gets_connect_link;
#[path = "vault_ac07_used_handoff_token_returns_410.rs"]
mod vault_ac07_used_handoff_token_returns_410;
#[path = "vault_ac08_disconnect_revokes_and_blocks_calls.rs"]
mod vault_ac08_disconnect_revokes_and_blocks_calls;
#[path = "vault_ac09_providers_hides_client_secret.rs"]
mod vault_ac09_providers_hides_client_secret;
#[path = "vault_ac10_refresh_401_revokes_no_retry_storm.rs"]
mod vault_ac10_refresh_401_revokes_no_retry_storm;
#[path = "vault_ac11_quota_vault_providers.rs"]
mod vault_ac11_quota_vault_providers;
#[path = "vaultst_ac01_status_lists_connected_and_unconnected_providers.rs"]
mod vaultst_ac01_status_lists_connected_and_unconnected_providers;
#[path = "vaultst_ac02_status_end_user_resolution_matches_connect_link.rs"]
mod vaultst_ac02_status_end_user_resolution_matches_connect_link;
#[path = "vaultst_ac03_status_shows_revoked_after_refresh_401.rs"]
mod vaultst_ac03_status_shows_revoked_after_refresh_401;
#[path = "vaultst_ac04_admin_vault_stats_per_tenant_per_provider.rs"]
mod vaultst_ac04_admin_vault_stats_per_tenant_per_provider;
#[path = "vaultst_ac05_admin_vault_stats_rejects_tenant_key.rs"]
mod vaultst_ac05_admin_vault_stats_rejects_tenant_key;
#[path = "vaultst_ac06_provider_remove_revokes_all_tokens.rs"]
mod vaultst_ac06_provider_remove_revokes_all_tokens;
#[path = "vaultst_ac07_provider_set_presets_fill_urls.rs"]
mod vaultst_ac07_provider_set_presets_fill_urls;
#[path = "vaultst_ac08_llms_txt_documents_vault_and_sharing_check_green.rs"]
mod vaultst_ac08_llms_txt_documents_vault_and_sharing_check_green;
#[path = "vaultst_ac09_deferral_is_justified.rs"]
mod vaultst_ac09_deferral_is_justified;
#[path = "vaultst_ac09_live_vault_status_trailer.rs"]
mod vaultst_ac09_live_vault_status_trailer;
#[path = "verbfwd_ac01_trigger_set_dotted_forwards.rs"]
mod verbfwd_ac01_trigger_set_dotted_forwards;
#[path = "verbfwd_ac02_every_spelling_forwards_identically.rs"]
mod verbfwd_ac02_every_spelling_forwards_identically;
#[path = "verbfwd_ac03_tenant_tool_name_wins_over_verb.rs"]
mod verbfwd_ac03_tenant_tool_name_wins_over_verb;
#[path = "verbfwd_ac04_admin_verb_refused_never_forwarded.rs"]
mod verbfwd_ac04_admin_verb_refused_never_forwarded;
#[path = "verbfwd_ac05_tool_test_forwards_dry_run_or_unverifiable.rs"]
mod verbfwd_ac05_tool_test_forwards_dry_run_or_unverifiable;
#[path = "verbfwd_ac06_hint_parity_underscore_form_resolves.rs"]
mod verbfwd_ac06_hint_parity_underscore_form_resolves;
#[path = "verbfwd_ac07_forwarded_call_metered_via_tool_call_no_quota.rs"]
mod verbfwd_ac07_forwarded_call_metered_via_tool_call_no_quota;
#[path = "wake_ac1_message_trigger_fires_run.rs"]
mod wake_ac1_message_trigger_fires_run;
#[path = "wake_ac2_from_filter.rs"]
mod wake_ac2_from_filter;
#[path = "wake_ac3_dedupe.rs"]
mod wake_ac3_dedupe;
#[path = "wake_ac4_jobs_concurrent_rejects.rs"]
mod wake_ac4_jobs_concurrent_rejects;
#[path = "wake_ac5_pause_resume.rs"]
mod wake_ac5_pause_resume;
#[path = "wake_ac6_msg_wait.rs"]
mod wake_ac6_msg_wait;
#[path = "wake_ac7_trigger_test_synthetic_envelope.rs"]
mod wake_ac7_trigger_test_synthetic_envelope;
#[path = "wake_ac8_replay.rs"]
mod wake_ac8_replay;
#[path = "wasmkind_ac01_echo_component_calls_and_meters.rs"]
mod wasmkind_ac01_echo_component_calls_and_meters;
#[path = "wasmkind_ac02_publish_validation_errors.rs"]
mod wasmkind_ac02_publish_validation_errors;
#[path = "wasmkind_ac03_timeout_and_oom_recover.rs"]
mod wasmkind_ac03_timeout_and_oom_recover;
#[path = "wasmkind_ac05_tool_test_dry_run.rs"]
mod wasmkind_ac05_tool_test_dry_run;
#[path = "wasmkind_ac06_trap_is_structured_and_logged.rs"]
mod wasmkind_ac06_trap_is_structured_and_logged;
#[path = "wasmkind_ac07_docs_llms_and_quickstart_document_wasm.rs"]
mod wasmkind_ac07_docs_llms_and_quickstart_document_wasm;
#[path = "wasmkind_ac08_cache_reuses_compiled_artifact.rs"]
mod wasmkind_ac08_cache_reuses_compiled_artifact;
#[path = "wasmkind_ac09_healthz_reports_wasm_runtime.rs"]
mod wasmkind_ac09_healthz_reports_wasm_runtime;
#[path = "wasmkind_ac10_declared_output_promotion_matches_python.rs"]
mod wasmkind_ac10_declared_output_promotion_matches_python;
#[path = "xaa_ac01_valid_assertion_no_consent.rs"]
mod xaa_ac01_valid_assertion_no_consent;
#[path = "xaa_ac03_invalid_grant_reasons_are_distinct_and_audited.rs"]
mod xaa_ac03_invalid_grant_reasons_are_distinct_and_audited;
#[path = "xaa_ac04_invalid_client_scope_target.rs"]
mod xaa_ac04_invalid_client_scope_target;
#[path = "xaa_ac05_metadata_grant_types_and_trusted_issuer.rs"]
mod xaa_ac05_metadata_grant_types_and_trusted_issuer;
#[path = "xaa_ac06_offline_access_gates_refresh_token.rs"]
mod xaa_ac06_offline_access_gates_refresh_token;
#[path = "xaa_ac07_revoke_and_unrevoke_end_user.rs"]
mod xaa_ac07_revoke_and_unrevoke_end_user;
#[path = "xaa_ac08_trusted_issuer_quota.rs"]
mod xaa_ac08_trusted_issuer_quota;
#[path = "xaa_ac09_hosted_and_key_paths_unchanged.rs"]
mod xaa_ac09_hosted_and_key_paths_unchanged;
