// GENERATED by scripts/gen-test-suites.sh -- do not edit by hand.
// Regenerate with: scripts/gen-test-suites.sh
// Check for drift with: scripts/gen-test-suites.sh --check
//
// This file exists only to give cargo one test BINARY for the files listed
// below; it declares no tests of its own. Every included file keeps its
// original name, path, and test names (nextest's test list, with this
// suite's prefix stripped, is unchanged from before consolidation).
mod common;

#[path = "tenant_delete_ac01_cascade_delete.rs"]
mod tenant_delete_ac01_cascade_delete;
#[path = "tenant_delete_ac02_forbidden.rs"]
mod tenant_delete_ac02_forbidden;
#[path = "tenant_delete_ac03_dry_run_prefix.rs"]
mod tenant_delete_ac03_dry_run_prefix;
#[path = "tenant_delete_ac04_prefix_delete.rs"]
mod tenant_delete_ac04_prefix_delete;
#[path = "tenant_delete_ac05_prefix_too_short.rs"]
mod tenant_delete_ac05_prefix_too_short;
#[path = "tenant_delete_ac06_migration_cascade.rs"]
mod tenant_delete_ac06_migration_cascade;
#[path = "tenant_delete_ac07_tenant_not_found.rs"]
mod tenant_delete_ac07_tenant_not_found;
#[path = "tenant_delete_ac09_healthz_probe_split.rs"]
mod tenant_delete_ac09_healthz_probe_split;
#[path = "tenant_delete_ac10_tenants_prefix_filter.rs"]
mod tenant_delete_ac10_tenants_prefix_filter;
#[path = "tooltest_ac12_log_marking.rs"]
mod tooltest_ac12_log_marking;
#[path = "tooltest_ac3_http_dry_run.rs"]
mod tooltest_ac3_http_dry_run;
#[path = "tooltest_ac4_echo_verbatim.rs"]
mod tooltest_ac4_echo_verbatim;
#[path = "tooltest_ac5_validation_error_taxonomy.rs"]
mod tooltest_ac5_validation_error_taxonomy;
#[path = "tooltest_ac6_quota_and_metering.rs"]
mod tooltest_ac6_quota_and_metering;
#[path = "tooltest_ac7_too_many_invocations.rs"]
mod tooltest_ac7_too_many_invocations;
#[path = "tooltest_ac9_ac10_listing_and_auth.rs"]
mod tooltest_ac9_ac10_listing_and_auth;
