// GENERATED by scripts/gen-test-suites.sh -- do not edit by hand.
// Regenerate with: scripts/gen-test-suites.sh
// Check for drift with: scripts/gen-test-suites.sh --check
//
// This file exists only to give cargo one test BINARY for the files listed
// below; it declares no tests of its own. Every included file keeps its
// original name, path, and test names (nextest's test list, with this
// suite's prefix stripped, is unchanged from before consolidation).
mod common;

#[path = "firstpub_ac08_quickstart_http_starter.rs"]
mod firstpub_ac08_quickstart_http_starter;
#[path = "flakelint_ac01_env_mutation.rs"]
mod flakelint_ac01_env_mutation;
#[path = "flakelint_ac05_env_guard_race.rs"]
mod flakelint_ac05_env_guard_race;
#[path = "flakelint_ac07_full_lint_pass_and_env_suites.rs"]
mod flakelint_ac07_full_lint_pass_and_env_suites;
#[path = "support_ac05_support_url_rendered_or_not_configured.rs"]
mod support_ac05_support_url_rendered_or_not_configured;
