// GENERATED by scripts/gen-test-suites.sh -- do not edit by hand.
// Regenerate with: scripts/gen-test-suites.sh
// Check for drift with: scripts/gen-test-suites.sh --check
//
// This file exists only to give cargo one test BINARY for the files listed
// below; it declares no tests of its own. Every included file keeps its
// original name, path, and test names (nextest's test list, with this
// suite's prefix stripped, is unchanged from before consolidation).
mod common;

#[path = "mcphost_python_dependency_policy_ac03_advisory_fails_publish.rs"]
mod mcphost_python_dependency_policy_ac03_advisory_fails_publish;
#[path = "mcphost_python_dependency_policy_ac08_reaudit_flags_new_advisory.rs"]
mod mcphost_python_dependency_policy_ac08_reaudit_flags_new_advisory;
#[path = "mcphost_python_dependency_policy_ac09_admin_usage_counts_network_and_advisories.rs"]
mod mcphost_python_dependency_policy_ac09_admin_usage_counts_network_and_advisories;
#[path = "mcphost_sandbox_egress_allowlist_ac03_pro_no_proxy_egress_unavailable.rs"]
mod mcphost_sandbox_egress_allowlist_ac03_pro_no_proxy_egress_unavailable;
#[path = "mcphost_sandbox_egress_allowlist_ac04_egress_proxy_command_and_env.rs"]
mod mcphost_sandbox_egress_allowlist_ac04_egress_proxy_command_and_env;
#[path = "mcphost_sandbox_egress_allowlist_ac06_downgrade_then_upgrade_republish_hint.rs"]
mod mcphost_sandbox_egress_allowlist_ac06_downgrade_then_upgrade_republish_hint;
#[path = "mcphost_sandbox_egress_allowlist_ac07_healthz_network_denied_counters.rs"]
mod mcphost_sandbox_egress_allowlist_ac07_healthz_network_denied_counters;
