// GENERATED by scripts/gen-test-suites.sh -- do not edit by hand.
// Regenerate with: scripts/gen-test-suites.sh
// Check for drift with: scripts/gen-test-suites.sh --check
//
// This file exists only to give cargo one test BINARY for the files listed
// below; it declares no tests of its own. Every included file keeps its
// original name, path, and test names (nextest's test list, with this
// suite's prefix stripped, is unchanged from before consolidation).
mod common;
mod ci_sandbox_support;

#[path = "ac01_unauthenticated_lists_signup.rs"]
mod ac01_unauthenticated_lists_signup;
#[path = "ac02_signup_creates_hashed_tenant.rs"]
mod ac02_signup_creates_hashed_tenant;
#[path = "ac03_tenant_lists_control_plane_only.rs"]
mod ac03_tenant_lists_control_plane_only;
#[path = "ac04_publish_list_and_call.rs"]
mod ac04_publish_list_and_call;
#[path = "ac05_cross_tenant_isolation.rs"]
mod ac05_cross_tenant_isolation;
#[path = "ac06_remove_tool.rs"]
mod ac06_remove_tool;
#[path = "ac07_usage_metering.rs"]
mod ac07_usage_metering;
#[path = "ac08_admin_disable_and_forbidden.rs"]
mod ac08_admin_disable_and_forbidden;
#[path = "ac09_signup_rate_limit.rs"]
mod ac09_signup_rate_limit;
#[path = "ac10_publish_validation_errors.rs"]
mod ac10_publish_validation_errors;
#[path = "ac11_load_smoke.rs"]
mod ac11_load_smoke;
#[path = "ac12_preflight.rs"]
mod ac12_preflight;
#[path = "ac13_mcp_name_mismatch_metering.rs"]
mod ac13_mcp_name_mismatch_metering;
#[path = "ac14_storage_unwritable.rs"]
mod ac14_storage_unwritable;
#[path = "ac15_call_timeout.rs"]
mod ac15_call_timeout;
#[path = "ac16_request_body_too_large.rs"]
mod ac16_request_body_too_large;
#[path = "ac18_tools_list_ttl.rs"]
mod ac18_tools_list_ttl;
#[path = "ac19_registry_publish.rs"]
mod ac19_registry_publish;
#[path = "attrib_ac1_loopback_signup_unstamped.rs"]
mod attrib_ac1_loopback_signup_unstamped;
#[path = "attrib_ac2_clientinfo_captured.rs"]
mod attrib_ac2_clientinfo_captured;
#[path = "attrib_ac3_backfill_migration.rs"]
mod attrib_ac3_backfill_migration;
#[path = "attrib_ac4_external_signup_counts_real.rs"]
mod attrib_ac4_external_signup_counts_real;
#[path = "attrib_ac5_funnel_report.rs"]
mod attrib_ac5_funnel_report;
#[path = "attrib_ac6_whoami_source_class.rs"]
mod attrib_ac6_whoami_source_class;
#[path = "autherr_ac1_tenant_key_missing.rs"]
mod autherr_ac1_tenant_key_missing;
#[path = "autherr_ac2_tenant_key_invalid.rs"]
mod autherr_ac2_tenant_key_invalid;
#[path = "autherr_ac3_disabled_tenant_key_invalid.rs"]
mod autherr_ac3_disabled_tenant_key_invalid;
#[path = "autherr_ac4_bearer_invalid_unchanged.rs"]
mod autherr_ac4_bearer_invalid_unchanged;
#[path = "autherr_ac5_instructions_mention_codes.rs"]
mod autherr_ac5_instructions_mention_codes;
#[path = "billing_ac01_plans_toml_and_billing_plans.rs"]
mod billing_ac01_plans_toml_and_billing_plans;
#[path = "billing_ac02_publish_quota_exceeded.rs"]
mod billing_ac02_publish_quota_exceeded;
#[path = "billing_ac03_call_time_quota_exceeded.rs"]
mod billing_ac03_call_time_quota_exceeded;
#[path = "billing_ac04_checkout_unavailable_no_keys.rs"]
mod billing_ac04_checkout_unavailable_no_keys;
#[path = "billing_ac05_checkout_returns_session.rs"]
mod billing_ac05_checkout_returns_session;
#[path = "billing_ac06_webhook_checkout_completed_idempotent.rs"]
mod billing_ac06_webhook_checkout_completed_idempotent;
#[path = "billing_ac07_webhook_bad_signature_or_stale.rs"]
mod billing_ac07_webhook_bad_signature_or_stale;
#[path = "billing_ac08_webhook_subscription_deleted_downgrades.rs"]
mod billing_ac08_webhook_subscription_deleted_downgrades;
#[path = "billing_ac09_admin_billing_ledger_filters.rs"]
mod billing_ac09_admin_billing_ledger_filters;
#[path = "billing_ac10_webhook_mode_mismatch.rs"]
mod billing_ac10_webhook_mode_mismatch;
#[path = "billing_ac11_healthz_paying_tenants.rs"]
mod billing_ac11_healthz_paying_tenants;
#[path = "billing_ac13_checkout_reuse.rs"]
mod billing_ac13_checkout_reuse;
#[path = "checkcompat_ac02_ac03.rs"]
mod checkcompat_ac02_ac03;
#[path = "ci_sandbox_ac01_workflow_executes_sandbox_suites.rs"]
mod ci_sandbox_ac01_workflow_executes_sandbox_suites;
#[path = "ci_sandbox_ac03_incapable_in_ci_skips_and_fails_job.rs"]
mod ci_sandbox_ac03_incapable_in_ci_skips_and_fails_job;
#[path = "ci_sandbox_ac04_incapable_outside_ci_fails_loudly.rs"]
mod ci_sandbox_ac04_incapable_outside_ci_fails_loudly;
#[path = "ci_sandbox_ac06_sandbox_suites_run_as_a_parallel_job.rs"]
mod ci_sandbox_ac06_sandbox_suites_run_as_a_parallel_job;
#[path = "classify_ac9_is_within_proptest.rs"]
mod classify_ac9_is_within_proptest;
#[path = "compat_ac01_ac02_ac03_cache_fields.rs"]
mod compat_ac01_ac02_ac03_cache_fields;
#[path = "compat_ac04_ac05_admin_and_tenant_cache_fields.rs"]
mod compat_ac04_ac05_admin_and_tenant_cache_fields;
#[path = "compat_ac08_ac09_ac10_advertised_version.rs"]
mod compat_ac08_ac09_ac10_advertised_version;
#[path = "compat_ac11_ac12_claude_sdk_replay.rs"]
mod compat_ac11_ac12_claude_sdk_replay;
#[path = "compose_ac3_self_call_refused.rs"]
mod compose_ac3_self_call_refused;
#[path = "compose_ac4_depth_exceeded.rs"]
mod compose_ac4_depth_exceeded;
#[path = "compose_ac5_three_step_chain_prev_mapping.rs"]
mod compose_ac5_three_step_chain_prev_mapping;
#[path = "compose_ac6_mapping_missing.rs"]
mod compose_ac6_mapping_missing;
#[path = "compose_ac7_on_error_continue.rs"]
mod compose_ac7_on_error_continue;
#[path = "compose_ac8_tool_test_dry_run.rs"]
mod compose_ac8_tool_test_dry_run;
#[path = "envelope_ac1_http_declared_output_promoted.rs"]
mod envelope_ac1_http_declared_output_promoted;
#[path = "envelope_ac4_tool_test_reports_missing_declared_output.rs"]
mod envelope_ac4_tool_test_reports_missing_declared_output;
#[path = "firstcall_ac6_outcome_metering.rs"]
mod firstcall_ac6_outcome_metering;
#[path = "handoff_ac01_signup_returns_token_and_no_key.rs"]
mod handoff_ac01_signup_returns_token_and_no_key;
#[path = "handoff_ac02_redeem_single_use_and_expiry.rs"]
mod handoff_ac02_redeem_single_use_and_expiry;
#[path = "handoff_ac03_key_rotate_invalidates_old_key.rs"]
mod handoff_ac03_key_rotate_invalidates_old_key;
#[path = "handoff_ac04_full_two_context_flow.rs"]
mod handoff_ac04_full_two_context_flow;
#[path = "handoff_ac05_raw_signup_still_works_unchanged.rs"]
mod handoff_ac05_raw_signup_still_works_unchanged;
#[path = "handoff_ac06_errors_never_echo_token_or_key.rs"]
mod handoff_ac06_errors_never_echo_token_or_key;
#[path = "handoff_ac07_docs_recommend_handoff_flow.rs"]
mod handoff_ac07_docs_recommend_handoff_flow;
#[path = "handoff_ac08_whoami_reports_key_age_and_rotation.rs"]
mod handoff_ac08_whoami_reports_key_age_and_rotation;
#[path = "hooks_ac10_healthz_event_counters.rs"]
mod hooks_ac10_healthz_event_counters;
#[path = "hooks_ac11_dedupe_header_idempotent.rs"]
mod hooks_ac11_dedupe_header_idempotent;
#[path = "hooks_ac1_hmac_sha256_valid_signature_runs.rs"]
mod hooks_ac1_hmac_sha256_valid_signature_runs;
#[path = "hooks_ac2_wrong_signature_401_no_run.rs"]
mod hooks_ac2_wrong_signature_401_no_run;
#[path = "hooks_ac3_stripe_style_stale_timestamp_401.rs"]
mod hooks_ac3_stripe_style_stale_timestamp_401;
#[path = "hooks_ac4_none_scheme_requires_allow_unverified.rs"]
mod hooks_ac4_none_scheme_requires_allow_unverified;
#[path = "hooks_ac5_rate_limit_429.rs"]
mod hooks_ac5_rate_limit_429;
#[path = "hooks_ac6_body_too_large_413.rs"]
mod hooks_ac6_body_too_large_413;
#[path = "hooks_ac7_trigger_test_creates_marked_run.rs"]
mod hooks_ac7_trigger_test_creates_marked_run;
#[path = "hooks_ac8_trigger_replay_new_run_trigger_ref.rs"]
mod hooks_ac8_trigger_replay_new_run_trigger_ref;
#[path = "hooks_ac9_paused_trigger_404.rs"]
mod hooks_ac9_paused_trigger_404;
