// GENERATED by scripts/gen-test-suites.sh -- do not edit by hand.
// Regenerate with: scripts/gen-test-suites.sh
// Check for drift with: scripts/gen-test-suites.sh --check
//
// This file exists only to give cargo one test BINARY for the files listed
// below; it declares no tests of its own. Every included file keeps its
// original name, path, and test names (nextest's test list, with this
// suite's prefix stripped, is unchanged from before consolidation).
mod common;

#[path = "runtime_ac1_range_typeerror_fixture.rs"]
mod runtime_ac1_range_typeerror_fixture;
#[path = "runtime_ac2_tool_code_phase_and_line.rs"]
mod runtime_ac2_tool_code_phase_and_line;
#[path = "runtime_ac3_args_coercion_phase_and_types.rs"]
mod runtime_ac3_args_coercion_phase_and_types;
#[path = "runtime_ac4_publish_and_first_call_latency.rs"]
mod runtime_ac4_publish_and_first_call_latency;
#[path = "runtime_ac5_assignment_expression_message.rs"]
mod runtime_ac5_assignment_expression_message;
#[path = "runtime_ac6_readme_documents_restriction.rs"]
mod runtime_ac6_readme_documents_restriction;
#[path = "sandboxready_ac10_sandbox_check_subcommand.rs"]
mod sandboxready_ac10_sandbox_check_subcommand;
#[path = "sandboxready_ac1_ac2_healthz_startup.rs"]
mod sandboxready_ac1_ac2_healthz_startup;
#[path = "sandboxready_ac3_ac4_publish_rejection.rs"]
mod sandboxready_ac3_ac4_publish_rejection;
#[path = "sandboxready_ac5_admin_recheck_recovers.rs"]
mod sandboxready_ac5_admin_recheck_recovers;
#[path = "sandboxready_ac6_periodic_recheck_flips_unready.rs"]
mod sandboxready_ac6_periodic_recheck_flips_unready;
#[path = "sandboxready_ac8_get_info_and_description_note.rs"]
mod sandboxready_ac8_get_info_and_description_note;
#[path = "sandboxready_ac9_failure_classification.rs"]
mod sandboxready_ac9_failure_classification;
#[path = "state_ac02_ac03_python_sandbox.rs"]
mod state_ac02_ac03_python_sandbox;
#[path = "state_ac03_network_none_default.rs"]
mod state_ac03_network_none_default;
#[path = "state_ac07_tool_test_observability.rs"]
mod state_ac07_tool_test_observability;
#[path = "state_ac10_quickstart_llms_txt.rs"]
mod state_ac10_quickstart_llms_txt;
#[path = "surface_ac01_quickstart_try_before_call.rs"]
mod surface_ac01_quickstart_try_before_call;
#[path = "surface_ac06_python_outputs_by_path.rs"]
mod surface_ac06_python_outputs_by_path;
#[path = "tooltest_ac13_publish_error_parity.rs"]
mod tooltest_ac13_publish_error_parity;
#[path = "tooltest_ac1_python_two_invocations.rs"]
mod tooltest_ac1_python_two_invocations;
#[path = "tooltest_ac2_python_exception_other_still_runs.rs"]
mod tooltest_ac2_python_exception_other_still_runs;
#[path = "warmpool_ac06_ac07_tool_run.rs"]
mod warmpool_ac06_ac07_tool_run;
