// GENERATED by scripts/gen-test-suites.sh -- do not edit by hand.
// Regenerate with: scripts/gen-test-suites.sh
// Check for drift with: scripts/gen-test-suites.sh --check
//
// This file exists only to give cargo one test BINARY for the files listed
// below; it declares no tests of its own. Every included file keeps its
// original name, path, and test names (nextest's test list, with this
// suite's prefix stripped, is unchanged from before consolidation).
mod common;

#[path = "provaudit_ac01_synthetic_signup_stamped.rs"]
mod provaudit_ac01_synthetic_signup_stamped;
#[path = "provaudit_ac02_external_signup_stamped.rs"]
mod provaudit_ac02_external_signup_stamped;
#[path = "provaudit_ac03_migration_backfill_counts.rs"]
mod provaudit_ac03_migration_backfill_counts;
#[path = "provaudit_ac04_healthz_split_shape.rs"]
mod provaudit_ac04_healthz_split_shape;
#[path = "provaudit_ac05_admin_audit_log.rs"]
mod provaudit_ac05_admin_audit_log;
#[path = "provaudit_ac06_null_origin_rejected.rs"]
mod provaudit_ac06_null_origin_rejected;
#[path = "provaudit_ac07_ip_class_triage.rs"]
mod provaudit_ac07_ip_class_triage;
#[path = "proxy_ac1_loopback_xff_resolves_signup_source.rs"]
mod proxy_ac1_loopback_xff_resolves_signup_source;
#[path = "proxy_ac2_non_loopback_peer_ignores_header.rs"]
mod proxy_ac2_non_loopback_peer_ignores_header;
#[path = "proxy_ac3_unparseable_header_falls_back.rs"]
mod proxy_ac3_unparseable_header_falls_back;
#[path = "proxy_ac4_rate_limit_keys_on_resolved_address.rs"]
mod proxy_ac4_rate_limit_keys_on_resolved_address;
#[path = "proxy_ac5_signup_event_stores_forwarded_address.rs"]
mod proxy_ac5_signup_event_stores_forwarded_address;
#[path = "proxy_ac6_healthz_distinct_source_ips.rs"]
mod proxy_ac6_healthz_distinct_source_ips;
#[path = "publishfirsttry_ac01_tool_publish_description.rs"]
mod publishfirsttry_ac01_tool_publish_description;
#[path = "publishfirsttry_ac02_structured_error_fields.rs"]
mod publishfirsttry_ac02_structured_error_fields;
#[path = "publishfirsttry_ac07_signup_next.rs"]
mod publishfirsttry_ac07_signup_next;
#[path = "revdebt_ac1_intent_card_pointers_resolve.rs"]
mod revdebt_ac1_intent_card_pointers_resolve;
#[path = "runs_ac05_sync_call_writes_run_row.rs"]
mod runs_ac05_sync_call_writes_run_row;
#[path = "runs_ac07_purge_clears_result.rs"]
mod runs_ac07_purge_clears_result;
#[path = "runs_ac08_tenant_delete_cascades_runs.rs"]
mod runs_ac08_tenant_delete_cascades_runs;
#[path = "runs_ac09_quickstart_and_llms_txt_name_job_limits.rs"]
mod runs_ac09_quickstart_and_llms_txt_name_job_limits;
#[path = "runs_ac10_wait_long_polls.rs"]
mod runs_ac10_wait_long_polls;
#[path = "runs_ac11_admin_runs_reap.rs"]
mod runs_ac11_admin_runs_reap;
#[path = "sandboxready_ac7_conformance_suite.rs"]
mod sandboxready_ac7_conformance_suite;
#[path = "sched_ac10_trigger_fire_manual.rs"]
mod sched_ac10_trigger_fire_manual;
#[path = "sched_ac1_two_firings_visible_in_ledger.rs"]
mod sched_ac1_two_firings_visible_in_ledger;
#[path = "sched_ac2_invalid_cron_names_minute.rs"]
mod sched_ac2_invalid_cron_names_minute;
#[path = "sched_ac3_free_plan_quota_exceeded.rs"]
mod sched_ac3_free_plan_quota_exceeded;
#[path = "sched_ac4_free_plan_interval_too_short.rs"]
mod sched_ac4_free_plan_interval_too_short;
#[path = "sched_ac5_overlap_skips_and_records.rs"]
mod sched_ac5_overlap_skips_and_records;
#[path = "sched_ac6_pause_blocks_resume_allows.rs"]
mod sched_ac6_pause_blocks_resume_allows;
#[path = "sched_ac7_tool_remove_disables_triggers.rs"]
mod sched_ac7_tool_remove_disables_triggers;
#[path = "sched_ac8_healthz_scheduler_fields.rs"]
mod sched_ac8_healthz_scheduler_fields;
#[path = "sched_quickstart_and_usage_report_schedules.rs"]
mod sched_quickstart_and_usage_report_schedules;
#[path = "sessionkey_ac02_ac03_discovery_shape.rs"]
mod sessionkey_ac02_ac03_discovery_shape;
#[path = "sessionkey_ac04_signup_usage_field.rs"]
mod sessionkey_ac04_signup_usage_field;
#[path = "sessionkey_ac05_ac07_ac08_ac09_tenant_key_auth.rs"]
mod sessionkey_ac05_ac07_ac08_ac09_tenant_key_auth;
#[path = "sessionkey_ac06_publish_via_tenant_key.rs"]
mod sessionkey_ac06_publish_via_tenant_key;
#[path = "sessionkey_ac10_tenant_key_to_admin_forbidden.rs"]
mod sessionkey_ac10_tenant_key_to_admin_forbidden;
#[path = "sessionkey_ac11_ac12_ac13_ac14_ac15_tool_call.rs"]
mod sessionkey_ac11_ac12_ac13_ac14_ac15_tool_call;
#[path = "sessionkey_ac16_full_session_no_header.rs"]
mod sessionkey_ac16_full_session_no_header;
#[path = "sessionkey_ac17_request_log_no_key.rs"]
mod sessionkey_ac17_request_log_no_key;
#[path = "sessionkey_ac18_tool_logs_no_key.rs"]
mod sessionkey_ac18_tool_logs_no_key;
#[path = "sessionkey_ac19_nested_tenant_key_redacted.rs"]
mod sessionkey_ac19_nested_tenant_key_redacted;
#[path = "sessionkey_ac20_error_message_no_key.rs"]
mod sessionkey_ac20_error_message_no_key;
#[path = "share_ac01_public_tool_cross_tenant_call.rs"]
mod share_ac01_public_tool_cross_tenant_call;
#[path = "share_ac02_private_tool_still_not_found.rs"]
mod share_ac02_private_tool_still_not_found;
#[path = "share_ac03_group_visibility_members_only.rs"]
mod share_ac03_group_visibility_members_only;
#[path = "share_ac04_secret_never_reaches_caller.rs"]
mod share_ac04_secret_never_reaches_caller;
#[path = "share_ac05_usage_and_quota_attribution.rs"]
mod share_ac05_usage_and_quota_attribution;
#[path = "share_ac06_share_quota_exceeded.rs"]
mod share_ac06_share_quota_exceeded;
#[path = "share_ac07_catalog_search_and_well_known.rs"]
mod share_ac07_catalog_search_and_well_known;
#[path = "share_ac08_unshare_revokes_access.rs"]
mod share_ac08_unshare_revokes_access;
#[path = "share_ac09_admin_tool_unshare.rs"]
mod share_ac09_admin_tool_unshare;
