// GENERATED by scripts/gen-test-suites.sh -- do not edit by hand.
// Regenerate with: scripts/gen-test-suites.sh
// Check for drift with: scripts/gen-test-suites.sh --check
//
// This file exists only to give cargo one test BINARY for the files listed
// below; it declares no tests of its own. Every included file keeps its
// original name, path, and test names (nextest's test list, with this
// suite's prefix stripped, is unchanged from before consolidation).
mod common;

#[path = "specpath_ac01_map_form_normalizes_and_publishes.rs"]
mod specpath_ac01_map_form_normalizes_and_publishes;
#[path = "specpath_ac02_outputs_map_value_type_error.rs"]
mod specpath_ac02_outputs_map_value_type_error;
#[path = "specpath_ac03_headers_array_type_error.rs"]
mod specpath_ac03_headers_array_type_error;
#[path = "specpath_ac04_path_reads_declared_field.rs"]
mod specpath_ac04_path_reads_declared_field;
#[path = "specpath_ac05_missing_path_reports_tried_path.rs"]
mod specpath_ac05_missing_path_reports_tried_path;
#[path = "specpath_ac06_list_form_seen_at_hint.rs"]
mod specpath_ac06_list_form_seen_at_hint;
#[path = "specpath_ac07_replay_recorded_sessions_map_form.rs"]
mod specpath_ac07_replay_recorded_sessions_map_form;
#[path = "specpath_ac08_wildcard_path_rejected.rs"]
mod specpath_ac08_wildcard_path_rejected;
#[path = "state_ac01_kv_roundtrip.rs"]
mod state_ac01_kv_roundtrip;
#[path = "state_ac04_table_query.rs"]
mod state_ac04_table_query;
#[path = "state_ac05_schema_violation.rs"]
mod state_ac05_schema_violation;
#[path = "state_ac06_quota_exceeded.rs"]
mod state_ac06_quota_exceeded;
#[path = "state_ac08_tenant_isolation.rs"]
mod state_ac08_tenant_isolation;
#[path = "state_ac09_cascade_delete.rs"]
mod state_ac09_cascade_delete;
#[path = "suite_ac1_ten_binaries_and_names_preserved.rs"]
mod suite_ac1_ten_binaries_and_names_preserved;
#[path = "suite_ac2_check_catches_unregistered_file.rs"]
mod suite_ac2_check_catches_unregistered_file;
#[path = "suite_ac3_mod_common_declared_once.rs"]
mod suite_ac3_mod_common_declared_once;
#[path = "suite_ac4_archived_prd_pointers_resolve.rs"]
mod suite_ac4_archived_prd_pointers_resolve;
#[path = "suite_ac5_disk_size_budget.rs"]
mod suite_ac5_disk_size_budget;
#[path = "suite_ac6_wall_time_budget.rs"]
mod suite_ac6_wall_time_budget;
#[path = "suite_ac7_junit_per_test_timing.rs"]
mod suite_ac7_junit_per_test_timing;
#[path = "suite_ac9_selftest_named_and_green.rs"]
mod suite_ac9_selftest_named_and_green;
#[path = "surface_ac02_dry_run_descriptions.rs"]
mod surface_ac02_dry_run_descriptions;
#[path = "surface_ac03_args_invalid_unified.rs"]
mod surface_ac03_args_invalid_unified;
#[path = "surface_ac04_required_field_descriptions.rs"]
mod surface_ac04_required_field_descriptions;
#[path = "surface_ac05_llms_txt_tool_parity.rs"]
mod surface_ac05_llms_txt_tool_parity;
#[path = "surface_ac07_tool_publish_description_length.rs"]
mod surface_ac07_tool_publish_description_length;
#[path = "surface_ac08_get_info_mentions_try_before_call.rs"]
mod surface_ac08_get_info_mentions_try_before_call;
#[path = "synthetic_ac01_migration_null_default.rs"]
mod synthetic_ac01_migration_null_default;
#[path = "synthetic_ac02_signup_header_sets_label.rs"]
mod synthetic_ac02_signup_header_sets_label;
#[path = "synthetic_ac03_invalid_and_missing_header.rs"]
mod synthetic_ac03_invalid_and_missing_header;
#[path = "synthetic_ac04_tenant_facing_byte_identical.rs"]
mod synthetic_ac04_tenant_facing_byte_identical;
#[path = "synthetic_ac05_admin_tenant_set_synthetic.rs"]
mod synthetic_ac05_admin_tenant_set_synthetic;
#[path = "synthetic_ac06_bulk_retro_tag.rs"]
mod synthetic_ac06_bulk_retro_tag;
#[path = "synthetic_ac07_healthz_counts.rs"]
mod synthetic_ac07_healthz_counts;
#[path = "synthetic_ac08_admin_tenants_field.rs"]
mod synthetic_ac08_admin_tenants_field;
#[path = "synthetic_ac09_metering_filter.rs"]
mod synthetic_ac09_metering_filter;
#[path = "synthetic_ac10_healthz_paying_real.rs"]
mod synthetic_ac10_healthz_paying_real;
#[path = "tenant_delete_ac01_cascade_delete.rs"]
mod tenant_delete_ac01_cascade_delete;
#[path = "tenant_delete_ac02_forbidden.rs"]
mod tenant_delete_ac02_forbidden;
#[path = "tenant_delete_ac03_dry_run_prefix.rs"]
mod tenant_delete_ac03_dry_run_prefix;
#[path = "tenant_delete_ac04_prefix_delete.rs"]
mod tenant_delete_ac04_prefix_delete;
#[path = "tenant_delete_ac05_prefix_too_short.rs"]
mod tenant_delete_ac05_prefix_too_short;
#[path = "tenant_delete_ac06_migration_cascade.rs"]
mod tenant_delete_ac06_migration_cascade;
#[path = "tenant_delete_ac07_tenant_not_found.rs"]
mod tenant_delete_ac07_tenant_not_found;
#[path = "tenant_delete_ac08_audit_log_and_events.rs"]
mod tenant_delete_ac08_audit_log_and_events;
#[path = "tenant_delete_ac09_healthz_probe_split.rs"]
mod tenant_delete_ac09_healthz_probe_split;
#[path = "tenant_delete_ac10_tenants_prefix_filter.rs"]
mod tenant_delete_ac10_tenants_prefix_filter;
#[path = "tooltest_ac12_log_marking.rs"]
mod tooltest_ac12_log_marking;
#[path = "tooltest_ac3_http_dry_run.rs"]
mod tooltest_ac3_http_dry_run;
#[path = "tooltest_ac4_echo_verbatim.rs"]
mod tooltest_ac4_echo_verbatim;
#[path = "tooltest_ac5_validation_error_taxonomy.rs"]
mod tooltest_ac5_validation_error_taxonomy;
#[path = "tooltest_ac6_quota_and_metering.rs"]
mod tooltest_ac6_quota_and_metering;
#[path = "tooltest_ac7_too_many_invocations.rs"]
mod tooltest_ac7_too_many_invocations;
#[path = "tooltest_ac9_ac10_listing_and_auth.rs"]
mod tooltest_ac9_ac10_listing_and_auth;
