// GENERATED by scripts/gen-test-suites.sh -- do not edit by hand.
// Regenerate with: scripts/gen-test-suites.sh
// Check for drift with: scripts/gen-test-suites.sh --check
//
// This file exists only to give cargo one test BINARY for the files listed
// below; it declares no tests of its own. Every included file keeps its
// original name, path, and test names (nextest's test list, with this
// suite's prefix stripped, is unchanged from before consolidation).
mod common;

#[path = "python_ac01_no_deps_cpu_memory.rs"]
mod python_ac01_no_deps_cpu_memory;
#[path = "python_ac02_requirements_build_and_building_state.rs"]
mod python_ac02_requirements_build_and_building_state;
#[path = "python_ac03_invalid_source_rejected.rs"]
mod python_ac03_invalid_source_rejected;
#[path = "python_ac04_disallowed_requirement.rs"]
mod python_ac04_disallowed_requirement;
#[path = "python_ac05_exception_traceback.rs"]
mod python_ac05_exception_traceback;
#[path = "python_ac06_timeout.rs"]
mod python_ac06_timeout;
#[path = "python_ac07_oom.rs"]
mod python_ac07_oom;
#[path = "python_ac08_network_none_blocks.rs"]
mod python_ac08_network_none_blocks;
#[path = "python_ac09_filesystem_isolation.rs"]
mod python_ac09_filesystem_isolation;
#[path = "python_ac10_fork_bomb_contained.rs"]
mod python_ac10_fork_bomb_contained;
#[path = "python_ac11_secret_redaction.rs"]
mod python_ac11_secret_redaction;
#[path = "python_ac12_republish_atomic.rs"]
mod python_ac12_republish_atomic;
#[path = "python_ac13_capacity_admission.rs"]
mod python_ac13_capacity_admission;
#[path = "python_ac14_cpu_budget_rate_limit.rs"]
mod python_ac14_cpu_budget_rate_limit;
#[path = "runenvelope_ac1_call_and_tool_run_parity.rs"]
mod runenvelope_ac1_call_and_tool_run_parity;
#[path = "runenvelope_ac2_no_declared_outputs_raw_payload.rs"]
mod runenvelope_ac2_no_declared_outputs_raw_payload;
#[path = "runenvelope_ac3_descriptor_and_decision_table_name_envelope.rs"]
mod runenvelope_ac3_descriptor_and_decision_table_name_envelope;
#[path = "runenvelope_ac4_no_calls_row_with_payload.rs"]
mod runenvelope_ac4_no_calls_row_with_payload;
#[path = "runoverflow_ac01_python_async_result_overflows_to_parts.rs"]
mod runoverflow_ac01_python_async_result_overflows_to_parts;
#[path = "runoverflow_ac02_state_quota_error_preserves_counters.rs"]
mod runoverflow_ac02_state_quota_error_preserves_counters;
#[path = "runoverflow_ac06_purge_drops_run_results_bytes_not_user_state.rs"]
mod runoverflow_ac06_purge_drops_run_results_bytes_not_user_state;
#[path = "runoverflow_ac07_llms_txt_long_running_jobs_walkthrough.rs"]
mod runoverflow_ac07_llms_txt_long_running_jobs_walkthrough;
#[path = "runoverflow_ac08_wait_until_counter_returns_while_running.rs"]
mod runoverflow_ac08_wait_until_counter_returns_while_running;
#[path = "runoverflow_ac09_sync_call_still_tool_output_too_large.rs"]
mod runoverflow_ac09_sync_call_still_tool_output_too_large;
#[path = "runs_ac01_async_job_runs_progress_and_result.rs"]
mod runs_ac01_async_job_runs_progress_and_result;
#[path = "runs_ac02_job_max_s_timeout.rs"]
mod runs_ac02_job_max_s_timeout;
#[path = "runs_ac03_progress_shape.rs"]
mod runs_ac03_progress_shape;
#[path = "runs_ac04_cancel_kills_sandbox.rs"]
mod runs_ac04_cancel_kills_sandbox;
#[path = "runs_ac06_jobs_concurrent_gate.rs"]
mod runs_ac06_jobs_concurrent_gate;
#[path = "runtime_ac1_range_typeerror_fixture.rs"]
mod runtime_ac1_range_typeerror_fixture;
#[path = "runtime_ac2_tool_code_phase_and_line.rs"]
mod runtime_ac2_tool_code_phase_and_line;
#[path = "runtime_ac3_args_coercion_phase_and_types.rs"]
mod runtime_ac3_args_coercion_phase_and_types;
#[path = "runtime_ac4_publish_and_first_call_latency.rs"]
mod runtime_ac4_publish_and_first_call_latency;
#[path = "runtime_ac5_assignment_expression_message.rs"]
mod runtime_ac5_assignment_expression_message;
#[path = "runtime_ac6_readme_documents_restriction.rs"]
mod runtime_ac6_readme_documents_restriction;
#[path = "sandboxready_ac10_sandbox_check_subcommand.rs"]
mod sandboxready_ac10_sandbox_check_subcommand;
#[path = "sandboxready_ac1_ac2_healthz_startup.rs"]
mod sandboxready_ac1_ac2_healthz_startup;
#[path = "sandboxready_ac3_ac4_publish_rejection.rs"]
mod sandboxready_ac3_ac4_publish_rejection;
#[path = "sandboxready_ac5_admin_recheck_recovers.rs"]
mod sandboxready_ac5_admin_recheck_recovers;
#[path = "sandboxready_ac6_periodic_recheck_flips_unready.rs"]
mod sandboxready_ac6_periodic_recheck_flips_unready;
#[path = "sandboxready_ac8_get_info_and_description_note.rs"]
mod sandboxready_ac8_get_info_and_description_note;
#[path = "sandboxready_ac9_failure_classification.rs"]
mod sandboxready_ac9_failure_classification;
#[path = "state_ac02_ac03_python_sandbox.rs"]
mod state_ac02_ac03_python_sandbox;
#[path = "state_ac03_network_none_default.rs"]
mod state_ac03_network_none_default;
#[path = "state_ac07_tool_test_observability.rs"]
mod state_ac07_tool_test_observability;
#[path = "state_ac10_quickstart_llms_txt.rs"]
mod state_ac10_quickstart_llms_txt;
#[path = "statusfeed_ac01_operational_after_three_minutes.rs"]
mod statusfeed_ac01_operational_after_three_minutes;
#[path = "statusfeed_ac09_alert_and_auto_incident.rs"]
mod statusfeed_ac09_alert_and_auto_incident;
#[path = "statusfeed_ac11_live_status_trailer.rs"]
mod statusfeed_ac11_live_status_trailer;
#[path = "stdlibpseudo_ac1_future_import_empty_requirements.rs"]
mod stdlibpseudo_ac1_future_import_empty_requirements;
#[path = "stdlibpseudo_ac2_dunder_main_no_requirement.rs"]
mod stdlibpseudo_ac2_dunder_main_no_requirement;
#[path = "surface_ac01_quickstart_try_before_call.rs"]
mod surface_ac01_quickstart_try_before_call;
#[path = "surface_ac06_python_outputs_by_path.rs"]
mod surface_ac06_python_outputs_by_path;
#[path = "tables_ac05_python_sandbox_table_access.rs"]
mod tables_ac05_python_sandbox_table_access;
#[path = "tables_ac08_docs_and_kv_vs_table_sentence.rs"]
mod tables_ac08_docs_and_kv_vs_table_sentence;
#[path = "tooltest_ac13_publish_error_parity.rs"]
mod tooltest_ac13_publish_error_parity;
#[path = "tooltest_ac1_python_two_invocations.rs"]
mod tooltest_ac1_python_two_invocations;
#[path = "tooltest_ac2_python_exception_other_still_runs.rs"]
mod tooltest_ac2_python_exception_other_still_runs;
#[path = "warmpool_ac06_ac07_tool_run.rs"]
mod warmpool_ac06_ac07_tool_run;
#[path = "wasmkind_ac04_independent_of_sandbox_mechanism.rs"]
mod wasmkind_ac04_independent_of_sandbox_mechanism;
