// GENERATED by scripts/gen-test-suites.sh -- do not edit by hand.
// Regenerate with: scripts/gen-test-suites.sh
// Check for drift with: scripts/gen-test-suites.sh --check
//
// This file exists only to give cargo one test BINARY for the files listed
// below; it declares no tests of its own. Every included file keeps its
// original name, path, and test names (nextest's test list, with this
// suite's prefix stripped, is unchanged from before consolidation).
mod common;

#[path = "compat_ac13_ac14_middleware_logging_and_scope.rs"]
mod compat_ac13_ac14_middleware_logging_and_scope;
#[path = "hooks_ac10_healthz_event_counters.rs"]
mod hooks_ac10_healthz_event_counters;
#[path = "hooks_ac11_dedupe_header_idempotent.rs"]
mod hooks_ac11_dedupe_header_idempotent;
#[path = "hooks_ac1_hmac_sha256_valid_signature_runs.rs"]
mod hooks_ac1_hmac_sha256_valid_signature_runs;
#[path = "hooks_ac2_wrong_signature_401_no_run.rs"]
mod hooks_ac2_wrong_signature_401_no_run;
#[path = "hooks_ac3_stripe_style_stale_timestamp_401.rs"]
mod hooks_ac3_stripe_style_stale_timestamp_401;
#[path = "hooks_ac4_none_scheme_requires_allow_unverified.rs"]
mod hooks_ac4_none_scheme_requires_allow_unverified;
#[path = "hooks_ac5_rate_limit_429.rs"]
mod hooks_ac5_rate_limit_429;
#[path = "hooks_ac6_body_too_large_413.rs"]
mod hooks_ac6_body_too_large_413;
#[path = "hooks_ac7_trigger_test_creates_marked_run.rs"]
mod hooks_ac7_trigger_test_creates_marked_run;
#[path = "hooks_ac8_trigger_replay_new_run_trigger_ref.rs"]
mod hooks_ac8_trigger_replay_new_run_trigger_ref;
#[path = "hooks_ac9_paused_trigger_404.rs"]
mod hooks_ac9_paused_trigger_404;
#[path = "http_ac01_secret_redaction.rs"]
mod http_ac01_secret_redaction;
#[path = "http_ac02_publish_ssrf_literal.rs"]
mod http_ac02_publish_ssrf_literal;
#[path = "http_ac03_publish_secret_missing.rs"]
mod http_ac03_publish_secret_missing;
#[path = "http_ac04_args_invalid.rs"]
mod http_ac04_args_invalid;
#[path = "http_ac05_upstream_429_retry_after.rs"]
mod http_ac05_upstream_429_retry_after;
#[path = "http_ac06_upstream_timeout.rs"]
mod http_ac06_upstream_timeout;
#[path = "http_ac07_response_too_large.rs"]
mod http_ac07_response_too_large;
#[path = "http_ac08_template_error.rs"]
mod http_ac08_template_error;
#[path = "http_ac09_dns_rebinding.rs"]
mod http_ac09_dns_rebinding;
#[path = "http_ac10_concurrency_overhead.rs"]
mod http_ac10_concurrency_overhead;
#[path = "http_ac11_redirect_not_followed.rs"]
mod http_ac11_redirect_not_followed;
#[path = "http_ac12_tool_test.rs"]
mod http_ac12_tool_test;
#[path = "http_ac13_rate_limit.rs"]
mod http_ac13_rate_limit;
#[path = "http_ac14_bridge_envelope_payload.rs"]
mod http_ac14_bridge_envelope_payload;
#[path = "http_ac15_upstream_bridge_declarative.rs"]
mod http_ac15_upstream_bridge_declarative;
#[path = "http_ac16_upstream_bridge_errors.rs"]
mod http_ac16_upstream_bridge_errors;
#[path = "http_ac17_upstream_egress_policy.rs"]
mod http_ac17_upstream_egress_policy;
#[path = "http_ac18_bridge_test_dry_run.rs"]
mod http_ac18_bridge_test_dry_run;
#[path = "infer_ac05_ac06_ac07_http_schema.rs"]
mod infer_ac05_ac06_ac07_http_schema;
#[path = "infer_ac14_latency_budget.rs"]
mod infer_ac14_latency_budget;
#[path = "infer_ac17_no_execution.rs"]
mod infer_ac17_no_execution;
#[path = "kindhonor_ac1_http_kind_honored.rs"]
mod kindhonor_ac1_http_kind_honored;
#[path = "kindhonor_ac3_spec_test_reports_kind.rs"]
mod kindhonor_ac3_spec_test_reports_kind;
#[path = "kindhonor_ac4_initialize_instructions_mention_kind.rs"]
mod kindhonor_ac4_initialize_instructions_mention_kind;
#[path = "kindhonor_ac5_replay_cost_optimizer_shape.rs"]
mod kindhonor_ac5_replay_cost_optimizer_shape;
#[path = "kindhonor_ac6_tools_list_meta_kind.rs"]
mod kindhonor_ac6_tools_list_meta_kind;
#[path = "limits_ac05_signup_burst_atomic.rs"]
mod limits_ac05_signup_burst_atomic;
#[path = "metering_ac01_stripe_customer_id_null_default.rs"]
mod metering_ac01_stripe_customer_id_null_default;
#[path = "metering_ac02_webhook_stores_stripe_customer_id.rs"]
mod metering_ac02_webhook_stores_stripe_customer_id;
#[path = "metering_ac03_checkout_metered_line_item.rs"]
mod metering_ac03_checkout_metered_line_item;
#[path = "metering_ac04_emits_pro_calls_only.rs"]
mod metering_ac04_emits_pro_calls_only;
#[path = "metering_ac05_crash_replay.rs"]
mod metering_ac05_crash_replay;
#[path = "metering_ac06_failure_leaves_state_unmoved.rs"]
mod metering_ac06_failure_leaves_state_unmoved;
#[path = "metering_ac07_batches_cap_at_100.rs"]
mod metering_ac07_batches_cap_at_100;
#[path = "metering_ac08_healthz_meter_lag.rs"]
mod metering_ac08_healthz_meter_lag;
#[path = "metering_ac09_deploy_units_verify.rs"]
mod metering_ac09_deploy_units_verify;
#[path = "metering_ac11_admin_meter_status.rs"]
mod metering_ac11_admin_meter_status;
#[path = "metering_ac12_billing_status_stripe_reported_usage.rs"]
mod metering_ac12_billing_status_stripe_reported_usage;
#[path = "metering_billing_status_emitted_this_month.rs"]
mod metering_billing_status_emitted_this_month;
#[path = "migration_compat_headers.rs"]
mod migration_compat_headers;
#[path = "minimal_ac1_anonymous_ok_only.rs"]
mod minimal_ac1_anonymous_ok_only;
#[path = "minimal_ac2_admin_full_document.rs"]
mod minimal_ac2_admin_full_document;
#[path = "minimal_ac3_wrong_bearer_matches_anonymous.rs"]
mod minimal_ac3_wrong_bearer_matches_anonymous;
#[path = "minimal_ac4_liveness_failure_returns_5xx.rs"]
mod minimal_ac4_liveness_failure_returns_5xx;
#[path = "minimal_ac5_tenant_bearer_gets_anonymous_body.rs"]
mod minimal_ac5_tenant_bearer_gets_anonymous_body;
#[path = "proptest_invariants.rs"]
mod proptest_invariants;
