// GENERATED by scripts/gen-test-suites.sh -- do not edit by hand.
// Regenerate with: scripts/gen-test-suites.sh
// Check for drift with: scripts/gen-test-suites.sh --check
//
// This file exists only to give cargo one test BINARY for the files listed
// below; it declares no tests of its own. Every included file keeps its
// original name, path, and test names (nextest's test list, with this
// suite's prefix stripped, is unchanged from before consolidation).
mod common;
mod ci_sandbox_support;
#[path = "support/chart_fixture.rs"]
mod chart_fixture;
#[path = "support/docs_qa.rs"]
mod docs_qa;
#[path = "support/egress_proxy_lock.rs"]
mod egress_proxy_lock;
#[path = "support/federation.rs"]
mod federation;
#[path = "support/host.rs"]
#[allow(dead_code)]
mod host;
#[path = "support/oauth.rs"]
mod oauth;
#[path = "support/uptime_probes.rs"]
mod uptime_probes;

#[path = "ac17_kind_conformance.rs"]
mod ac17_kind_conformance;
#[path = "chainhost_ac05_quickstart_chain_example_resolves.rs"]
mod chainhost_ac05_quickstart_chain_example_resolves;
#[path = "chanbridge_ac01_python_channel_post_seq_and_host_sees_tenant.rs"]
mod chanbridge_ac01_python_channel_post_seq_and_host_sees_tenant;
#[path = "chanbridge_ac02_python_msg_send_reaches_inbox_with_thread_id.rs"]
mod chanbridge_ac02_python_msg_send_reaches_inbox_with_thread_id;
#[path = "chanbridge_ac03_msg_send_quota_raises_bridge_error_nothing_sent.rs"]
mod chanbridge_ac03_msg_send_quota_raises_bridge_error_nothing_sent;
#[path = "chanbridge_ac04_tool_test_dry_run_reports_would_post_no_write_no_trigger.rs"]
mod chanbridge_ac04_tool_test_dry_run_reports_would_post_no_write_no_trigger;
#[path = "chanbridge_ac05_channel_post_loop_fails_at_state_ops_per_call_max.rs"]
mod chanbridge_ac05_channel_post_loop_fails_at_state_ops_per_call_max;
#[path = "chanbridge_ac07_channel_read_ack_resumes_from_stored_cursor.rs"]
mod chanbridge_ac07_channel_read_ack_resumes_from_stored_cursor;
#[path = "chart_ac11_python_bridge_returns_chart_v1.rs"]
mod chart_ac11_python_bridge_returns_chart_v1;
#[path = "ci_sandbox_ac02_capable_env_never_skips.rs"]
mod ci_sandbox_ac02_capable_env_never_skips;
#[path = "ci_sandbox_ac05_ci_var_alone_never_skips.rs"]
mod ci_sandbox_ac05_ci_var_alone_never_skips;
#[path = "ci_sandbox_ac07_docs_state_the_capability_requirement.rs"]
mod ci_sandbox_ac07_docs_state_the_capability_requirement;
#[path = "compose_ac1_python_call_child_result.rs"]
mod compose_ac1_python_call_child_result;
#[path = "compose_ac2_child_exception_propagates.rs"]
mod compose_ac2_child_exception_propagates;
#[path = "docsqa_ac01_recipe_end_to_end.rs"]
mod docsqa_ac01_recipe_end_to_end;
#[path = "docsqa_ac02_quota_inside_free_plan_knobs.rs"]
mod docsqa_ac02_quota_inside_free_plan_knobs;
#[path = "docsqa_ac03_llms_txt_section_matches_script.rs"]
mod docsqa_ac03_llms_txt_section_matches_script;
#[path = "docsqa_ac04_updated_document_changes_the_answer.rs"]
mod docsqa_ac04_updated_document_changes_the_answer;
#[path = "docsqa_ac05_plugin_command_runs_the_script.rs"]
mod docsqa_ac05_plugin_command_runs_the_script;
#[path = "docsqa_ac07_embeddings_reports_both_hit_rates.rs"]
mod docsqa_ac07_embeddings_reports_both_hit_rates;
#[path = "docsqa_ac08_zero_passages_is_structured_not_an_error.rs"]
mod docsqa_ac08_zero_passages_is_structured_not_an_error;
#[path = "docstore_ac09_python_mcphost_docs_get_without_tool_call.rs"]
mod docstore_ac09_python_mcphost_docs_get_without_tool_call;
#[path = "enduser_ac01_oauth_python_env_and_calls_row.rs"]
mod enduser_ac01_oauth_python_env_and_calls_row;
#[path = "enduser_ac04_no_identity_env_unset_and_calls_row_null.rs"]
mod enduser_ac04_no_identity_env_unset_and_calls_row_null;
#[path = "envelope_ac2_python_object_declared_output_promoted.rs"]
mod envelope_ac2_python_object_declared_output_promoted;
#[path = "envelope_ac3_python_scalar_promotion_warns.rs"]
mod envelope_ac3_python_scalar_promotion_warns;
#[path = "envelope_ac5_replay_recorded_sessions.rs"]
mod envelope_ac5_replay_recorded_sessions;
#[path = "fedlogin_ac03_python_env_and_whoami.rs"]
mod fedlogin_ac03_python_env_and_whoami;
#[path = "firstpub_ac01_quickstart_starter_tool.rs"]
mod firstpub_ac01_quickstart_starter_tool;
#[path = "firstpub_ac02_sandbox_unavailable_retry.rs"]
mod firstpub_ac02_sandbox_unavailable_retry;
#[path = "firstpub_ac03_dry_run_gates.rs"]
mod firstpub_ac03_dry_run_gates;
#[path = "firstpub_ac04_real_publish_carries_gates.rs"]
mod firstpub_ac04_real_publish_carries_gates;
#[path = "firstpub_ac05_stub_flag_in_tools_list.rs"]
mod firstpub_ac05_stub_flag_in_tools_list;
#[path = "firstpub_ac06_get_info_no_echo_steering.rs"]
mod firstpub_ac06_get_info_no_echo_steering;
#[path = "firstpub_ac07_llms_txt_first_run_executes.rs"]
mod firstpub_ac07_llms_txt_first_run_executes;
#[path = "firstpub_ac08_quickstart_http_starter.rs"]
mod firstpub_ac08_quickstart_http_starter;
#[path = "infer_ac01_ac02_ac03_python_schema.rs"]
mod infer_ac01_ac02_ac03_python_schema;
#[path = "infer_ac04_python_explicit_schema.rs"]
mod infer_ac04_python_explicit_schema;
#[path = "infer_ac08_ac09_python_requirements.rs"]
mod infer_ac08_ac09_python_requirements;
#[path = "infer_ac10_unmapped_import_fails.rs"]
mod infer_ac10_unmapped_import_fails;
#[path = "infer_ac11_unresolvable_keys_fail.rs"]
mod infer_ac11_unresolvable_keys_fail;
#[path = "infer_ac13_deterministic_schema.rs"]
mod infer_ac13_deterministic_schema;
#[path = "infer_ac15_tool_test_uses_inferred_schema.rs"]
mod infer_ac15_tool_test_uses_inferred_schema;
#[path = "infer_ac16_syntax_error_precedence.rs"]
mod infer_ac16_syntax_error_precedence;
#[path = "kindhonor_ac2_kind_mismatch_refused.rs"]
mod kindhonor_ac2_kind_mismatch_refused;
#[path = "kindroute_ac04_unknown_kind_carries_recipe_hints.rs"]
mod kindroute_ac04_unknown_kind_carries_recipe_hints;
#[path = "kindroute_ac05_startup_aliases_and_recipe_tools_are_registered.rs"]
mod kindroute_ac05_startup_aliases_and_recipe_tools_are_registered;
#[path = "limits_ac01_declared_timeout_honored.rs"]
mod limits_ac01_declared_timeout_honored;
#[path = "limits_ac02_default_timeout_when_undeclared.rs"]
mod limits_ac02_default_timeout_when_undeclared;
#[path = "limits_ac03_output_too_large.rs"]
mod limits_ac03_output_too_large;
#[path = "limits_ac04_tenant_admission_control.rs"]
mod limits_ac04_tenant_admission_control;
#[path = "limits_ac06_quickstart_docs_match_constants.rs"]
mod limits_ac06_quickstart_docs_match_constants;
#[path = "limits_ac07_process_fork_storm_capped.rs"]
mod limits_ac07_process_fork_storm_capped;
#[path = "limits_ac08_usage_capacity_refusals.rs"]
mod limits_ac08_usage_capacity_refusals;
#[path = "lineage_ac01_source_scan_registers_table_edge.rs"]
mod lineage_ac01_source_scan_registers_table_edge;
#[path = "lineage_ac12_python_bridge_trace_matches_tool.rs"]
mod lineage_ac12_python_bridge_trace_matches_tool;
#[path = "mcphost_database_in_a_minute_ac02_all_rows_present.rs"]
mod mcphost_database_in_a_minute_ac02_all_rows_present;
#[path = "mcphost_database_in_a_minute_ac03_query_answers_match_fixture.rs"]
mod mcphost_database_in_a_minute_ac03_query_answers_match_fixture;
#[path = "mcphost_database_in_a_minute_ac04_query_rejects_like_and_raw_sql.rs"]
mod mcphost_database_in_a_minute_ac04_query_rejects_like_and_raw_sql;
#[path = "mcphost_database_in_a_minute_ac05_signup_events_source_tagged.rs"]
mod mcphost_database_in_a_minute_ac05_signup_events_source_tagged;
#[path = "mcphost_database_in_a_minute_ac07_synthorg_task_five_completions.rs"]
mod mcphost_database_in_a_minute_ac07_synthorg_task_five_completions;
#[path = "mcphost_database_in_a_minute_ac09_csv_import_batches_internally.rs"]
mod mcphost_database_in_a_minute_ac09_csv_import_batches_internally;
#[path = "mcphost_python_dependency_policy_ac01_lock_stored_and_require_hashes.rs"]
mod mcphost_python_dependency_policy_ac01_lock_stored_and_require_hashes;
#[path = "mcphost_python_dependency_policy_ac02_rebuild_matches_lock.rs"]
mod mcphost_python_dependency_policy_ac02_rebuild_matches_lock;
#[path = "mcphost_python_dependency_policy_ac03_advisory_fails_publish.rs"]
mod mcphost_python_dependency_policy_ac03_advisory_fails_publish;
#[path = "mcphost_python_dependency_policy_ac04_free_tenant_network_none_default.rs"]
mod mcphost_python_dependency_policy_ac04_free_tenant_network_none_default;
#[path = "mcphost_python_dependency_policy_ac05_near_name_denied.rs"]
mod mcphost_python_dependency_policy_ac05_near_name_denied;
#[path = "mcphost_python_dependency_policy_ac07_supplied_lock_stored_without_reresolving.rs"]
mod mcphost_python_dependency_policy_ac07_supplied_lock_stored_without_reresolving;
#[path = "mcphost_python_dependency_policy_ac08_reaudit_flags_new_advisory.rs"]
mod mcphost_python_dependency_policy_ac08_reaudit_flags_new_advisory;
#[path = "mcphost_python_dependency_policy_ac09_admin_usage_counts_network_and_advisories.rs"]
mod mcphost_python_dependency_policy_ac09_admin_usage_counts_network_and_advisories;
#[path = "mcphost_sandbox_egress_allowlist_ac01_free_publish_public_refused.rs"]
mod mcphost_sandbox_egress_allowlist_ac01_free_publish_public_refused;
#[path = "mcphost_sandbox_egress_allowlist_ac02_free_publish_egress_refused.rs"]
mod mcphost_sandbox_egress_allowlist_ac02_free_publish_egress_refused;
#[path = "mcphost_sandbox_egress_allowlist_ac03_pro_no_proxy_egress_unavailable.rs"]
mod mcphost_sandbox_egress_allowlist_ac03_pro_no_proxy_egress_unavailable;
#[path = "mcphost_sandbox_egress_allowlist_ac04_egress_proxy_command_and_env.rs"]
mod mcphost_sandbox_egress_allowlist_ac04_egress_proxy_command_and_env;
#[path = "mcphost_sandbox_egress_allowlist_ac06_downgrade_then_upgrade_republish_hint.rs"]
mod mcphost_sandbox_egress_allowlist_ac06_downgrade_then_upgrade_republish_hint;
#[path = "mcphost_sandbox_egress_allowlist_ac07_healthz_network_denied_counters.rs"]
mod mcphost_sandbox_egress_allowlist_ac07_healthz_network_denied_counters;
#[path = "mcphost_sandbox_egress_allowlist_ac08_concurrent_free_publishes_refused.rs"]
mod mcphost_sandbox_egress_allowlist_ac08_concurrent_free_publishes_refused;
#[path = "mcphost_sandbox_egress_allowlist_ac10_uptime_probes_fixture_no_longer_free.rs"]
mod mcphost_sandbox_egress_allowlist_ac10_uptime_probes_fixture_no_longer_free;
#[path = "mcphost_shared_tool_spec_readback_ac01_group_member_reads_spec.rs"]
mod mcphost_shared_tool_spec_readback_ac01_group_member_reads_spec;
#[path = "mcphost_shared_tool_spec_readback_ac02_tool_list_shows_expose_spec.rs"]
mod mcphost_shared_tool_spec_readback_ac02_tool_list_shows_expose_spec;
#[path = "mcphost_shared_tool_spec_readback_ac03_redacts_env_and_secrets.rs"]
mod mcphost_shared_tool_spec_readback_ac03_redacts_env_and_secrets;
#[path = "mcphost_shared_tool_spec_readback_ac04_spec_not_exposed_refusal.rs"]
mod mcphost_shared_tool_spec_readback_ac04_spec_not_exposed_refusal;
#[path = "mcphost_shared_tool_spec_readback_ac05_not_shared_same_not_found_shape.rs"]
mod mcphost_shared_tool_spec_readback_ac05_not_shared_same_not_found_shape;
#[path = "mcphost_shared_tool_spec_readback_ac06_unshare_then_reshare_without_flag.rs"]
mod mcphost_shared_tool_spec_readback_ac06_unshare_then_reshare_without_flag;
#[path = "mcphost_shared_tool_spec_readback_ac08_fifty_concurrent_reads_p95.rs"]
mod mcphost_shared_tool_spec_readback_ac08_fifty_concurrent_reads_p95;
#[path = "mcphost_shared_tool_spec_readback_ac09_spec_reads_counter.rs"]
mod mcphost_shared_tool_spec_readback_ac09_spec_reads_counter;
#[path = "mcphost_shared_tool_spec_readback_ac10_two_tenant_spec_read_and_calls_listing.rs"]
mod mcphost_shared_tool_spec_readback_ac10_two_tenant_spec_read_and_calls_listing;
#[path = "mcphost_team_memory_ac02_b_remember_writer.rs"]
mod mcphost_team_memory_ac02_b_remember_writer;
#[path = "mcphost_team_memory_ac03_c_recall_shows_writer.rs"]
mod mcphost_team_memory_ac03_c_recall_shows_writer;
#[path = "mcphost_team_memory_ac04_group_remove_revokes_c.rs"]
mod mcphost_team_memory_ac04_group_remove_revokes_c;
#[path = "mcphost_team_memory_ac05_recall_limit_capped_at_50.rs"]
mod mcphost_team_memory_ac05_recall_limit_capped_at_50;
#[path = "mcphost_team_memory_ac07_synthorg_task_five_completions.rs"]
mod mcphost_team_memory_ac07_synthorg_task_five_completions;
#[path = "mcphost_team_memory_ac09_forget_refused_for_non_writer_non_owner.rs"]
mod mcphost_team_memory_ac09_forget_refused_for_non_writer_non_owner;
#[path = "mcphost_uptime_probes_ac02_checks_two_rows_per_target.rs"]
mod mcphost_uptime_probes_ac02_checks_two_rows_per_target;
#[path = "mcphost_uptime_probes_ac03_status_up_pct_and_down_since.rs"]
mod mcphost_uptime_probes_ac03_status_up_pct_and_down_since;
#[path = "mcphost_uptime_probes_ac04_retention_deletes_old_rows.rs"]
mod mcphost_uptime_probes_ac04_retention_deletes_old_rows;
#[path = "mcphost_uptime_probes_ac05_target_cap_at_20.rs"]
mod mcphost_uptime_probes_ac05_target_cap_at_20;
#[path = "mcphost_uptime_probes_ac07_synthorg_task_five_completions.rs"]
mod mcphost_uptime_probes_ac07_synthorg_task_five_completions;
#[path = "mcphost_uptime_probes_ac09_down_since_flip_sends_inbox.rs"]
mod mcphost_uptime_probes_ac09_down_since_flip_sends_inbox;
#[path = "plainenv_ac01_env_reaches_process.rs"]
mod plainenv_ac01_env_reaches_process;
#[path = "plainenv_ac02_invalid_names_refused.rs"]
mod plainenv_ac02_invalid_names_refused;
#[path = "plainenv_ac03_bounds.rs"]
mod plainenv_ac03_bounds;
#[path = "plainenv_ac04_secret_env_collision.rs"]
mod plainenv_ac04_secret_env_collision;
#[path = "plainenv_ac05_tool_test_environment_rendering.rs"]
mod plainenv_ac05_tool_test_environment_rendering;
#[path = "plainenv_ac06_env_only_tool_under_sandbox.rs"]
mod plainenv_ac06_env_only_tool_under_sandbox;
#[path = "plainenv_ac07_docs_and_tool_list.rs"]
mod plainenv_ac07_docs_and_tool_list;
#[path = "plainenv_ac08_warm_pool_invalidates_on_env_change.rs"]
mod plainenv_ac08_warm_pool_invalidates_on_env_change;
#[path = "plainenv_ac10_admin_reports_env_names_and_size.rs"]
mod plainenv_ac10_admin_reports_env_names_and_size;
#[path = "publishfirsttry_ac03_ac04_quickstart.rs"]
mod publishfirsttry_ac03_ac04_quickstart;
#[path = "publishfirsttry_ac06_docs_shared_source.rs"]
mod publishfirsttry_ac06_docs_shared_source;
#[path = "python_ac01_no_deps_cpu_memory.rs"]
mod python_ac01_no_deps_cpu_memory;
#[path = "python_ac02_requirements_build_and_building_state.rs"]
mod python_ac02_requirements_build_and_building_state;
#[path = "python_ac03_invalid_source_rejected.rs"]
mod python_ac03_invalid_source_rejected;
#[path = "python_ac04_disallowed_requirement.rs"]
mod python_ac04_disallowed_requirement;
#[path = "python_ac05_exception_traceback.rs"]
mod python_ac05_exception_traceback;
#[path = "python_ac06_timeout.rs"]
mod python_ac06_timeout;
#[path = "python_ac07_oom.rs"]
mod python_ac07_oom;
#[path = "python_ac08_network_none_blocks.rs"]
mod python_ac08_network_none_blocks;
#[path = "python_ac09_filesystem_isolation.rs"]
mod python_ac09_filesystem_isolation;
#[path = "python_ac10_fork_bomb_contained.rs"]
mod python_ac10_fork_bomb_contained;
#[path = "python_ac11_secret_redaction.rs"]
mod python_ac11_secret_redaction;
#[path = "python_ac12_republish_atomic.rs"]
mod python_ac12_republish_atomic;
#[path = "python_ac13_capacity_admission.rs"]
mod python_ac13_capacity_admission;
#[path = "python_ac14_cpu_budget_rate_limit.rs"]
mod python_ac14_cpu_budget_rate_limit;
#[path = "runenvelope_ac1_call_and_tool_run_parity.rs"]
mod runenvelope_ac1_call_and_tool_run_parity;
#[path = "runenvelope_ac2_no_declared_outputs_raw_payload.rs"]
mod runenvelope_ac2_no_declared_outputs_raw_payload;
#[path = "runenvelope_ac3_descriptor_and_decision_table_name_envelope.rs"]
mod runenvelope_ac3_descriptor_and_decision_table_name_envelope;
#[path = "runenvelope_ac4_no_calls_row_with_payload.rs"]
mod runenvelope_ac4_no_calls_row_with_payload;
