// GENERATED by scripts/gen-test-suites.sh -- do not edit by hand.
// Regenerate with: scripts/gen-test-suites.sh
// Check for drift with: scripts/gen-test-suites.sh --check
//
// This file exists only to give cargo one test BINARY for the files listed
// below; it declares no tests of its own. Every included file keeps its
// original name, path, and test names (nextest's test list, with this
// suite's prefix stripped, is unchanged from before consolidation).
mod common;
mod ci_sandbox_support;

#[path = "ac17_kind_conformance.rs"]
mod ac17_kind_conformance;
#[path = "ci_sandbox_ac02_capable_env_never_skips.rs"]
mod ci_sandbox_ac02_capable_env_never_skips;
#[path = "ci_sandbox_ac05_ci_var_alone_never_skips.rs"]
mod ci_sandbox_ac05_ci_var_alone_never_skips;
#[path = "ci_sandbox_ac07_docs_state_the_capability_requirement.rs"]
mod ci_sandbox_ac07_docs_state_the_capability_requirement;
#[path = "compose_ac1_python_call_child_result.rs"]
mod compose_ac1_python_call_child_result;
#[path = "compose_ac2_child_exception_propagates.rs"]
mod compose_ac2_child_exception_propagates;
#[path = "envelope_ac2_python_object_declared_output_promoted.rs"]
mod envelope_ac2_python_object_declared_output_promoted;
#[path = "envelope_ac3_python_scalar_promotion_warns.rs"]
mod envelope_ac3_python_scalar_promotion_warns;
#[path = "envelope_ac5_replay_recorded_sessions.rs"]
mod envelope_ac5_replay_recorded_sessions;
#[path = "infer_ac01_ac02_ac03_python_schema.rs"]
mod infer_ac01_ac02_ac03_python_schema;
#[path = "infer_ac04_python_explicit_schema.rs"]
mod infer_ac04_python_explicit_schema;
#[path = "infer_ac08_ac09_python_requirements.rs"]
mod infer_ac08_ac09_python_requirements;
#[path = "infer_ac10_unmapped_import_fails.rs"]
mod infer_ac10_unmapped_import_fails;
#[path = "infer_ac11_unresolvable_keys_fail.rs"]
mod infer_ac11_unresolvable_keys_fail;
#[path = "infer_ac13_deterministic_schema.rs"]
mod infer_ac13_deterministic_schema;
#[path = "infer_ac15_tool_test_uses_inferred_schema.rs"]
mod infer_ac15_tool_test_uses_inferred_schema;
#[path = "infer_ac16_syntax_error_precedence.rs"]
mod infer_ac16_syntax_error_precedence;
#[path = "kindhonor_ac2_kind_mismatch_refused.rs"]
mod kindhonor_ac2_kind_mismatch_refused;
#[path = "limits_ac01_declared_timeout_honored.rs"]
mod limits_ac01_declared_timeout_honored;
#[path = "limits_ac02_default_timeout_when_undeclared.rs"]
mod limits_ac02_default_timeout_when_undeclared;
#[path = "limits_ac03_output_too_large.rs"]
mod limits_ac03_output_too_large;
#[path = "limits_ac04_tenant_admission_control.rs"]
mod limits_ac04_tenant_admission_control;
#[path = "limits_ac06_quickstart_docs_match_constants.rs"]
mod limits_ac06_quickstart_docs_match_constants;
#[path = "limits_ac07_process_fork_storm_capped.rs"]
mod limits_ac07_process_fork_storm_capped;
#[path = "limits_ac08_usage_capacity_refusals.rs"]
mod limits_ac08_usage_capacity_refusals;
#[path = "publishfirsttry_ac03_ac04_quickstart.rs"]
mod publishfirsttry_ac03_ac04_quickstart;
#[path = "publishfirsttry_ac06_docs_shared_source.rs"]
mod publishfirsttry_ac06_docs_shared_source;
#[path = "python_ac01_no_deps_cpu_memory.rs"]
mod python_ac01_no_deps_cpu_memory;
#[path = "python_ac02_requirements_build_and_building_state.rs"]
mod python_ac02_requirements_build_and_building_state;
#[path = "python_ac03_invalid_source_rejected.rs"]
mod python_ac03_invalid_source_rejected;
#[path = "python_ac04_disallowed_requirement.rs"]
mod python_ac04_disallowed_requirement;
#[path = "python_ac05_exception_traceback.rs"]
mod python_ac05_exception_traceback;
#[path = "python_ac06_timeout.rs"]
mod python_ac06_timeout;
#[path = "python_ac07_oom.rs"]
mod python_ac07_oom;
#[path = "python_ac08_network_none_blocks.rs"]
mod python_ac08_network_none_blocks;
#[path = "python_ac09_filesystem_isolation.rs"]
mod python_ac09_filesystem_isolation;
#[path = "python_ac10_fork_bomb_contained.rs"]
mod python_ac10_fork_bomb_contained;
#[path = "python_ac11_secret_redaction.rs"]
mod python_ac11_secret_redaction;
#[path = "python_ac12_republish_atomic.rs"]
mod python_ac12_republish_atomic;
#[path = "python_ac13_capacity_admission.rs"]
mod python_ac13_capacity_admission;
#[path = "python_ac14_cpu_budget_rate_limit.rs"]
mod python_ac14_cpu_budget_rate_limit;
#[path = "runs_ac01_async_job_runs_progress_and_result.rs"]
mod runs_ac01_async_job_runs_progress_and_result;
#[path = "runs_ac02_job_max_s_timeout.rs"]
mod runs_ac02_job_max_s_timeout;
#[path = "runs_ac03_progress_shape.rs"]
mod runs_ac03_progress_shape;
#[path = "runs_ac04_cancel_kills_sandbox.rs"]
mod runs_ac04_cancel_kills_sandbox;
#[path = "runs_ac06_jobs_concurrent_gate.rs"]
mod runs_ac06_jobs_concurrent_gate;
#[path = "runtime_ac1_range_typeerror_fixture.rs"]
mod runtime_ac1_range_typeerror_fixture;
#[path = "runtime_ac2_tool_code_phase_and_line.rs"]
mod runtime_ac2_tool_code_phase_and_line;
#[path = "runtime_ac3_args_coercion_phase_and_types.rs"]
mod runtime_ac3_args_coercion_phase_and_types;
#[path = "runtime_ac4_publish_and_first_call_latency.rs"]
mod runtime_ac4_publish_and_first_call_latency;
#[path = "runtime_ac5_assignment_expression_message.rs"]
mod runtime_ac5_assignment_expression_message;
#[path = "runtime_ac6_readme_documents_restriction.rs"]
mod runtime_ac6_readme_documents_restriction;
#[path = "sandboxready_ac10_sandbox_check_subcommand.rs"]
mod sandboxready_ac10_sandbox_check_subcommand;
#[path = "sandboxready_ac1_ac2_healthz_startup.rs"]
mod sandboxready_ac1_ac2_healthz_startup;
#[path = "sandboxready_ac3_ac4_publish_rejection.rs"]
mod sandboxready_ac3_ac4_publish_rejection;
#[path = "sandboxready_ac5_admin_recheck_recovers.rs"]
mod sandboxready_ac5_admin_recheck_recovers;
#[path = "sandboxready_ac6_periodic_recheck_flips_unready.rs"]
mod sandboxready_ac6_periodic_recheck_flips_unready;
#[path = "sandboxready_ac8_get_info_and_description_note.rs"]
mod sandboxready_ac8_get_info_and_description_note;
#[path = "sandboxready_ac9_failure_classification.rs"]
mod sandboxready_ac9_failure_classification;
