// GENERATED by scripts/gen-test-suites.sh -- do not edit by hand.
// Regenerate with: scripts/gen-test-suites.sh
// Check for drift with: scripts/gen-test-suites.sh --check
//
// This file exists only to give cargo one test BINARY for the files listed
// below; it declares no tests of its own. Every included file keeps its
// original name, path, and test names (nextest's test list, with this
// suite's prefix stripped, is unchanged from before consolidation).
mod common;
mod ci_sandbox_support;
#[path = "support/host.rs"]
#[allow(dead_code)]
mod host;
#[path = "support/uptime_probes.rs"]
mod uptime_probes;

#[path = "ac17_kind_conformance.rs"]
mod ac17_kind_conformance;
#[path = "ci_sandbox_ac02_capable_env_never_skips.rs"]
mod ci_sandbox_ac02_capable_env_never_skips;
#[path = "ci_sandbox_ac05_ci_var_alone_never_skips.rs"]
mod ci_sandbox_ac05_ci_var_alone_never_skips;
#[path = "ci_sandbox_ac07_docs_state_the_capability_requirement.rs"]
mod ci_sandbox_ac07_docs_state_the_capability_requirement;
#[path = "compose_ac1_python_call_child_result.rs"]
mod compose_ac1_python_call_child_result;
#[path = "compose_ac2_child_exception_propagates.rs"]
mod compose_ac2_child_exception_propagates;
#[path = "envelope_ac2_python_object_declared_output_promoted.rs"]
mod envelope_ac2_python_object_declared_output_promoted;
#[path = "envelope_ac3_python_scalar_promotion_warns.rs"]
mod envelope_ac3_python_scalar_promotion_warns;
#[path = "envelope_ac5_replay_recorded_sessions.rs"]
mod envelope_ac5_replay_recorded_sessions;
#[path = "infer_ac01_ac02_ac03_python_schema.rs"]
mod infer_ac01_ac02_ac03_python_schema;
#[path = "infer_ac04_python_explicit_schema.rs"]
mod infer_ac04_python_explicit_schema;
#[path = "infer_ac08_ac09_python_requirements.rs"]
mod infer_ac08_ac09_python_requirements;
#[path = "infer_ac10_unmapped_import_fails.rs"]
mod infer_ac10_unmapped_import_fails;
#[path = "infer_ac11_unresolvable_keys_fail.rs"]
mod infer_ac11_unresolvable_keys_fail;
#[path = "infer_ac13_deterministic_schema.rs"]
mod infer_ac13_deterministic_schema;
#[path = "infer_ac15_tool_test_uses_inferred_schema.rs"]
mod infer_ac15_tool_test_uses_inferred_schema;
#[path = "infer_ac16_syntax_error_precedence.rs"]
mod infer_ac16_syntax_error_precedence;
#[path = "kindhonor_ac2_kind_mismatch_refused.rs"]
mod kindhonor_ac2_kind_mismatch_refused;
#[path = "limits_ac01_declared_timeout_honored.rs"]
mod limits_ac01_declared_timeout_honored;
#[path = "limits_ac02_default_timeout_when_undeclared.rs"]
mod limits_ac02_default_timeout_when_undeclared;
#[path = "limits_ac03_output_too_large.rs"]
mod limits_ac03_output_too_large;
#[path = "limits_ac04_tenant_admission_control.rs"]
mod limits_ac04_tenant_admission_control;
#[path = "limits_ac06_quickstart_docs_match_constants.rs"]
mod limits_ac06_quickstart_docs_match_constants;
#[path = "limits_ac07_process_fork_storm_capped.rs"]
mod limits_ac07_process_fork_storm_capped;
#[path = "limits_ac08_usage_capacity_refusals.rs"]
mod limits_ac08_usage_capacity_refusals;
#[path = "mcphost_database_in_a_minute_ac02_all_rows_present.rs"]
mod mcphost_database_in_a_minute_ac02_all_rows_present;
#[path = "mcphost_database_in_a_minute_ac03_query_answers_match_fixture.rs"]
mod mcphost_database_in_a_minute_ac03_query_answers_match_fixture;
#[path = "mcphost_database_in_a_minute_ac04_query_rejects_like_and_raw_sql.rs"]
mod mcphost_database_in_a_minute_ac04_query_rejects_like_and_raw_sql;
#[path = "mcphost_database_in_a_minute_ac05_signup_events_source_tagged.rs"]
mod mcphost_database_in_a_minute_ac05_signup_events_source_tagged;
#[path = "mcphost_database_in_a_minute_ac07_synthorg_task_five_completions.rs"]
mod mcphost_database_in_a_minute_ac07_synthorg_task_five_completions;
#[path = "mcphost_database_in_a_minute_ac09_csv_import_batches_internally.rs"]
mod mcphost_database_in_a_minute_ac09_csv_import_batches_internally;
#[path = "mcphost_python_dependency_policy_ac01_lock_stored_and_require_hashes.rs"]
mod mcphost_python_dependency_policy_ac01_lock_stored_and_require_hashes;
#[path = "mcphost_python_dependency_policy_ac02_rebuild_matches_lock.rs"]
mod mcphost_python_dependency_policy_ac02_rebuild_matches_lock;
#[path = "mcphost_python_dependency_policy_ac03_advisory_fails_publish.rs"]
mod mcphost_python_dependency_policy_ac03_advisory_fails_publish;
#[path = "mcphost_python_dependency_policy_ac04_free_tenant_network_none_default.rs"]
mod mcphost_python_dependency_policy_ac04_free_tenant_network_none_default;
#[path = "mcphost_python_dependency_policy_ac05_near_name_denied.rs"]
mod mcphost_python_dependency_policy_ac05_near_name_denied;
#[path = "mcphost_python_dependency_policy_ac07_supplied_lock_stored_without_reresolving.rs"]
mod mcphost_python_dependency_policy_ac07_supplied_lock_stored_without_reresolving;
#[path = "mcphost_python_dependency_policy_ac08_reaudit_flags_new_advisory.rs"]
mod mcphost_python_dependency_policy_ac08_reaudit_flags_new_advisory;
#[path = "mcphost_python_dependency_policy_ac09_admin_usage_counts_network_and_advisories.rs"]
mod mcphost_python_dependency_policy_ac09_admin_usage_counts_network_and_advisories;
#[path = "mcphost_team_memory_ac02_b_remember_writer.rs"]
mod mcphost_team_memory_ac02_b_remember_writer;
#[path = "mcphost_team_memory_ac03_c_recall_shows_writer.rs"]
mod mcphost_team_memory_ac03_c_recall_shows_writer;
#[path = "mcphost_team_memory_ac04_group_remove_revokes_c.rs"]
mod mcphost_team_memory_ac04_group_remove_revokes_c;
#[path = "mcphost_team_memory_ac05_recall_limit_capped_at_50.rs"]
mod mcphost_team_memory_ac05_recall_limit_capped_at_50;
#[path = "mcphost_team_memory_ac07_synthorg_task_five_completions.rs"]
mod mcphost_team_memory_ac07_synthorg_task_five_completions;
#[path = "mcphost_team_memory_ac09_forget_refused_for_non_writer_non_owner.rs"]
mod mcphost_team_memory_ac09_forget_refused_for_non_writer_non_owner;
#[path = "mcphost_uptime_probes_ac02_checks_two_rows_per_target.rs"]
mod mcphost_uptime_probes_ac02_checks_two_rows_per_target;
#[path = "mcphost_uptime_probes_ac03_status_up_pct_and_down_since.rs"]
mod mcphost_uptime_probes_ac03_status_up_pct_and_down_since;
#[path = "mcphost_uptime_probes_ac04_retention_deletes_old_rows.rs"]
mod mcphost_uptime_probes_ac04_retention_deletes_old_rows;
#[path = "mcphost_uptime_probes_ac05_target_cap_at_20.rs"]
mod mcphost_uptime_probes_ac05_target_cap_at_20;
#[path = "mcphost_uptime_probes_ac07_synthorg_task_five_completions.rs"]
mod mcphost_uptime_probes_ac07_synthorg_task_five_completions;
#[path = "mcphost_uptime_probes_ac09_down_since_flip_sends_inbox.rs"]
mod mcphost_uptime_probes_ac09_down_since_flip_sends_inbox;
#[path = "plainenv_ac01_env_reaches_process.rs"]
mod plainenv_ac01_env_reaches_process;
#[path = "plainenv_ac02_invalid_names_refused.rs"]
mod plainenv_ac02_invalid_names_refused;
#[path = "plainenv_ac03_bounds.rs"]
mod plainenv_ac03_bounds;
#[path = "plainenv_ac04_secret_env_collision.rs"]
mod plainenv_ac04_secret_env_collision;
#[path = "plainenv_ac05_tool_test_environment_rendering.rs"]
mod plainenv_ac05_tool_test_environment_rendering;
#[path = "plainenv_ac06_env_only_tool_under_sandbox.rs"]
mod plainenv_ac06_env_only_tool_under_sandbox;
#[path = "plainenv_ac07_docs_and_tool_list.rs"]
mod plainenv_ac07_docs_and_tool_list;
#[path = "plainenv_ac08_warm_pool_invalidates_on_env_change.rs"]
mod plainenv_ac08_warm_pool_invalidates_on_env_change;
#[path = "plainenv_ac10_admin_reports_env_names_and_size.rs"]
mod plainenv_ac10_admin_reports_env_names_and_size;
