//! PRD-mcphost-first-hour-support-surface
//! AC4 (P0) — Given `billing::plans()`, When `gen-docs` runs, Then
//! `docs/plans.md` and `www/plans.html` are regenerated byte-identically,
//! and `/plans.json` equals the `billing.plans` tool output for the same
//! binary.
//!
//! `docs/plans.md`'s own "byte-identical to a fresh render" half is also
//! covered hermetically (no server, no tokio) by
//! `gendocs::tests::committed_plans_doc_matches_a_fresh_render` -- this file
//! covers the live half: `/plans.json` (the HTTP route) and `billing.plans`
//! (the MCP tool) must return exactly the same thing from one running
//! binary, and that same data must be what `docs/plans.md` was rendered
//! from. `www/plans.html` is a static shell that fetches `/plans.json`
//! client-side (see `help.rs`'s module doc comment) -- it carries no
//! baked-in catalog data to go stale, but `mcphost gen-docs` still
//! regenerates it from `gendocs::render_plans_html` byte-identically (its
//! own "byte-identical to a fresh render" half is covered hermetically by
//! `gendocs::tests::committed_plans_html_matches_a_fresh_render`, the exact
//! same pattern as `docs/plans.md`); this file's own
//! `plans_html_is_served_and_non_empty` confirms the live half -- it's
//! served non-empty (the served-pages test, AC6, covers it as a same-host
//! link from README/llms.txt too).

use crate::common;
use common::{McpClient, TestServer, extract_structured};
use serde_json::json;

#[tokio::test]
async fn plans_json_route_equals_billing_plans_tool_output() {
    let server = TestServer::start().await;
    let client = McpClient::new(&server.base_url);

    let tool_result = client
        .tools_call("billing.plans", json!({}))
        .await
        .expect("billing.plans should succeed unauthenticated");
    let tool_structured = extract_structured(&tool_result);

    let http = reqwest::Client::new();
    let json_route: serde_json::Value = http
        .get(format!("{}/plans.json", server.base_url))
        .send()
        .await
        .expect("GET /plans.json")
        .json()
        .await
        .expect("/plans.json body must be JSON");

    assert_eq!(
        tool_structured, json_route,
        "billing.plans tool output and /plans.json must be byte-for-byte the same"
    );
}

#[tokio::test]
async fn plans_html_is_served_and_non_empty() {
    let server = TestServer::start().await;
    let http = reqwest::Client::new();
    let resp = http
        .get(format!("{}/plans.html", server.base_url))
        .send()
        .await
        .expect("GET /plans.html");
    assert_eq!(resp.status(), reqwest::StatusCode::OK);
    let body = resp.text().await.expect("body");
    assert!(!body.is_empty());
    assert!(body.contains("/plans.json"), "plans.html must fetch the live catalog: {body}");
}

/// The hermetic half of AC4 (`docs/plans.md`), expressed here too (not just
/// in `gendocs`'s own unit test) so a reviewer reading this PRD's
/// `support_ac04_*` file sees the whole AC proven in one place.
#[test]
fn docs_plans_md_matches_a_fresh_render() {
    let committed = include_str!("../docs/plans.md");
    let fresh = mcphost::gendocs::render_plans_markdown(&mcphost::plans::PlanCatalog::default_catalog());
    assert_eq!(committed, fresh, "docs/plans.md has drifted -- run `mcphost gen-docs`");
}

/// AC4's other generated-file half (`www/plans.html`), expressed here too
/// for the same reason as `docs_plans_md_matches_a_fresh_render` above.
#[test]
fn www_plans_html_matches_a_fresh_render() {
    let committed = include_str!("../www/plans.html");
    let fresh = mcphost::gendocs::render_plans_html();
    assert_eq!(committed, fresh, "www/plans.html has drifted -- run `mcphost gen-docs`");
}
