#!/usr/bin/env bash
# gen-llms-full.sh — PRD-mcphost-agent-findability requirement 7:
# `llms-full.txt` is "the docs page rendered as one markdown file", per the
# llms.txt convention (llmstxt.org): llms.txt is the short index, llms-full.txt
# is every doc a crawler would otherwise have to follow links to find,
# concatenated into one file so it can be fetched in a single request.
#
# Source files, in the order they appear in the assembled output:
#   README.md            the canonical agent-readable doc (requirement 1)
#   docs/kinds/*.md       the three tool kinds (echo, http, python)
#   docs/benchmarks/*.md  every measured proof point cited from README/llms.txt
#   docs/receipts/*.md    supporting measurement receipts cited elsewhere
#
# Usage:
#   scripts/gen-llms-full.sh          regenerate www/llms-full.txt
#   scripts/gen-llms-full.sh --check  exit 1 if www/llms-full.txt is stale
set -uo pipefail
cd "$(dirname "$0")/.."

OUT="www/llms-full.txt"
MODE="${1:-write}"

render() {
  echo "# mcphost — full documentation"
  echo
  echo "> Generated by scripts/gen-llms-full.sh from README.md, docs/kinds/*.md,"
  echo "> docs/benchmarks/*.md and docs/receipts/*.md. See /llms.txt for the short"
  echo "> index. Do not hand-edit."
  echo

  echo "## README"
  echo
  cat README.md
  echo

  for f in docs/kinds/*.md; do
    [ -f "$f" ] || continue
    echo "## Kind: $(basename "$f" .md)"
    echo
    cat "$f"
    echo
  done

  for f in docs/benchmarks/*.md; do
    [ -f "$f" ] || continue
    echo "## Benchmark: $(basename "$f")"
    echo
    cat "$f"
    echo
  done

  for f in docs/receipts/*.md; do
    [ -f "$f" ] || continue
    echo "## Receipt: $(basename "$f")"
    echo
    cat "$f"
    echo
  done
}

case "$MODE" in
  --check)
    tmp="$(mktemp)"
    render > "$tmp"
    if diff -q "$tmp" "$OUT" > /dev/null 2>&1; then
      rm -f "$tmp"
      exit 0
    else
      echo "gen-llms-full.sh --check: $OUT is stale (run scripts/gen-llms-full.sh)" >&2
      rm -f "$tmp"
      exit 1
    fi
    ;;
  write|"")
    render > "$OUT"
    ;;
  *)
    echo "usage: $0 [--check]" >&2
    exit 2
    ;;
esac
