#!/usr/bin/env bash
# gen-oauth-scenarios-doc.sh -- PRD-mcphost-oauth-conformance-harness
# requirement 6: "docs/oauth-scenarios.md generated from the gold file (one
# table), linked from www/llms.txt operator notes." tests/oauthconf/
# scenarios.toml is the one source of truth (requirement 2: "scenario gold
# in data, not in test code"); this script is the only thing that writes
# docs/oauth-scenarios.md, so the doc can never drift from the gold file
# the gate actually runs against.
#
# Usage:
#   scripts/gen-oauth-scenarios-doc.sh          regenerate docs/oauth-scenarios.md
#   scripts/gen-oauth-scenarios-doc.sh --check  exit 1 if it's stale
set -uo pipefail
cd "$(dirname "$0")/.."

SOURCE="tests/oauthconf/scenarios.toml"
TARGET="docs/oauth-scenarios.md"
MODE="${1:-write}"

if [ ! -f "$SOURCE" ]; then
  echo "gen-oauth-scenarios-doc.sh: missing $SOURCE" >&2
  exit 2
fi

render() {
  python3 - "$SOURCE" <<'PY'
import sys
import tomllib

with open(sys.argv[1], "rb") as f:
    data = tomllib.load(f)

print("# OAuth conformance scenarios")
print()
print(
    "Generated by `scripts/gen-oauth-scenarios-doc.sh` from "
    "`tests/oauthconf/scenarios.toml` -- do not hand-edit. Every scenario "
    "the `oauthconf` gate runs (PRD-mcphost-oauth-conformance-harness) "
    "appears exactly once below."
)
print()
print("| scenario | family | owner PRD | expected verdict |")
print("|---|---|---|---|")
for s in data["scenario"]:
    print(f"| {s['name']} | {s['family']} | {s['owner_prd']} | {s['expected']} |")
PY
}

apply() {
  render > "$TARGET"
}

check() {
  local before after
  before="$(mktemp)"
  after="$(mktemp)"
  if [ -f "$TARGET" ]; then
    cp "$TARGET" "$before"
  else
    : > "$before"
  fi
  render > "$after"
  if diff -q "$before" "$after" > /dev/null; then
    rm -f "$before" "$after"
    return 0
  fi
  echo "gen-oauth-scenarios-doc.sh --check: $TARGET is stale (run scripts/gen-oauth-scenarios-doc.sh)" >&2
  diff -u "$before" "$after" >&2 || true
  rm -f "$before" "$after"
  return 1
}

case "$MODE" in
  --check)
    check
    ;;
  write|"")
    apply
    ;;
  *)
    echo "usage: $0 [--check]" >&2
    exit 2
    ;;
esac
