//! PRD-mcphost-host-tool-deprecation: the `host.*`/`billing.*` tool surface
//! as a versioned, diffable artifact.
//!
//! `contracts/host-tools.v1.json` (generated by `mcphost contract dump`,
//! requirement 1 / AC1) pins the input schema and `since` version of every
//! control-plane tool [`crate::handler::host_tool_descriptors`] builds. A
//! future PR that removes or narrows a field is caught by [`diff`] against
//! this committed baseline (requirements 2 and 5) unless
//! `contracts/deprecations.json` carries a matching, valid [`Deprecation`]
//! entry -- see that function's own doc for the exact two-gate rule.

use serde::{Deserialize, Serialize};
use serde_json::{Map, Value, json};

use crate::kinds::KindRegistry;

/// `host.whoami`'s `contract_version` (AC7) and this file's own
/// `contract_version` key.
pub const CONTRACT_VERSION: u32 = 1;

/// Default path (relative to the repo root / crate root `cargo test` runs
/// from) for the committed contract -- same "repo-relative, not
/// `$MCPHOST_DATA_DIR`-relative" convention `www/llms.txt` already uses in
/// `main.rs`'s `LlmsTxt` subcommand, since this is a static, committed
/// artifact, not per-deployment runtime data.
pub const DEFAULT_CONTRACT_PATH: &str = "contracts/host-tools.v1.json";

/// Default path for the deprecation ledger, same convention as
/// [`DEFAULT_CONTRACT_PATH`].
pub const DEFAULT_DEPRECATIONS_PATH: &str = "contracts/deprecations.json";

/// The `since` recorded for every tool that already existed when this
/// contract system shipped. This is deliberately NOT an attempt to
/// backfill each tool's true historical introduction version (that
/// history isn't recoverable from the source tree) -- it's the version as
/// of which this crate started tracking `since` at all, honestly labeled
/// as such rather than guessed per tool. A tool added after this baseline
/// (e.g. `host.changelog` itself, requirement 4 / AC6) gets its own,
/// later `since`.
pub const CONTRACT_BASELINE_SINCE: &str = "0.58.0";

/// `host.changelog`'s own `since` (requirement 4 / AC6: it must itself
/// show up as an addition). Kept in sync with `Cargo.toml`'s `version` by
/// this PRD's own version-bump commit -- see that commit's CHANGELOG.md
/// entry.
pub const HOST_CHANGELOG_SINCE: &str = "0.58.1";

/// requirement 1's "output envelope fields": the field every `host.*`/
/// `billing.*` result MAY carry, added by requirement 3 (AC4) when the
/// call used a deprecated field -- see
/// [`deprecation_notices`]/`handler::call_tool`. Not per-tool (every
/// result is an otherwise-unstructured JSON object; this is the one
/// cross-cutting envelope field this PRD adds), so it's recorded once at
/// the top level of the dump rather than repeated per tool.
pub const OUTPUT_ENVELOPE_FIELDS: &[&str] = &["deprecations"];

/// A `contracts/deprecations.json` entry (requirement 2): `path` is a
/// dotted `<tool>` (whole-tool deprecation) or `<tool>.<field>`
/// (single-level field deprecation, e.g. `"host.tool_publish.kind"`).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Deprecation {
    pub path: String,
    /// `YYYY-MM-DD`, the version's ship date this field was announced
    /// deprecated.
    pub since: String,
    /// `YYYY-MM-DD`; [`Self::lead_time_valid`] requires this to be at
    /// least 60 days after `since`.
    pub sunset: String,
    /// What to use instead, shown to a caller via `x-deprecated` and the
    /// call-time `deprecations` note.
    pub replacement: String,
}

impl Deprecation {
    /// Requirement 2: an entry only excuses a removal/narrowing when its
    /// own lead time is at least 60 days. An entry with an unparseable
    /// date or a too-short lead time is treated as if absent -- see
    /// [`check_removed`]/[`check_narrowed`] -- so a malformed entry can
    /// never accidentally excuse a real breaking change.
    pub fn lead_time_valid(&self) -> bool {
        match (
            crate::state::parse_date_ymd_unix(&self.since),
            crate::state::parse_date_ymd_unix(&self.sunset),
        ) {
            (Some(since), Some(sunset)) => sunset - since >= 60 * 86_400,
            _ => false,
        }
    }

    /// Requirement 5: whether `today_unix` is on or after `sunset`.
    pub fn sunset_passed(&self, today_unix: i64) -> bool {
        crate::state::parse_date_ymd_unix(&self.sunset).is_some_and(|sunset| today_unix >= sunset)
    }
}

/// Load `contracts/deprecations.json`. A missing file reads as no
/// deprecations (the migration section: "v1 is the current surface; no
/// deprecations at ship") rather than an error, so a fresh checkout with
/// no such file yet still starts and tests cleanly; a present-but-invalid
/// file IS an error -- silently ignoring a malformed ledger would be
/// exactly the false confidence this PRD exists to remove.
pub fn load_deprecations(path: &std::path::Path) -> anyhow::Result<Vec<Deprecation>> {
    match std::fs::read_to_string(path) {
        Ok(raw) => Ok(serde_json::from_str(&raw)?),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(Vec::new()),
        Err(e) => Err(e.into()),
    }
}

/// The `since` this contract records for `name`. See
/// [`CONTRACT_BASELINE_SINCE`]/[`HOST_CHANGELOG_SINCE`]'s own docs.
fn since_for_tool(name: &str) -> &'static str {
    if name == "host.changelog" {
        HOST_CHANGELOG_SINCE
    } else {
        CONTRACT_BASELINE_SINCE
    }
}

/// Recursively rebuilds `value` with every object's keys inserted in
/// sorted order. `serde_json::Map`'s default (no `preserve_order` feature
/// enabled anywhere in this crate's dependency graph) already sorts keys,
/// but rebuilding explicitly here means [`dump_contract`]'s determinism
/// (requirement 1's "must be deterministic (sorted keys)") doesn't
/// silently depend on that feature staying off in a future dependency
/// bump -- see the technical considerations note it's pinned against.
fn sort_keys(value: &Value) -> Value {
    match value {
        Value::Object(map) => {
            let mut keys: Vec<&String> = map.keys().collect();
            keys.sort();
            let mut sorted = Map::new();
            for k in keys {
                sorted.insert(k.clone(), sort_keys(&map[k]));
            }
            Value::Object(sorted)
        }
        Value::Array(items) => Value::Array(items.iter().map(sort_keys).collect()),
        other => other.clone(),
    }
}

/// Requirement 1 / AC1: the whole `host.*`/`billing.*` control-plane
/// surface as one deterministic [`Value`] -- every tool's name,
/// description, input schema, and `since`, sorted by name (and, via
/// [`sort_keys`], by key at every nesting level). Always built from
/// [`KindRegistry::with_builtin`] regardless of which kinds a given
/// deployment actually registers, same convention
/// `crate::llms_txt::tenant_tool_names`'s own doc comment already
/// establishes for the tool-name set: the http/python/wasm kinds affect
/// only prose inside `host.tool_publish`'s own description (which kinds
/// are nameable), never which control-plane tools exist, so a fixed
/// registry keeps the committed contract stable across deployments.
pub fn dump_contract(kinds: &KindRegistry) -> Value {
    let mut tools = crate::handler::host_tool_descriptors(kinds);
    tools.sort_by(|a, b| a.name.cmp(&b.name));
    let entries: Vec<Value> = tools
        .iter()
        .map(|t| {
            json!({
                "name": t.name,
                "description": t.description.clone().unwrap_or_default(),
                "since": since_for_tool(&t.name),
                "input_schema": Value::Object((*t.input_schema).clone()),
            })
        })
        .collect();
    sort_keys(&json!({
        "contract_version": CONTRACT_VERSION,
        "output_envelope_fields": OUTPUT_ENVELOPE_FIELDS,
        "tools": entries,
    }))
}

/// [`dump_contract`], pretty-printed with a trailing newline -- the exact
/// bytes `mcphost contract dump` writes and AC1's test compares twice (and
/// against the committed file) for byte-identity.
pub fn dump_contract_bytes(kinds: &KindRegistry) -> Vec<u8> {
    let mut s =
        serde_json::to_string_pretty(&dump_contract(kinds)).expect("contract dump serializes");
    s.push('\n');
    s.into_bytes()
}

/// One diff finding: a tool/field removed with no (valid, sunset-passed)
/// deprecation entry to excuse it, or a field's schema narrowed in a way
/// that isn't excused either. `path` is `"<tool>"` for a whole-tool
/// removal, `"<tool>.<field>"` for a single-level field.
#[derive(Debug, Clone, PartialEq)]
pub enum Violation {
    Removed { path: String },
    RemovedBeforeSunset { path: String, sunset: String },
    Narrowed { path: String, detail: String },
}

impl Violation {
    pub fn path(&self) -> &str {
        match self {
            Violation::Removed { path }
            | Violation::RemovedBeforeSunset { path, .. }
            | Violation::Narrowed { path, .. } => path,
        }
    }

    pub fn message(&self) -> String {
        match self {
            Violation::Removed { path } => format!(
                "{path} was removed with no contracts/deprecations.json entry (or an invalid \
                 one -- sunset must be at least 60 days after since)"
            ),
            Violation::RemovedBeforeSunset { path, sunset } => format!(
                "{path} was removed before its deprecation's sunset ({sunset}) has passed"
            ),
            Violation::Narrowed { path, detail } => format!(
                "{path} was narrowed ({detail}) with no valid contracts/deprecations.json entry"
            ),
        }
    }
}

/// A entry excuses a REMOVAL only when both hold: it exists with a valid
/// (>=60 day) lead time (requirement 2), AND `today_unix` is on or after
/// its `sunset` (requirement 5) -- the field isn't actually gone from a
/// caller's perspective until that date, so removing it earlier breaks
/// exactly the caller the lead time was supposed to protect.
fn check_removed(
    path: &str,
    deprecations: &[Deprecation],
    today_unix: i64,
    violations: &mut Vec<Violation>,
) {
    match deprecations
        .iter()
        .find(|d| d.path == path && d.lead_time_valid())
    {
        None => violations.push(Violation::Removed {
            path: path.to_string(),
        }),
        Some(dep) if !dep.sunset_passed(today_unix) => {
            violations.push(Violation::RemovedBeforeSunset {
                path: path.to_string(),
                sunset: dep.sunset.clone(),
            })
        }
        Some(_) => {}
    }
}

/// A entry excuses a NARROWING as soon as it's announced with a valid
/// lead time -- unlike [`check_removed`], narrowing doesn't wait on
/// `sunset`: the field is still present and still usable (just under a
/// stricter schema), so there's no "gone from a caller's perspective"
/// moment to gate on the way an outright removal has. Requirement 2 only
/// asks for the entry to exist with a valid lead time; requirement 5's
/// extra sunset gate is stated for removal specifically.
fn check_narrowed(
    path: &str,
    detail: String,
    deprecations: &[Deprecation],
    violations: &mut Vec<Violation>,
) {
    let excused = deprecations
        .iter()
        .any(|d| d.path == path && d.lead_time_valid());
    if !excused {
        violations.push(Violation::Narrowed {
            path: path.to_string(),
            detail,
        });
    }
}

fn schema_type(schema: &Value) -> Option<&Value> {
    schema.get("type")
}

fn schema_enum(schema: &Value) -> Option<&Vec<Value>> {
    schema.get("enum").and_then(Value::as_array)
}

/// requirement 2 / Technical considerations: "narrowed type" = the new
/// schema does not accept every instance the old one did. Checked
/// structurally (type change, enum shrink, newly required) rather than by
/// generating and validating probe instances through the `jsonschema`
/// crate -- every field this crate's own `host_schema` builds is a flat
/// `{type, description}` (occasionally `enum`), so a structural comparison
/// covers every real case exactly, and stays a pure, deterministic
/// function `diff` can call with no schema-compilation cost per field.
/// `None` when nothing about `old` narrows relative to `new`.
fn narrowing_reason(old: &Value, new: &Value, was_required: bool, is_required: bool) -> Option<String> {
    if !was_required && is_required {
        return Some("became required".to_string());
    }
    if let (Some(old_type), Some(new_type)) = (schema_type(old), schema_type(new))
        && old_type != new_type
    {
        return Some(format!("type changed from {old_type} to {new_type}"));
    }
    if let Some(new_enum) = schema_enum(new) {
        match schema_enum(old) {
            // Narrowed iff the old schema didn't already accept every
            // value the new enum lists -- either it had no enum at all
            // (accepted any value of the type) or its own enum was
            // missing one of the new schema's values.
            Some(old_enum) if !new_enum.iter().all(|v| old_enum.contains(v)) => {
                return Some("enum narrowed".to_string());
            }
            None => return Some("enum added where none existed".to_string()),
            Some(_) => {}
        }
    }
    None
}

/// Walks `old_schema.properties`/`required` against `new_schema`'s own,
/// one level deep (every real `host.*` argument schema this crate builds
/// is flat -- see [`narrowing_reason`]'s doc), pushing a [`Violation`] for
/// each field removed or narrowed with no excusing entry.
#[allow(clippy::too_many_arguments)]
fn diff_properties(
    tool_name: &str,
    old_schema: &Value,
    new_schema: &Value,
    deprecations: &[Deprecation],
    today_unix: i64,
    violations: &mut Vec<Violation>,
) {
    let Some(old_props) = old_schema.get("properties").and_then(Value::as_object) else {
        return;
    };
    let new_props = new_schema.get("properties").and_then(Value::as_object);
    let old_required: Vec<&str> = old_schema
        .get("required")
        .and_then(Value::as_array)
        .map(|a| a.iter().filter_map(Value::as_str).collect())
        .unwrap_or_default();
    let new_required: Vec<&str> = new_schema
        .get("required")
        .and_then(Value::as_array)
        .map(|a| a.iter().filter_map(Value::as_str).collect())
        .unwrap_or_default();

    for (field, old_field_schema) in old_props {
        let path = format!("{tool_name}.{field}");
        match new_props.and_then(|p| p.get(field)) {
            None => check_removed(&path, deprecations, today_unix, violations),
            Some(new_field_schema) => {
                if let Some(detail) = narrowing_reason(
                    old_field_schema,
                    new_field_schema,
                    old_required.contains(&field.as_str()),
                    new_required.contains(&field.as_str()),
                ) {
                    check_narrowed(&path, detail, deprecations, violations);
                }
            }
        }
    }
}

fn tools_by_name(contract: &Value) -> std::collections::BTreeMap<String, &Value> {
    contract["tools"]
        .as_array()
        .into_iter()
        .flatten()
        .filter_map(|t| Some((t.get("name")?.as_str()?.to_string(), t)))
        .collect()
}

/// Requirements 2 and 5 / AC2, AC3, AC5: diffs `committed` (the last
/// contract dump on disk, e.g. `contracts/host-tools.v1.json`) against
/// `live` (a fresh [`dump_contract`]) and returns every unexcused breaking
/// change -- a removed tool, a removed field, or a narrowed field -- as a
/// [`Violation`] naming its path. An addition (a tool or field in `live`
/// but not `committed`) is never a violation. `today_unix` is threaded in
/// (rather than read from the clock inside) so a test can exercise both
/// sides of requirement 5's sunset gate without waiting on a real clock.
pub fn diff(
    committed: &Value,
    live: &Value,
    deprecations: &[Deprecation],
    today_unix: i64,
) -> Vec<Violation> {
    let committed_tools = tools_by_name(committed);
    let live_tools = tools_by_name(live);
    let mut violations = Vec::new();
    for (name, old_tool) in &committed_tools {
        match live_tools.get(name) {
            None => check_removed(name, deprecations, today_unix, &mut violations),
            Some(new_tool) => {
                let old_schema = old_tool.get("input_schema").unwrap_or(&Value::Null);
                let new_schema = new_tool.get("input_schema").unwrap_or(&Value::Null);
                diff_properties(
                    name,
                    old_schema,
                    new_schema,
                    deprecations,
                    today_unix,
                    &mut violations,
                );
            }
        }
    }
    violations
}

/// Requirement 3 / AC4: the `deprecations` a call to `tool` using
/// arguments `args` should surface in its result envelope -- every entry
/// whose `path` is `"<tool>.<field>"` for a top-level key actually present
/// in `args`. Never matches a whole-tool entry (`path == tool`): calling a
/// deprecated tool at all isn't "using a deprecated field", and
/// `tools/list`'s own `x-deprecated` on the tool already carries that
/// signal. Pure and synchronous, called once per `host.*`/`billing.*`
/// dispatch from `handler::call_tool`.
pub fn deprecation_notices(tool: &str, args: &Value, deprecations: &[Deprecation]) -> Vec<Value> {
    let Some(obj) = args.as_object() else {
        return Vec::new();
    };
    deprecations
        .iter()
        .filter_map(|d| {
            let field = d.path.strip_prefix(tool)?.strip_prefix('.')?;
            if field.contains('.') || !obj.contains_key(field) {
                return None;
            }
            Some(json!({
                "path": d.path,
                "since": d.since,
                "sunset": d.sunset,
                "replacement": d.replacement,
            }))
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn dump_contract_bytes_is_deterministic_across_calls() {
        let kinds = KindRegistry::with_builtin();
        assert_eq!(dump_contract_bytes(&kinds), dump_contract_bytes(&kinds));
    }

    #[test]
    fn dump_contract_sorts_tools_by_name() {
        let value = dump_contract(&KindRegistry::with_builtin());
        let names: Vec<String> = value["tools"]
            .as_array()
            .expect("tools array")
            .iter()
            .map(|t| t["name"].as_str().expect("name").to_string())
            .collect();
        let mut sorted = names.clone();
        sorted.sort();
        assert_eq!(names, sorted);
    }

    #[test]
    fn narrowing_detects_type_change_and_newly_required() {
        let string_schema = json!({"type": "string"});
        let number_schema = json!({"type": "number"});
        assert!(narrowing_reason(&string_schema, &number_schema, false, false).is_some());
        assert!(narrowing_reason(&string_schema, &string_schema, false, true).is_some());
        assert!(narrowing_reason(&string_schema, &string_schema, false, false).is_none());
        assert!(narrowing_reason(&string_schema, &string_schema, true, true).is_none());
    }

    #[test]
    fn narrowing_detects_enum_shrink_but_not_enum_growth() {
        let wide = json!({"type": "string", "enum": ["a", "b", "c"]});
        let narrow = json!({"type": "string", "enum": ["a"]});
        let wider = json!({"type": "string", "enum": ["a", "b", "c", "d"]});
        assert!(narrowing_reason(&wide, &narrow, false, false).is_some());
        assert!(narrowing_reason(&wide, &wider, false, false).is_none());
        assert!(narrowing_reason(&wide, &wide, false, false).is_none());
    }

    #[test]
    fn deprecation_lead_time_valid_requires_60_days() {
        let short = Deprecation {
            path: "x".into(),
            since: "2026-01-01".into(),
            sunset: "2026-02-01".into(), // 31 days
            replacement: "y".into(),
        };
        let long = Deprecation {
            sunset: "2026-03-02".into(), // exactly 60 days after since (2026-01-01)
            ..short.clone()
        };
        assert!(!short.lead_time_valid());
        assert!(long.lead_time_valid());
    }

    #[test]
    fn load_deprecations_missing_file_is_empty() {
        let dir = std::env::temp_dir().join(format!(
            "mcphost-deprecations-test-{}",
            crate::state::now_unix()
        ));
        let path = dir.join("deprecations.json");
        assert_eq!(load_deprecations(&path).expect("no such file"), Vec::new());
    }
}
