//! PRD-mcphost-host-tool-deprecation: the `host.*`/`billing.*` tool surface
//! as a versioned, diffable artifact.
//!
//! `contracts/host-tools.v1.json` (generated by `mcphost contract dump`,
//! requirement 1 / AC1) pins the input schema and `since` version of every
//! control-plane tool [`crate::handler::host_tool_descriptors`] builds. A
//! future PR that removes or narrows a field is caught by [`diff`] against
//! this committed baseline (requirements 2 and 5) unless
//! `contracts/deprecations.json` carries a matching, valid [`Deprecation`]
//! entry -- see that function's own doc for the exact two-gate rule.

use serde::{Deserialize, Serialize};
use serde_json::{Map, Value, json};

use crate::kinds::KindRegistry;

/// `host.whoami`'s `contract_version` (AC7) and this file's own
/// `contract_version` key.
pub const CONTRACT_VERSION: u32 = 1;

/// Default path (relative to the repo root / crate root `cargo test` runs
/// from) for the committed contract -- same "repo-relative, not
/// `$MCPHOST_DATA_DIR`-relative" convention `www/llms.txt` already uses in
/// `main.rs`'s `LlmsTxt` subcommand, since this is a static, committed
/// artifact, not per-deployment runtime data.
pub const DEFAULT_CONTRACT_PATH: &str = "contracts/host-tools.v1.json";

/// Default path for the deprecation ledger, same convention as
/// [`DEFAULT_CONTRACT_PATH`].
pub const DEFAULT_DEPRECATIONS_PATH: &str = "contracts/deprecations.json";

/// The `since` recorded for every tool that already existed when this
/// contract system shipped. This is deliberately NOT an attempt to
/// backfill each tool's true historical introduction version (that
/// history isn't recoverable from the source tree) -- it's the version as
/// of which this crate started tracking `since` at all, honestly labeled
/// as such rather than guessed per tool. A tool added after this baseline
/// (e.g. `host.changelog` itself, requirement 4 / AC6) gets its own,
/// later `since`.
pub const CONTRACT_BASELINE_SINCE: &str = "0.58.0";

/// `host.changelog`'s own `since` (requirement 4 / AC6: it must itself
/// show up as an addition). Kept in sync with `Cargo.toml`'s `version` by
/// this PRD's own version-bump commit -- see that commit's CHANGELOG.md
/// entry.
pub const HOST_CHANGELOG_SINCE: &str = "0.58.1";

/// requirement 1's "output envelope fields": the field every `host.*`/
/// `billing.*` result MAY carry, added by requirement 3 (AC4) when the
/// call used a deprecated field -- see
/// [`deprecation_notices`]/`handler::call_tool`. Not per-tool (every
/// result is an otherwise-unstructured JSON object; this is the one
/// cross-cutting envelope field this PRD adds), so it's recorded once at
/// the top level of the dump rather than repeated per tool.
pub const OUTPUT_ENVELOPE_FIELDS: &[&str] = &["deprecations"];

/// A `contracts/deprecations.json` entry (requirement 2): `path` is a
/// dotted `<tool>` (whole-tool deprecation) or `<tool>.<field>`
/// (single-level field deprecation, e.g. `"host.tool_publish.kind"`).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Deprecation {
    pub path: String,
    /// `YYYY-MM-DD`, the version's ship date this field was announced
    /// deprecated.
    pub since: String,
    /// `YYYY-MM-DD`; [`Self::lead_time_valid`] requires this to be at
    /// least 60 days after `since`.
    pub sunset: String,
    /// What to use instead, shown to a caller via `x-deprecated` and the
    /// call-time `deprecations` note.
    pub replacement: String,
}

impl Deprecation {
    /// Requirement 2: an entry only excuses a removal/narrowing when its
    /// own lead time is at least 60 days. An entry with an unparseable
    /// date or a too-short lead time is treated as if absent -- see
    /// [`check_removed`]/[`check_narrowed`] -- so a malformed entry can
    /// never accidentally excuse a real breaking change.
    pub fn lead_time_valid(&self) -> bool {
        match (
            crate::state::parse_date_ymd_unix(&self.since),
            crate::state::parse_date_ymd_unix(&self.sunset),
        ) {
            (Some(since), Some(sunset)) => sunset - since >= 60 * 86_400,
            _ => false,
        }
    }

    /// Requirement 5: whether `today_unix` is on or after `sunset`.
    pub fn sunset_passed(&self, today_unix: i64) -> bool {
        crate::state::parse_date_ymd_unix(&self.sunset).is_some_and(|sunset| today_unix >= sunset)
    }
}

/// Load `contracts/deprecations.json`. A missing file reads as no
/// deprecations (the migration section: "v1 is the current surface; no
/// deprecations at ship") rather than an error, so a fresh checkout with
/// no such file yet still starts and tests cleanly; a present-but-invalid
/// file IS an error -- silently ignoring a malformed ledger would be
/// exactly the false confidence this PRD exists to remove.
pub fn load_deprecations(path: &std::path::Path) -> anyhow::Result<Vec<Deprecation>> {
    match std::fs::read_to_string(path) {
        Ok(raw) => Ok(serde_json::from_str(&raw)?),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(Vec::new()),
        Err(e) => Err(e.into()),
    }
}

/// The `since` this contract records for `name`. See
/// [`CONTRACT_BASELINE_SINCE`]/[`HOST_CHANGELOG_SINCE`]'s own docs.
fn since_for_tool(name: &str) -> &'static str {
    if name == "host.changelog" {
        HOST_CHANGELOG_SINCE
    } else {
        CONTRACT_BASELINE_SINCE
    }
}

/// Recursively rebuilds `value` with every object's keys inserted in
/// sorted order. `serde_json::Map`'s default (no `preserve_order` feature
/// enabled anywhere in this crate's dependency graph) already sorts keys,
/// but rebuilding explicitly here means [`dump_contract`]'s determinism
/// (requirement 1's "must be deterministic (sorted keys)") doesn't
/// silently depend on that feature staying off in a future dependency
/// bump -- see the technical considerations note it's pinned against.
fn sort_keys(value: &Value) -> Value {
    match value {
        Value::Object(map) => {
            let mut keys: Vec<&String> = map.keys().collect();
            keys.sort();
            let mut sorted = Map::new();
            for k in keys {
                sorted.insert(k.clone(), sort_keys(&map[k]));
            }
            Value::Object(sorted)
        }
        Value::Array(items) => Value::Array(items.iter().map(sort_keys).collect()),
        other => other.clone(),
    }
}

/// Requirement 1 / AC1: the whole `host.*`/`billing.*` control-plane
/// surface as one deterministic [`Value`] -- every tool's name,
/// description, input schema, and `since`, sorted by name (and, via
/// [`sort_keys`], by key at every nesting level). Always built from
/// [`KindRegistry::with_builtin`] regardless of which kinds a given
/// deployment actually registers, same convention
/// `crate::llms_txt::tenant_tool_names`'s own doc comment already
/// establishes for the tool-name set: the http/python/wasm kinds affect
/// only prose inside `host.tool_publish`'s own description (which kinds
/// are nameable), never which control-plane tools exist, so a fixed
/// registry keeps the committed contract stable across deployments.
pub fn dump_contract(kinds: &KindRegistry) -> Value {
    let mut tools = crate::handler::host_tool_descriptors(kinds);
    tools.sort_by(|a, b| a.name.cmp(&b.name));
    let entries: Vec<Value> = tools
        .iter()
        .map(|t| {
            json!({
                "name": t.name,
                "description": t.description.clone().unwrap_or_default(),
                "since": since_for_tool(&t.name),
                "input_schema": Value::Object((*t.input_schema).clone()),
            })
        })
        .collect();
    sort_keys(&json!({
        "contract_version": CONTRACT_VERSION,
        "output_envelope_fields": OUTPUT_ENVELOPE_FIELDS,
        "tools": entries,
    }))
}

/// [`dump_contract`], pretty-printed with a trailing newline -- the exact
/// bytes `mcphost contract dump` writes and AC1's test compares twice (and
/// against the committed file) for byte-identity.
pub fn dump_contract_bytes(kinds: &KindRegistry) -> Vec<u8> {
    let mut s =
        serde_json::to_string_pretty(&dump_contract(kinds)).expect("contract dump serializes");
    s.push('\n');
    s.into_bytes()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn dump_contract_bytes_is_deterministic_across_calls() {
        let kinds = KindRegistry::with_builtin();
        assert_eq!(dump_contract_bytes(&kinds), dump_contract_bytes(&kinds));
    }

    #[test]
    fn dump_contract_sorts_tools_by_name() {
        let value = dump_contract(&KindRegistry::with_builtin());
        let names: Vec<String> = value["tools"]
            .as_array()
            .expect("tools array")
            .iter()
            .map(|t| t["name"].as_str().expect("name").to_string())
            .collect();
        let mut sorted = names.clone();
        sorted.sort();
        assert_eq!(names, sorted);
    }

    #[test]
    fn load_deprecations_missing_file_is_empty() {
        let dir = std::env::temp_dir().join(format!(
            "mcphost-deprecations-test-{}",
            crate::state::now_unix()
        ));
        let path = dir.join("deprecations.json");
        assert_eq!(load_deprecations(&path).expect("no such file"), Vec::new());
    }
}
