//! `mcphost gen-docs` -- PRD-mcphost-first-hour-support-surface requirement
//! 3: regenerates `docs/plans.md` from `billing::plans_from_catalog` over
//! [`crate::plans::PlanCatalog::default_catalog`], the exact same function
//! `billing.plans`/`/plans.json` call over whatever catalog is actually
//! loaded. Same `--check` convention as `mcphost llms-txt`: write by
//! default, exit 1 (naming the stale file) under `--check` without writing,
//! so this can run as a pre-commit/CI drift gate the way `www-check.sh`/
//! `docs-check.sh` already do for the other generated files in this repo.
//!
//! `www/plans.html` is also regenerated here ([`render_plans_html`]): it's
//! a static shell (same convention as `www/status.html`) that fetches the
//! live `/plans.json` client-side rather than embedding catalog numbers,
//! so it never drifts from the catalog by construction -- but it is still
//! rendered from this module's own Rust constant, not just read back from
//! the committed file, so a hand-edit to the committed copy is caught by
//! `--check` the same way a `docs/plans.md` hand-edit is (AC4: "`docs/
//! plans.md` and `www/plans.html` are regenerated byte-identically").
//!
//! AC5's build-time half -- splicing `MCPHOST_SUPPORT_URL` into README,
//! `docs/agent-quickstart.md`, and `www/llms.txt`'s `<!-- support:start/
//! end -->` sections -- also runs here, via [`crate::help::
//! splice_support_section`]. `www/help/<code>.html` and `www/support.html`
//! are the one pair that is still NOT a generated file -- `/help/<code>`,
//! `/help`, and `/support.html` are rendered by `src/http.rs` at request
//! time from `help::HELP_ENTRIES` plus whatever `MCPHOST_SUPPORT_URL` the
//! live process has *right now*, so an operator setting that env var takes
//! effect on those three without a rebuild (see `help.rs`'s own module doc
//! comment).

use std::path::Path;

use crate::help;
use crate::plans::{Plan, PlanCatalog};

pub const PLANS_DOC_PATH: &str = "docs/plans.md";
pub const PLANS_HTML_PATH: &str = "www/plans.html";

/// AC5's three build-time docs -- plain repo files, never served at
/// request time, so `MCPHOST_SUPPORT_URL`'s value for them is baked in at
/// `mcphost gen-docs` time (see this module's own doc comment) and
/// committed.
pub const SUPPORT_SPLICED_DOCS: &[&str] =
    &["README.md", "docs/agent-quickstart.md", "www/llms.txt"];

/// One `billing::plans_from_catalog`-shaped row, rendered as a markdown
/// table row -- requirement 3's own fields (name, price, tools, calls/day,
/// secrets), plus a short prose description already on the `Plan` struct.
fn render_plan_row(p: &Plan) -> String {
    format!(
        "| {name} | ${price}/mo | {tools} | {calls} | {secrets} | {description} |",
        name = p.name,
        price = p.price_usd_month,
        tools = p.tools_max,
        calls = p.calls_per_day,
        secrets = p.secrets_max,
        description = p.description,
    )
}

/// The one function both [`run`] (writes/`--check`s the committed file) and
/// `tests/support_ac04_*` (the hermetic "byte-identical to a fresh render"
/// AC4 test) call -- the single source `docs/plans.md`'s own committed text
/// must always equal.
pub fn render_plans_markdown(catalog: &PlanCatalog) -> String {
    let mut out = String::new();
    out.push_str("# Plans\n\n");
    out.push_str(
        "Generated by `mcphost gen-docs` from the same `PlanCatalog` the \
         `billing.plans` tool and `/plans.json` read -- these numbers can't \
         drift from what the server actually enforces. Do not hand-edit; \
         run `mcphost gen-docs` after changing `plans.toml` (or its \
         built-in defaults) instead.\n\n",
    );
    out.push_str("| plan | price | tools | calls/day | secrets | description |\n");
    out.push_str("|---|---|---|---|---|---|\n");
    for plan in &catalog.plans {
        out.push_str(&render_plan_row(plan));
        out.push('\n');
    }
    out.push_str(
        "\nStorage, table, job-concurrency, and every other per-plan quota \
         (state/table/docs byte caps, `jobs_concurrent`, `channels_max`, \
         ...) are visible on a signed-up tenant's own `host.whoami` and \
         `host.usage`, and in `admin.usage` for an operator -- this page \
         covers the five numbers a developer decides on *before* signing \
         up, the ones `billing.plans` itself returns.\n",
    );
    out.push_str("\nMachine-readable: [`/plans.json`](/plans.json).\n");
    out
}

/// AC4's other generated file: `www/plans.html`'s committed text must
/// always equal this. A static shell -- it carries no catalog data, only
/// a client-side fetch of `/plans.json` -- but it is rendered from this
/// constant, not read back from the file on disk, so a hand-edit still
/// shows up as drift under `--check`.
pub fn render_plans_html() -> String {
    PLANS_HTML_TEMPLATE.to_string()
}

const PLANS_HTML_TEMPLATE: &str = r###"<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>mcphost — plans</title>
<meta name="description" content="mcphost's plan catalog -- the same numbers the billing.plans tool and /plans.json return. Nothing on this page is estimated.">
<style>
  /* Committed single look: same palette as status.html/aup.html. */
  :root { color-scheme: dark; }
  * { box-sizing: border-box; }
  body { margin: 0; background: #0b0d0e; color: #c9cdd1;
         font-family: ui-monospace, "Cascadia Mono", "DejaVu Sans Mono", Menlo, Consolas, monospace;
         font-size: 15px; line-height: 1.65; }
  .wrap { max-width: 44rem; margin: 0 auto; padding: 3.5rem 1.4rem 4rem; }
  h1 { font-size: 1.05rem; font-weight: 600; color: #e6edf3; margin: 0 0 .3rem; }
  h1::before { content: "# "; color: #484f58; font-weight: 400; }
  h2 { font-size: .95rem; font-weight: 600; color: #e6edf3; margin: 2.2rem 0 .6rem; }
  h2::before { content: "## "; color: #484f58; font-weight: 400; }
  p { margin: 0 0 1rem; }
  code { color: #e6edf3; background: #161b22; padding: .1em .35em; border-radius: 4px; }
  a { color: #58a6ff; text-decoration: none; }
  a:hover { text-decoration: underline; }
  table { border-collapse: collapse; width: 100%; margin: 0 0 1.2rem; }
  th, td { text-align: left; padding: .35rem .7rem .35rem 0; border-bottom: 1px solid #21262d; }
  th { color: #8b949e; font-weight: 400; }
  .dim { color: #8b949e; }
  footer { margin-top: 3rem; padding-top: 1.2rem; border-top: 1px solid #21262d;
           color: #8b949e; font-size: .9em; }
</style>
</head>
<body>
<main class="wrap">
<h1>plans</h1>
<p class="dim">The plan catalog, fetched live from <code>/plans.json</code> -- the same data the <code>billing.plans</code> tool and <code>docs/plans.md</code> read. No card required for Free.</p>

<div id="plans-fallback" class="dim">
  <p>Live catalog is not reachable from here. Raw feed: <a href="/plans.json">/plans.json</a>.</p>
</div>
<table id="plans-table" hidden>
  <thead><tr><th>plan</th><th>price</th><th>tools</th><th>calls/day</th><th>secrets</th><th>description</th></tr></thead>
  <tbody id="plans-rows"></tbody>
</table>
<p id="billing-mode" class="dim" hidden></p>

<h2>see for yourself</h2>
<p>Machine-readable: <a href="/plans.json">/plans.json</a> · Generated doc: <a href="https://github.com/j0yen/mcphost/blob/main/docs/plans.md">docs/plans.md</a> · Every other quota (storage, jobs, channels, ...): a signed-up tenant's own <code>host.whoami</code>/<code>host.usage</code>.</p>

<footer><a href="/">mcphost</a> · <a href="/status.html">status</a> · <a href="/support.html">support</a> · <a href="/help">help</a></footer>
</main>
<script>
(function () {
  "use strict";
  var fallback = document.getElementById("plans-fallback");
  var table = document.getElementById("plans-table");
  var rows = document.getElementById("plans-rows");
  var mode = document.getElementById("billing-mode");

  function esc(s) {
    var d = document.createElement("div");
    d.textContent = String(s);
    return d.innerHTML;
  }

  fetch("/plans.json", { cache: "no-store" })
    .then(function (r) {
      if (!r.ok) { throw new Error("plans.json answered " + r.status); }
      return r.json();
    })
    .then(function (data) {
      var plans = data.plans || [];
      rows.innerHTML = plans.map(function (p) {
        return "<tr><td>" + esc(p.name) + "</td><td>$" + esc(p.price_usd_month) + "/mo</td><td>" +
          esc(p.tools_max) + "</td><td>" + esc(p.calls_per_day) + "</td><td>" + esc(p.secrets_max) +
          "</td><td>" + esc(p.description) + "</td></tr>";
      }).join("");
      mode.textContent = "billing_mode: " + data.billing_mode;
      mode.hidden = false;
      fallback.hidden = true;
      table.hidden = false;
    })
    .catch(function () {
      fallback.hidden = false;
      table.hidden = true;
    });
})();
</script>
</body>
</html>
"###;

/// Every [`SUPPORT_SPLICED_DOCS`] path, read from disk, paired with what it
/// would become after splicing `support_url` into its `<!-- support:
/// start/end -->` section(s) -- the one function both [`run`] and
/// `tests/support_ac05_*` call, so the two can never disagree on what
/// "spliced" means.
fn support_spliced_docs(support_url: Option<&str>) -> std::io::Result<Vec<(&'static str, String, String)>> {
    SUPPORT_SPLICED_DOCS
        .iter()
        .map(|&path| {
            let current = std::fs::read_to_string(path)?;
            let spliced = help::splice_support_section(&current, support_url);
            Ok((path, current, spliced))
        })
        .collect()
}

/// Writes (or, under `check`, diffs without writing) `docs/plans.md`,
/// `www/plans.html`, and -- AC5's build-time half -- the `<!-- support:
/// start/end -->` sections of [`SUPPORT_SPLICED_DOCS`], relative to the
/// current directory -- same convention as `Command::LlmsTxt`'s own
/// `check`/write split. Returns `Ok(true)` iff anything was stale
/// (meaningful only under `check`; under write it always returns
/// `Ok(false)`, nothing left for the caller to act on).
pub fn run(check: bool) -> std::io::Result<bool> {
    let catalog = PlanCatalog::default_catalog();
    let rendered_md = render_plans_markdown(&catalog);
    let rendered_html = render_plans_html();
    let support_url = std::env::var("MCPHOST_SUPPORT_URL").ok();
    let support_docs = support_spliced_docs(support_url.as_deref())?;

    let md_path = Path::new(PLANS_DOC_PATH);
    let html_path = Path::new(PLANS_HTML_PATH);

    if check {
        let mut stale = false;
        let current_md = std::fs::read_to_string(md_path).unwrap_or_default();
        if current_md != rendered_md {
            eprintln!("gen-docs --check: {PLANS_DOC_PATH} is stale (run `mcphost gen-docs`)");
            stale = true;
        }
        let current_html = std::fs::read_to_string(html_path).unwrap_or_default();
        if current_html != rendered_html {
            eprintln!("gen-docs --check: {PLANS_HTML_PATH} is stale (run `mcphost gen-docs`)");
            stale = true;
        }
        for (path, current, spliced) in &support_docs {
            if current != spliced {
                eprintln!("gen-docs --check: {path} is stale (run `mcphost gen-docs`)");
                stale = true;
            }
        }
        Ok(stale)
    } else {
        std::fs::write(md_path, rendered_md)?;
        std::fs::write(html_path, rendered_html)?;
        for (path, _current, spliced) in &support_docs {
            std::fs::write(path, spliced)?;
        }
        Ok(false)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// AC4: `docs/plans.md` is byte-identical to a fresh render over
    /// `default_catalog()` -- the hermetic half of AC4 (the live half,
    /// "`/plans.json` equals the `billing.plans` tool output", is
    /// `tests/support_ac04_plans_doc_and_json_consistent.rs`, which needs a
    /// running server).
    #[test]
    fn committed_plans_doc_matches_a_fresh_render() {
        let committed = include_str!("../docs/plans.md");
        let fresh = render_plans_markdown(&PlanCatalog::default_catalog());
        assert_eq!(
            committed, fresh,
            "docs/plans.md has drifted from PlanCatalog::default_catalog() -- run `mcphost gen-docs`"
        );
    }

    /// AC4's other half: `www/plans.html` is byte-identical to a fresh
    /// render of [`render_plans_html`] -- deleting or hand-editing the
    /// generation step fails this the same way a `docs/plans.md` drift
    /// does above.
    #[test]
    fn committed_plans_html_matches_a_fresh_render() {
        let committed = include_str!("../www/plans.html");
        let fresh = render_plans_html();
        assert_eq!(committed, fresh, "www/plans.html has drifted -- run `mcphost gen-docs`");
    }
}
