//! `mcphost gen-docs` -- PRD-mcphost-first-hour-support-surface requirement
//! 3: regenerates `docs/plans.md` from `billing::plans_from_catalog` over
//! [`crate::plans::PlanCatalog::default_catalog`], the exact same function
//! `billing.plans`/`/plans.json` call over whatever catalog is actually
//! loaded. Same `--check` convention as `mcphost llms-txt`: write by
//! default, exit 1 (naming the stale file) under `--check` without writing,
//! so this can run as a pre-commit/CI drift gate the way `www-check.sh`/
//! `docs-check.sh` already do for the other generated files in this repo.
//!
//! `www/plans.html` is deliberately NOT generated here: it's a static shell
//! (same convention as `www/status.html`) that fetches the live
//! `/plans.json` client-side, so it never drifts from the catalog by
//! construction and needs no regeneration step.
//! `www/help/<code>.html` and `www/support.html` are also not generated
//! files -- `/help/<code>`, `/help`, and `/support.html` are rendered by
//! `src/http.rs` at request time from `help::HELP_ENTRIES` plus whatever
//! `MCPHOST_SUPPORT_URL` the live process has *right now*, so an operator
//! setting that env var takes effect without a rebuild (see `help.rs`'s own
//! module doc comment).

use std::path::Path;

use crate::plans::{Plan, PlanCatalog};

pub const PLANS_DOC_PATH: &str = "docs/plans.md";

/// One `billing::plans_from_catalog`-shaped row, rendered as a markdown
/// table row -- requirement 3's own fields (name, price, tools, calls/day,
/// secrets), plus a short prose description already on the `Plan` struct.
fn render_plan_row(p: &Plan) -> String {
    format!(
        "| {name} | ${price}/mo | {tools} | {calls} | {secrets} | {description} |",
        name = p.name,
        price = p.price_usd_month,
        tools = p.tools_max,
        calls = p.calls_per_day,
        secrets = p.secrets_max,
        description = p.description,
    )
}

/// The one function both [`run`] (writes/`--check`s the committed file) and
/// `tests/support_ac04_*` (the hermetic "byte-identical to a fresh render"
/// AC4 test) call -- the single source `docs/plans.md`'s own committed text
/// must always equal.
pub fn render_plans_markdown(catalog: &PlanCatalog) -> String {
    let mut out = String::new();
    out.push_str("# Plans\n\n");
    out.push_str(
        "Generated by `mcphost gen-docs` from the same `PlanCatalog` the \
         `billing.plans` tool and `/plans.json` read -- these numbers can't \
         drift from what the server actually enforces. Do not hand-edit; \
         run `mcphost gen-docs` after changing `plans.toml` (or its \
         built-in defaults) instead.\n\n",
    );
    out.push_str("| plan | price | tools | calls/day | secrets | description |\n");
    out.push_str("|---|---|---|---|---|---|\n");
    for plan in &catalog.plans {
        out.push_str(&render_plan_row(plan));
        out.push('\n');
    }
    out.push_str(
        "\nStorage, table, job-concurrency, and every other per-plan quota \
         (state/table/docs byte caps, `jobs_concurrent`, `channels_max`, \
         ...) are visible on a signed-up tenant's own `host.whoami` and \
         `host.usage`, and in `admin.usage` for an operator -- this page \
         covers the five numbers a developer decides on *before* signing \
         up, the ones `billing.plans` itself returns.\n",
    );
    out.push_str("\nMachine-readable: [`/plans.json`](/plans.json).\n");
    out
}

/// Writes (or, under `check`, diffs without writing) `docs/plans.md`
/// relative to the current directory -- same convention as
/// `Command::LlmsTxt`'s own `check`/write split. Returns `Ok(true)` iff the
/// file was stale (meaningful only under `check`; under write it always
/// returns `Ok(false)`, nothing left for the caller to act on).
pub fn run(check: bool) -> std::io::Result<bool> {
    let catalog = PlanCatalog::default_catalog();
    let rendered = render_plans_markdown(&catalog);
    let path = Path::new(PLANS_DOC_PATH);

    if check {
        let current = std::fs::read_to_string(path).unwrap_or_default();
        if current == rendered {
            Ok(false)
        } else {
            eprintln!("gen-docs --check: {PLANS_DOC_PATH} is stale (run `mcphost gen-docs`)");
            Ok(true)
        }
    } else {
        std::fs::write(path, rendered)?;
        Ok(false)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// AC4: `docs/plans.md` is byte-identical to a fresh render over
    /// `default_catalog()` -- the hermetic half of AC4 (the live half,
    /// "`/plans.json` equals the `billing.plans` tool output", is
    /// `tests/support_ac04_plans_doc_and_json_consistent.rs`, which needs a
    /// running server).
    #[test]
    fn committed_plans_doc_matches_a_fresh_render() {
        let committed = include_str!("../docs/plans.md");
        let fresh = render_plans_markdown(&PlanCatalog::default_catalog());
        assert_eq!(
            committed, fresh,
            "docs/plans.md has drifted from PlanCatalog::default_catalog() -- run `mcphost gen-docs`"
        );
    }
}
