//! PRD-mcphost-surface-fluidity requirement 4 (P0, AC5): `www/llms.txt`'s
//! tool list is generated from the same descriptors `tools/list` serves,
//! rather than hand-maintained prose that drifts (the 2026-09-09 audit
//! found 14 documented vs 18 live tenant tools). This module is the pure,
//! synchronous half -- name collection and markdown rendering -- shared by
//! the `mcphost llms-txt` subcommand (`main.rs`) and
//! `tests/surface_ac05_llms_txt_tool_parity.rs`, so neither needs a running
//! server or a DB to exercise it.

use crate::handler::llms_txt_tool_names;
use crate::kinds::KindRegistry;

pub const TOOLS_SECTION_START: &str = "<!-- tools:start -->";
pub const TOOLS_SECTION_END: &str = "<!-- tools:end -->";

/// Every tenant-visible tool name across both auth states, sorted and
/// deduplicated: `signup` (visible only pre-auth) union `handler.rs`'s
/// authenticated `host_tools` superset (which already includes every
/// `host.*`/`billing.*` descriptor and is a strict superset of the
/// anonymous list -- the only gated entry is `host.spec_test`). This is the
/// same union a client would see by calling `tools/list` once anonymous and
/// once authenticated, which is how AC5's own test builds its "live" side.
pub fn tenant_tool_names(kinds: &KindRegistry) -> Vec<String> {
    let mut names: Vec<String> = std::iter::once("signup".to_string())
        .chain(llms_txt_tool_names(kinds))
        .collect();
    names.sort();
    names.dedup();
    names
}

/// Render the generated `## Tools` section, bracketed by
/// [`TOOLS_SECTION_START`]/[`TOOLS_SECTION_END`] markers so
/// [`splice_into`] can find and replace it on a re-run without disturbing
/// the rest of the hand-written file.
pub fn render_tools_section(kinds: &KindRegistry) -> String {
    let mut out = String::new();
    out.push_str(TOOLS_SECTION_START);
    out.push('\n');
    out.push_str("## Tools\n\n");
    out.push_str(
        "Generated by `mcphost llms-txt` from the same descriptors `tools/list` serves \
         -- do not hand-edit; every name below is also in a live `tools/list` (anonymous \
         or authenticated).\n\n",
    );
    for name in tenant_tool_names(kinds) {
        out.push_str(&format!("- `{name}`\n"));
    }
    out.push_str(TOOLS_SECTION_END);
    out
}

/// Replace the section between the markers in `content` with `section`, or
/// -- on a first run, before any marker exists -- insert `section` just
/// before the `## Full documentation` heading. Falls back to appending at
/// the end if neither is found, so this never silently drops the section.
pub fn splice_into(content: &str, section: &str) -> String {
    let section = section.trim_end();
    if let (Some(start), Some(end_marker_pos)) =
        (content.find(TOOLS_SECTION_START), content.find(TOOLS_SECTION_END))
    {
        let end = end_marker_pos + TOOLS_SECTION_END.len();
        format!(
            "{}{}\n{}",
            &content[..start],
            section,
            content[end..].trim_start_matches('\n')
        )
    } else if let Some(idx) = content.find("## Full documentation") {
        format!("{}{}\n\n{}", &content[..idx], section, &content[idx..])
    } else {
        format!("{}\n\n{}\n", content.trim_end(), section)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn splice_into_replaces_an_existing_section_idempotently() {
        let content = format!(
            "before\n\n{TOOLS_SECTION_START}\nold\n{TOOLS_SECTION_END}\n\nafter\n"
        );
        let spliced = splice_into(&content, "<!-- tools:start -->\nnew\n<!-- tools:end -->");
        assert!(spliced.contains("new"));
        assert!(!spliced.contains("old"));
        assert!(spliced.starts_with("before"));
        assert!(spliced.trim_end().ends_with("after"));
    }

    #[test]
    fn splice_into_inserts_before_full_documentation_on_first_run() {
        let content = "intro\n\n## Full documentation\n\nmore\n";
        let section = render_tools_section(&KindRegistry::with_builtin());
        let spliced = splice_into(content, &section);
        assert!(spliced.contains(TOOLS_SECTION_START));
        let tools_pos = spliced.find(TOOLS_SECTION_START).unwrap();
        let full_docs_pos = spliced.find("## Full documentation").unwrap();
        assert!(tools_pos < full_docs_pos);
    }

    #[test]
    fn tenant_tool_names_includes_signup_and_is_sorted_unique() {
        let names = tenant_tool_names(&KindRegistry::with_builtin());
        assert!(names.contains(&"signup".to_string()));
        assert!(names.contains(&"host.tool_publish".to_string()));
        assert!(names.contains(&"host.bridge_test".to_string()));
        let mut sorted = names.clone();
        sorted.sort();
        sorted.dedup();
        assert_eq!(names, sorted);
    }
}
