//! PRD-mcphost-tool-naming-convention-and-aliases requirement 4: `docs/tools.md`
//! generated from the live registry (`handler::host_tool_descriptors`), so
//! it cannot drift from `tools/list` the way hand-maintained docs have
//! before (the 2026-09-30 audit's "names drift silently in four places").
//! Pure and synchronous, same `mcphost <subcommand> [--check]` split as
//! `llms_txt.rs`/`api_contract.rs`.

use crate::handler::host_tool_descriptors;
use crate::kinds::KindRegistry;
use crate::tool_aliases::{self, ALIASES};

/// The "Family" column: `host.<family>` for a dotted `host.*` name, `host
/// (singleton)` for one of [`crate::tool_aliases::SINGLETON_NOUN_EXCEPTIONS`],
/// or the segment before the first dot for a non-`host.*` top-level name
/// (`billing.*`).
fn family_of(name: &str) -> String {
    if let Some(rest) = name.strip_prefix("host.") {
        match rest.split_once('.') {
            Some((family, _)) => format!("host.{family}"),
            None => "host (singleton)".to_string(),
        }
    } else if let Some((family, _)) = name.split_once('.') {
        family.to_string()
    } else {
        "(top-level)".to_string()
    }
}

/// A table cell: `|` and newlines would otherwise break the markdown
/// table's row structure.
fn escape_cell(s: &str) -> String {
    s.replace('|', "\\|").replace('\n', " ")
}

/// Render `docs/tools.md` in full (requirement 4): every canonical
/// `host.*`/`billing.*` tool with its family and description, then a
/// "Renamed tools" table -- one row per [`ALIASES`] entry -- naming the
/// replacement and sunset date. `admin.*` and `signup` are out of this
/// doc's scope: `admin.*` is a separate, operator-only naming rule (PRD
/// non-goals) and `signup` is documented in `docs/agent-quickstart.md`.
pub fn render_tools_doc(kinds: &KindRegistry) -> String {
    let mut tools = host_tool_descriptors(kinds);
    tools.sort_by(|a, b| a.name.cmp(&b.name));

    let mut out = String::new();
    out.push_str("# Tool surface\n\n");
    out.push_str(
        "Generated by `mcphost tools-doc` from the live registry -- do not hand-edit. \
         See [tool-naming.md](tool-naming.md) for the rule this table enforces. `admin.*` \
         (operator-only) and `signup` (see [agent-quickstart.md](agent-quickstart.md)) are \
         out of this doc's scope.\n\n",
    );
    out.push_str("## Tools\n\n");
    out.push_str("| Tool | Family | Description |\n|---|---|---|\n");
    for tool in &tools {
        if tool_aliases::canonical_for_alias(tool.name.as_ref()).is_some() {
            continue; // aliases get their own table below, not this one
        }
        let desc = tool.description.as_deref().unwrap_or("");
        out.push_str(&format!(
            "| `{}` | {} | {} |\n",
            tool.name,
            family_of(tool.name.as_ref()),
            escape_cell(desc)
        ));
    }

    out.push_str("\n## Renamed tools (deprecated aliases)\n\n");
    out.push_str(
        "Each of these still works, unchanged, through its sunset date. Calling one returns \
         the same result as its replacement, plus a deprecation hint -- see \
         [tool-naming.md](tool-naming.md).\n\n",
    );
    out.push_str("| Old name | Replacement | Sunset |\n|---|---|---|\n");
    for (alias, canonical) in ALIASES {
        out.push_str(&format!(
            "| `{alias}` | `{canonical}` | {} |\n",
            tool_aliases::ALIAS_SUNSET_DATE
        ));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_tools_doc_lists_every_alias_exactly_once_and_no_alias_in_the_main_table() {
        let doc = render_tools_doc(&KindRegistry::with_builtin());
        for (alias, canonical) in ALIASES {
            assert_eq!(
                doc.matches(&format!("`{alias}`")).count(),
                1,
                "{alias} should appear exactly once (in the renamed-tools table): {doc}"
            );
            assert!(doc.contains(&format!("`{canonical}`")), "{canonical} missing: {doc}");
        }
    }

    #[test]
    fn render_tools_doc_is_deterministic() {
        let kinds = KindRegistry::with_builtin();
        assert_eq!(render_tools_doc(&kinds), render_tools_doc(&kinds));
    }
}
